apiVersion: v1
kind: Service
metadata:
  name: netbox-go-svc
  namespace: netbox-go
spec:
  selector:
    app: netbox-go
  type: ClusterIP
  ports:
    - name: netbox-go-svc-grpc-port
      port: 7682
      targetPort: 7682
    - name: netbox-go-svc-grpc-metrics-port
      port: 7683
      targetPort: 7683
