// Code generated by https://github.com/go-dev-frame/sponge

package ecode

import (
	"github.com/go-dev-frame/sponge/pkg/errcode"
)

// circuitsCircuit business-level rpc error codes.
// the _circuitsCircuitNO value range is 1~999, if the same error code is used, it will cause panic.
var (
	_circuitsCircuitNO       = 4
	_circuitsCircuitName     = "circuitsCircuit"
	_circuitsCircuitBaseCode = errcode.RCode(_circuitsCircuitNO)

	StatusCreateCircuitsCircuit         = errcode.NewRPCStatus(_circuitsCircuitBaseCode+1, "failed to Create "+_circuitsCircuitName)
	StatusDeleteByIDCircuitsCircuit     = errcode.NewRPCStatus(_circuitsCircuitBaseCode+2, "failed to DeleteByID "+_circuitsCircuitName)
	StatusUpdateByIDCircuitsCircuit     = errcode.NewRPCStatus(_circuitsCircuitBaseCode+3, "failed to UpdateByID "+_circuitsCircuitName)
	StatusGetByIDCircuitsCircuit        = errcode.NewRPCStatus(_circuitsCircuitBaseCode+4, "failed to GetByID "+_circuitsCircuitName)
	StatusListCircuitsCircuit           = errcode.NewRPCStatus(_circuitsCircuitBaseCode+5, "failed to List "+_circuitsCircuitName)
	StatusDeleteByIDsCircuitsCircuit    = errcode.NewRPCStatus(_circuitsCircuitBaseCode+6, "failed to DeleteByIDs "+_circuitsCircuitName)
	StatusGetByConditionCircuitsCircuit = errcode.NewRPCStatus(_circuitsCircuitBaseCode+7, "failed to GetByCondition "+_circuitsCircuitName)
	StatusListByIDsCircuitsCircuit      = errcode.NewRPCStatus(_circuitsCircuitBaseCode+8, "failed to ListByIDs "+_circuitsCircuitName)
	StatusListByLastIDCircuitsCircuit   = errcode.NewRPCStatus(_circuitsCircuitBaseCode+9, "failed to ListByLastID "+_circuitsCircuitName)

	// error codes are globally unique, adding 1 to the previous error code
)
