// Code generated by https://github.com/go-dev-frame/sponge

package ecode

import (
	"github.com/go-dev-frame/sponge/pkg/errcode"
)

// ipamIprange business-level rpc error codes.
// the _ipamIprangeNO value range is 1~999, if the same error code is used, it will cause panic.
var (
	_ipamIprangeNO       = 125
	_ipamIprangeName     = "ipamIprange"
	_ipamIprangeBaseCode = errcode.RCode(_ipamIprangeNO)

	StatusCreateIpamIprange         = errcode.NewRPCStatus(_ipamIprangeBaseCode+1, "failed to Create "+_ipamIprangeName)
	StatusDeleteByIDIpamIprange     = errcode.NewRPCStatus(_ipamIprangeBaseCode+2, "failed to DeleteByID "+_ipamIprangeName)
	StatusUpdateByIDIpamIprange     = errcode.NewRPCStatus(_ipamIprangeBaseCode+3, "failed to UpdateByID "+_ipamIprangeName)
	StatusGetByIDIpamIprange        = errcode.NewRPCStatus(_ipamIprangeBaseCode+4, "failed to GetByID "+_ipamIprangeName)
	StatusListIpamIprange           = errcode.NewRPCStatus(_ipamIprangeBaseCode+5, "failed to List "+_ipamIprangeName)
	StatusDeleteByIDsIpamIprange    = errcode.NewRPCStatus(_ipamIprangeBaseCode+6, "failed to DeleteByIDs "+_ipamIprangeName)
	StatusGetByConditionIpamIprange = errcode.NewRPCStatus(_ipamIprangeBaseCode+7, "failed to GetByCondition "+_ipamIprangeName)
	StatusListByIDsIpamIprange      = errcode.NewRPCStatus(_ipamIprangeBaseCode+8, "failed to ListByIDs "+_ipamIprangeName)
	StatusListByLastIDIpamIprange   = errcode.NewRPCStatus(_ipamIprangeBaseCode+9, "failed to ListByLastID "+_ipamIprangeName)

	// error codes are globally unique, adding 1 to the previous error code
)
