// Code generated by https://github.com/go-dev-frame/sponge

package ecode

import (
	"github.com/go-dev-frame/sponge/pkg/errcode"
)

// ipamRole business-level rpc error codes.
// the _ipamRoleNO value range is 1~999, if the same error code is used, it will cause panic.
var (
	_ipamRoleNO       = 128
	_ipamRoleName     = "ipamRole"
	_ipamRoleBaseCode = errcode.RCode(_ipamRoleNO)

	StatusCreateIpamRole         = errcode.NewRPCStatus(_ipamRoleBaseCode+1, "failed to Create "+_ipamRoleName)
	StatusDeleteByIDIpamRole     = errcode.NewRPCStatus(_ipamRoleBaseCode+2, "failed to DeleteByID "+_ipamRoleName)
	StatusUpdateByIDIpamRole     = errcode.NewRPCStatus(_ipamRoleBaseCode+3, "failed to UpdateByID "+_ipamRoleName)
	StatusGetByIDIpamRole        = errcode.NewRPCStatus(_ipamRoleBaseCode+4, "failed to GetByID "+_ipamRoleName)
	StatusListIpamRole           = errcode.NewRPCStatus(_ipamRoleBaseCode+5, "failed to List "+_ipamRoleName)
	StatusDeleteByIDsIpamRole    = errcode.NewRPCStatus(_ipamRoleBaseCode+6, "failed to DeleteByIDs "+_ipamRoleName)
	StatusGetByConditionIpamRole = errcode.NewRPCStatus(_ipamRoleBaseCode+7, "failed to GetByCondition "+_ipamRoleName)
	StatusListByIDsIpamRole      = errcode.NewRPCStatus(_ipamRoleBaseCode+8, "failed to ListByIDs "+_ipamRoleName)
	StatusListByLastIDIpamRole   = errcode.NewRPCStatus(_ipamRoleBaseCode+9, "failed to ListByLastID "+_ipamRoleName)

	// error codes are globally unique, adding 1 to the previous error code
)
