// Code generated by https://github.com/go-dev-frame/sponge

package ecode

import (
	"github.com/go-dev-frame/sponge/pkg/errcode"
)

// usersGroup business-level rpc error codes.
// the _usersGroupNO value range is 1~999, if the same error code is used, it will cause panic.
var (
	_usersGroupNO       = 157
	_usersGroupName     = "usersGroup"
	_usersGroupBaseCode = errcode.RCode(_usersGroupNO)

	StatusCreateUsersGroup         = errcode.NewRPCStatus(_usersGroupBaseCode+1, "failed to Create "+_usersGroupName)
	StatusDeleteByIDUsersGroup     = errcode.NewRPCStatus(_usersGroupBaseCode+2, "failed to DeleteByID "+_usersGroupName)
	StatusUpdateByIDUsersGroup     = errcode.NewRPCStatus(_usersGroupBaseCode+3, "failed to UpdateByID "+_usersGroupName)
	StatusGetByIDUsersGroup        = errcode.NewRPCStatus(_usersGroupBaseCode+4, "failed to GetByID "+_usersGroupName)
	StatusListUsersGroup           = errcode.NewRPCStatus(_usersGroupBaseCode+5, "failed to List "+_usersGroupName)
	StatusDeleteByIDsUsersGroup    = errcode.NewRPCStatus(_usersGroupBaseCode+6, "failed to DeleteByIDs "+_usersGroupName)
	StatusGetByConditionUsersGroup = errcode.NewRPCStatus(_usersGroupBaseCode+7, "failed to GetByCondition "+_usersGroupName)
	StatusListByIDsUsersGroup      = errcode.NewRPCStatus(_usersGroupBaseCode+8, "failed to ListByIDs "+_usersGroupName)
	StatusListByLastIDUsersGroup   = errcode.NewRPCStatus(_usersGroupBaseCode+9, "failed to ListByLastID "+_usersGroupName)

	// error codes are globally unique, adding 1 to the previous error code
)
