syntax = "proto3";

package netbox.ipam.v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "netbox/types/v1/pagination.proto";

option go_package = "netbox-go/gen/go/netbox/ipam/v1;ipamv1";

message VRF {
  int64 id = 1;
  string url = 2;
  string display = 3;
  string name = 4;
  google.protobuf.StringValue rd = 5;
  bool enforce_unique = 6;
  string description = 7;
  string comments = 8;
  google.protobuf.Timestamp created = 9;
  google.protobuf.Timestamp last_updated = 10;
  uint64 ipaddress_count = 11;
  uint64 prefix_count = 12;
}

message VRFInput {
  optional string name = 1;
  google.protobuf.StringValue rd = 2;
  optional bool enforce_unique = 3;
  optional string description = 4;
  optional string comments = 5;
}

message Prefix {
  int64 id = 1;
  string url = 2;
  string display = 3;
  string prefix = 4;
  google.protobuf.Int64Value vrf_id = 5;
  string status = 6;
  bool is_pool = 7;
  bool mark_utilized = 8;
  string description = 9;
  string comments = 10;
  google.protobuf.Timestamp created = 11;
  google.protobuf.Timestamp last_updated = 12;
  uint32 family = 13;
  uint64 children = 14;
  uint32 depth = 15;
}

message PrefixInput {
  optional string prefix = 1;
  google.protobuf.Int64Value vrf = 2;
  optional string status = 3;
  optional bool is_pool = 4;
  optional bool mark_utilized = 5;
  optional string description = 6;
  optional string comments = 7;
}

message IPAddress {
  int64 id = 1;
  string url = 2;
  string display = 3;
  string address = 4;
  google.protobuf.Int64Value vrf_id = 5;
  string status = 6;
  google.protobuf.StringValue role = 7;
  string dns_name = 8;
  string description = 9;
  string comments = 10;
  google.protobuf.StringValue assigned_object_type = 11;
  google.protobuf.Int64Value assigned_object_id = 12;
  netbox.types.v1.ObjectReference assigned_object = 13;
  google.protobuf.Timestamp created = 14;
  google.protobuf.Timestamp last_updated = 15;
  uint32 family = 16;
}

message IPAddressInput {
  optional string address = 1;
  google.protobuf.Int64Value vrf = 2;
  optional string status = 3;
  google.protobuf.StringValue role = 4;
  optional string dns_name = 5;
  optional string description = 6;
  optional string comments = 7;
  google.protobuf.StringValue assigned_object_type = 8;
  google.protobuf.Int64Value assigned_object_id = 9;
}
