// Code generated by https://github.com/go-dev-frame/sponge

package routers

import (
	"context"

	"github.com/gin-gonic/gin"
	"google.golang.org/grpc/metadata"

	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
	"github.com/go-dev-frame/sponge/pkg/logger"

	netbox_goV1 "netbox-go/api/netbox_go/v1"
	"netbox-go/internal/handler"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		ipamVlantranslationruleMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			ipamVlantranslationruleRouter(r, groupPathMiddlewares, singlePathMiddlewares, handler.NewIpamVlantranslationruleHandler())
		})
}

func ipamVlantranslationruleRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService netbox_goV1.IpamVlantranslationruleLogicer) {
	ctxFn := func(c *gin.Context) context.Context {
		md := metadata.New(map[string]string{
			middleware.ContextRequestIDKey: middleware.GCtxRequestID(c), // request_id
			//middleware.HeaderAuthorizationKey: c.GetHeader(middleware.HeaderAuthorizationKey),  // authorization
		})
		return metadata.NewIncomingContext(c.Request.Context(), md)
	}
	netbox_goV1.RegisterIpamVlantranslationruleRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		netbox_goV1.WithIpamVlantranslationruleLogger(logger.Get()),
		netbox_goV1.WithIpamVlantranslationruleRPCResponse(),
		netbox_goV1.WithIpamVlantranslationruleWrapCtx(ctxFn),
		netbox_goV1.WithIpamVlantranslationruleErrorToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.InternalServerError and ecode.ServiceUnavailable
		// example:
		// 	ecode.Forbidden, ecode.LimitExceed,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func ipamVlantranslationruleMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/ipamVlantranslationrule/:id  will take effect
	// c.setGroupPath("/api/v1/ipamVlantranslationrule", middleware.Auth())

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/api/v1/ipamVlantranslationrule", middleware.Auth())    // Create a new ipamVlantranslationrule
	//c.setSinglePath("DELETE", "/api/v1/ipamVlantranslationrule/:id", middleware.Auth())    // DeleteByID Delete a ipamVlantranslationrule by id
	//c.setSinglePath("PUT", "/api/v1/ipamVlantranslationrule/:id", middleware.Auth())    // UpdateByID Update a ipamVlantranslationrule by id
	//c.setSinglePath("GET", "/api/v1/ipamVlantranslationrule/:id", middleware.Auth())    // GetByID Get a ipamVlantranslationrule by id
	//c.setSinglePath("POST", "/api/v1/ipamVlantranslationrule/list", middleware.Auth())    // List Get a paginated list of ipamVlantranslationrule by custom conditions
	//c.setSinglePath("POST", "/api/v1/ipamVlantranslationrule/delete/ids", middleware.Auth())    // DeleteByIDs Batch delete ipamVlantranslationrule by ids
	//c.setSinglePath("POST", "/api/v1/ipamVlantranslationrule/condition", middleware.Auth())    // GetByCondition Get a ipamVlantranslationrule by custom condition
	//c.setSinglePath("POST", "/api/v1/ipamVlantranslationrule/list/ids", middleware.Auth())    // ListByIDs Batch get ipamVlantranslationrule by ids
	//c.setSinglePath("GET", "/api/v1/ipamVlantranslationrule/list", middleware.Auth())    // ListByLastID Get a paginated list of ipamVlantranslationrule by last id
	//c.setSinglePath("POST", "/api/ipam/vlantranslationrules", middleware.Auth())    // Create a new ipamVlantranslationrule
	//c.setSinglePath("DELETE", "/api/ipam/vlantranslationrules/:id", middleware.Auth())    // DeleteByID Delete a ipamVlantranslationrule by id
	//c.setSinglePath("PUT", "/api/ipam/vlantranslationrules/:id", middleware.Auth())    // UpdateByID Update a ipamVlantranslationrule by id
	//c.setSinglePath("GET", "/api/ipam/vlantranslationrules/:id", middleware.Auth())    // GetByID Get a ipamVlantranslationrule by id
	//c.setSinglePath("POST", "/api/ipam/vlantranslationrules/list", middleware.Auth())    // List Get a paginated list of ipamVlantranslationrule by custom conditions
	//c.setSinglePath("POST", "/api/ipam/vlantranslationrules/delete/ids", middleware.Auth())    // DeleteByIDs Batch delete ipamVlantranslationrule by ids
	//c.setSinglePath("POST", "/api/ipam/vlantranslationrules/condition", middleware.Auth())    // GetByCondition Get a ipamVlantranslationrule by custom condition
	//c.setSinglePath("POST", "/api/ipam/vlantranslationrules/list/ids", middleware.Auth())    // ListByIDs Batch get ipamVlantranslationrule by ids
	//c.setSinglePath("GET", "/api/ipam/vlantranslationrules", middleware.Auth())    // ListByLastID Get a paginated list of ipamVlantranslationrule by last id
}
