syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service circuitsCircuittermination {
  // Create a new circuitsCircuittermination
  rpc Create(CreateCircuitsCircuitterminationRequest) returns (CreateCircuitsCircuitterminationReply) {
    option (google.api.http) = {
      post: "/api/circuits/circuitterminations"
      body: "*"
    };
  }

  // Delete a circuitsCircuittermination by id
  rpc DeleteByID(DeleteCircuitsCircuitterminationByIDRequest) returns (DeleteCircuitsCircuitterminationByIDReply) {
    option (google.api.http) = {
      delete: "/api/circuits/circuitterminations/{id}"
    };
  }

  // Update a circuitsCircuittermination by id
  rpc UpdateByID(UpdateCircuitsCircuitterminationByIDRequest) returns (UpdateCircuitsCircuitterminationByIDReply) {
    option (google.api.http) = {
      put: "/api/circuits/circuitterminations/{id}"
      body: "*"
    };
  }

  // Get a circuitsCircuittermination by id
  rpc GetByID(GetCircuitsCircuitterminationByIDRequest) returns (GetCircuitsCircuitterminationByIDReply) {
    option (google.api.http) = {
      get: "/api/circuits/circuitterminations/{id}"
    };
  }

  // Get a paginated list of circuitsCircuittermination by custom conditions
  rpc List(ListCircuitsCircuitterminationRequest) returns (ListCircuitsCircuitterminationReply) {
    option (google.api.http) = {
      post: "/api/circuits/circuitterminations/list"
      body: "*"
    };
  }

  // Batch delete circuitsCircuittermination by ids
  rpc DeleteByIDs(DeleteCircuitsCircuitterminationByIDsRequest) returns (DeleteCircuitsCircuitterminationByIDsReply) {
    option (google.api.http) = {
      post: "/api/circuits/circuitterminations/delete/ids"
      body: "*"
    };
  }

  // Get a circuitsCircuittermination by custom condition
  rpc GetByCondition(GetCircuitsCircuitterminationByConditionRequest) returns (GetCircuitsCircuitterminationByConditionReply) {
    option (google.api.http) = {
      post: "/api/circuits/circuitterminations/condition"
      body: "*"
    };
  }

  // Batch get circuitsCircuittermination by ids
  rpc ListByIDs(ListCircuitsCircuitterminationByIDsRequest) returns (ListCircuitsCircuitterminationByIDsReply) {
    option (google.api.http) = {
      post: "/api/circuits/circuitterminations/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of circuitsCircuittermination by last id
  rpc ListByLastID(ListCircuitsCircuitterminationByLastIDRequest) returns (ListCircuitsCircuitterminationByLastIDReply) {
    option (google.api.http) = {
      get: "/api/circuits/circuitterminations"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/circuitsCircuittermination/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getCircuitsCircuittermination?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateCircuitsCircuitterminationRequest {
	string created = 1; 
	string lastUpdated = 2; 
	bool markConnected = 3; 
	string termSide = 4; 
	int32 portSpeed = 5; 
	int32 upstreamSpeed = 6; 
	string xconnectID = 7; 
	string ppInfo = 8; 
	string description = 9; 
	int64 cableID = 10; 
	int64 circuitID = 11; 
	int64 xProviderNetworkID = 12; 
	string customFieldData = 13; 
	string cableEnd = 14; 
	int64 terminationID = 15; 
	int32 terminationTypeID = 16; 
	int64 xLocationID = 17; 
	int64 xRegionID = 18; 
	int64 xSiteID = 19; 
	int64 xSiteGroupID = 20; 
}

message CreateCircuitsCircuitterminationReply {
  uint64 id = 1;
}

message DeleteCircuitsCircuitterminationByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteCircuitsCircuitterminationByIDReply {

}

message UpdateCircuitsCircuitterminationByIDRequest {
	string created = 1; 
	string lastUpdated = 2; 
	uint64 id = 3 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	bool markConnected = 4; 
	string termSide = 5; 
	int32 portSpeed = 6; 
	int32 upstreamSpeed = 7; 
	string xconnectID = 8; 
	string ppInfo = 9; 
	string description = 10; 
	int64 cableID = 11; 
	int64 circuitID = 12; 
	int64 xProviderNetworkID = 13; 
	string customFieldData = 14; 
	string cableEnd = 15; 
	int64 terminationID = 16; 
	int32 terminationTypeID = 17; 
	int64 xLocationID = 18; 
	int64 xRegionID = 19; 
	int64 xSiteID = 20; 
	int64 xSiteGroupID = 21; 
}

message UpdateCircuitsCircuitterminationByIDReply {

}

message CircuitsCircuittermination {
	string created = 1; 
	string lastUpdated = 2; 
	uint64 id = 3; 
	bool markConnected = 4; 
	string termSide = 5; 
	int32 portSpeed = 6; 
	int32 upstreamSpeed = 7; 
	string xconnectID = 8; 
	string ppInfo = 9; 
	string description = 10; 
	int64 cableID = 11; 
	int64 circuitID = 12; 
	int64 xProviderNetworkID = 13; 
	string customFieldData = 14; 
	string cableEnd = 15; 
	int64 terminationID = 16; 
	int32 terminationTypeID = 17; 
	int64 xLocationID = 18; 
	int64 xRegionID = 19; 
	int64 xSiteID = 20; 
	int64 xSiteGroupID = 21; 
}

message GetCircuitsCircuitterminationByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetCircuitsCircuitterminationByIDReply {
  CircuitsCircuittermination circuitsCircuittermination = 1;
}

message ListCircuitsCircuitterminationRequest {
  api.types.Params params = 1;
}

message ListCircuitsCircuitterminationReply {
  int64 total = 1;
  repeated CircuitsCircuittermination circuitsCircuitterminations = 2;
}

message DeleteCircuitsCircuitterminationByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteCircuitsCircuitterminationByIDsReply {

}

message GetCircuitsCircuitterminationByConditionRequest {
  types.Conditions conditions = 1;
}

message GetCircuitsCircuitterminationByConditionReply {
  CircuitsCircuittermination circuitsCircuittermination = 1;
}

message ListCircuitsCircuitterminationByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListCircuitsCircuitterminationByIDsReply {
  repeated CircuitsCircuittermination circuitsCircuitterminations = 1;
}

message ListCircuitsCircuitterminationByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListCircuitsCircuitterminationByLastIDReply {
  repeated CircuitsCircuittermination circuitsCircuitterminations = 1;
}


