syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service coreObjectchange {
  // Create a new coreObjectchange
  rpc Create(CreateCoreObjectchangeRequest) returns (CreateCoreObjectchangeReply) {
    option (google.api.http) = {
      post: "/api/core/objectchanges"
      body: "*"
    };
  }

  // Delete a coreObjectchange by id
  rpc DeleteByID(DeleteCoreObjectchangeByIDRequest) returns (DeleteCoreObjectchangeByIDReply) {
    option (google.api.http) = {
      delete: "/api/core/objectchanges/{id}"
    };
  }

  // Update a coreObjectchange by id
  rpc UpdateByID(UpdateCoreObjectchangeByIDRequest) returns (UpdateCoreObjectchangeByIDReply) {
    option (google.api.http) = {
      put: "/api/core/objectchanges/{id}"
      body: "*"
    };
  }

  // Get a coreObjectchange by id
  rpc GetByID(GetCoreObjectchangeByIDRequest) returns (GetCoreObjectchangeByIDReply) {
    option (google.api.http) = {
      get: "/api/core/objectchanges/{id}"
    };
  }

  // Get a paginated list of coreObjectchange by custom conditions
  rpc List(ListCoreObjectchangeRequest) returns (ListCoreObjectchangeReply) {
    option (google.api.http) = {
      post: "/api/core/objectchanges/list"
      body: "*"
    };
  }

  // Batch delete coreObjectchange by ids
  rpc DeleteByIDs(DeleteCoreObjectchangeByIDsRequest) returns (DeleteCoreObjectchangeByIDsReply) {
    option (google.api.http) = {
      post: "/api/core/objectchanges/delete/ids"
      body: "*"
    };
  }

  // Get a coreObjectchange by custom condition
  rpc GetByCondition(GetCoreObjectchangeByConditionRequest) returns (GetCoreObjectchangeByConditionReply) {
    option (google.api.http) = {
      post: "/api/core/objectchanges/condition"
      body: "*"
    };
  }

  // Batch get coreObjectchange by ids
  rpc ListByIDs(ListCoreObjectchangeByIDsRequest) returns (ListCoreObjectchangeByIDsReply) {
    option (google.api.http) = {
      post: "/api/core/objectchanges/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of coreObjectchange by last id
  rpc ListByLastID(ListCoreObjectchangeByLastIDRequest) returns (ListCoreObjectchangeByLastIDReply) {
    option (google.api.http) = {
      get: "/api/core/objectchanges"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/coreObjectchange/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getCoreObjectchange?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateCoreObjectchangeRequest {
	string time = 1; 
	string userName = 2; 
	string requestID = 3; 
	string action = 4; 
	int64 changedObjectID = 5; 
	int64 relatedObjectID = 6; 
	string objectRepr = 7; 
	string prechangeData = 8; 
	string postchangeData = 9; 
	int32 changedObjectTypeID = 10; 
	int32 relatedObjectTypeID = 11; 
	int64 userID = 12; 
	string message = 13; 
}

message CreateCoreObjectchangeReply {
  uint64 id = 1;
}

message DeleteCoreObjectchangeByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteCoreObjectchangeByIDReply {

}

message UpdateCoreObjectchangeByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string time = 2; 
	string userName = 3; 
	string requestID = 4; 
	string action = 5; 
	int64 changedObjectID = 6; 
	int64 relatedObjectID = 7; 
	string objectRepr = 8; 
	string prechangeData = 9; 
	string postchangeData = 10; 
	int32 changedObjectTypeID = 11; 
	int32 relatedObjectTypeID = 12; 
	int64 userID = 13; 
	string message = 14; 
}

message UpdateCoreObjectchangeByIDReply {

}

message CoreObjectchange {
	uint64 id = 1; 
	string time = 2; 
	string userName = 3; 
	string requestID = 4; 
	string action = 5; 
	int64 changedObjectID = 6; 
	int64 relatedObjectID = 7; 
	string objectRepr = 8; 
	string prechangeData = 9; 
	string postchangeData = 10; 
	int32 changedObjectTypeID = 11; 
	int32 relatedObjectTypeID = 12; 
	int64 userID = 13; 
	string message = 14; 
}

message GetCoreObjectchangeByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetCoreObjectchangeByIDReply {
  CoreObjectchange coreObjectchange = 1;
}

message ListCoreObjectchangeRequest {
  api.types.Params params = 1;
}

message ListCoreObjectchangeReply {
  int64 total = 1;
  repeated CoreObjectchange coreObjectchanges = 2;
}

message DeleteCoreObjectchangeByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteCoreObjectchangeByIDsReply {

}

message GetCoreObjectchangeByConditionRequest {
  types.Conditions conditions = 1;
}

message GetCoreObjectchangeByConditionReply {
  CoreObjectchange coreObjectchange = 1;
}

message ListCoreObjectchangeByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListCoreObjectchangeByIDsReply {
  repeated CoreObjectchange coreObjectchanges = 1;
}

message ListCoreObjectchangeByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListCoreObjectchangeByLastIDReply {
  repeated CoreObjectchange coreObjectchanges = 1;
}


