syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service dcimRegion {
  // Create a new dcimRegion
  rpc Create(CreateDcimRegionRequest) returns (CreateDcimRegionReply) {
    option (google.api.http) = {
      post: "/api/dcim/regions"
      body: "*"
    };
  }

  // Delete a dcimRegion by id
  rpc DeleteByID(DeleteDcimRegionByIDRequest) returns (DeleteDcimRegionByIDReply) {
    option (google.api.http) = {
      delete: "/api/dcim/regions/{id}"
    };
  }

  // Update a dcimRegion by id
  rpc UpdateByID(UpdateDcimRegionByIDRequest) returns (UpdateDcimRegionByIDReply) {
    option (google.api.http) = {
      put: "/api/dcim/regions/{id}"
      body: "*"
    };
  }

  // Get a dcimRegion by id
  rpc GetByID(GetDcimRegionByIDRequest) returns (GetDcimRegionByIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/regions/{id}"
    };
  }

  // Get a paginated list of dcimRegion by custom conditions
  rpc List(ListDcimRegionRequest) returns (ListDcimRegionReply) {
    option (google.api.http) = {
      post: "/api/dcim/regions/list"
      body: "*"
    };
  }

  // Batch delete dcimRegion by ids
  rpc DeleteByIDs(DeleteDcimRegionByIDsRequest) returns (DeleteDcimRegionByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/regions/delete/ids"
      body: "*"
    };
  }

  // Get a dcimRegion by custom condition
  rpc GetByCondition(GetDcimRegionByConditionRequest) returns (GetDcimRegionByConditionReply) {
    option (google.api.http) = {
      post: "/api/dcim/regions/condition"
      body: "*"
    };
  }

  // Batch get dcimRegion by ids
  rpc ListByIDs(ListDcimRegionByIDsRequest) returns (ListDcimRegionByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/regions/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of dcimRegion by last id
  rpc ListByLastID(ListDcimRegionByLastIDRequest) returns (ListDcimRegionByLastIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/regions"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/dcimRegion/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getDcimRegion?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateDcimRegionRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	string name = 4; 
	string slug = 5; 
	string description = 6; 
	int32 lft = 7; 
	int32 rght = 8; 
	int32 treeID = 9; 
	int32 level = 10; 
	int64 parentID = 11; 
	string comments = 12; 
}

message CreateDcimRegionReply {
  uint64 id = 1;
}

message DeleteDcimRegionByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteDcimRegionByIDReply {

}

message UpdateDcimRegionByIDRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string name = 5; 
	string slug = 6; 
	string description = 7; 
	int32 lft = 8; 
	int32 rght = 9; 
	int32 treeID = 10; 
	int32 level = 11; 
	int64 parentID = 12; 
	string comments = 13; 
}

message UpdateDcimRegionByIDReply {

}

message DcimRegion {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4; 
	string name = 5; 
	string slug = 6; 
	string description = 7; 
	int32 lft = 8; 
	int32 rght = 9; 
	int32 treeID = 10; 
	int32 level = 11; 
	int64 parentID = 12; 
	string comments = 13; 
}

message GetDcimRegionByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetDcimRegionByIDReply {
  DcimRegion dcimRegion = 1;
}

message ListDcimRegionRequest {
  api.types.Params params = 1;
}

message ListDcimRegionReply {
  int64 total = 1;
  repeated DcimRegion dcimRegions = 2;
}

message DeleteDcimRegionByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteDcimRegionByIDsReply {

}

message GetDcimRegionByConditionRequest {
  types.Conditions conditions = 1;
}

message GetDcimRegionByConditionReply {
  DcimRegion dcimRegion = 1;
}

message ListDcimRegionByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListDcimRegionByIDsReply {
  repeated DcimRegion dcimRegions = 1;
}

message ListDcimRegionByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListDcimRegionByLastIDReply {
  repeated DcimRegion dcimRegions = 1;
}


