// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/netbox_go/v1/dcimRegion.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "netbox-go/api/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDcimRegionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Created         string                 `protobuf:"bytes,1,opt,name=created,proto3" json:"created"`
	LastUpdated     string                 `protobuf:"bytes,2,opt,name=lastUpdated,proto3" json:"lastUpdated"`
	CustomFieldData string                 `protobuf:"bytes,3,opt,name=customFieldData,proto3" json:"customFieldData"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	Slug            string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	Lft             int32                  `protobuf:"varint,7,opt,name=lft,proto3" json:"lft"`
	Rght            int32                  `protobuf:"varint,8,opt,name=rght,proto3" json:"rght"`
	TreeID          int32                  `protobuf:"varint,9,opt,name=treeID,proto3" json:"treeID"`
	Level           int32                  `protobuf:"varint,10,opt,name=level,proto3" json:"level"`
	ParentID        int64                  `protobuf:"varint,11,opt,name=parentID,proto3" json:"parentID"`
	Comments        string                 `protobuf:"bytes,12,opt,name=comments,proto3" json:"comments"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateDcimRegionRequest) Reset() {
	*x = CreateDcimRegionRequest{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDcimRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDcimRegionRequest) ProtoMessage() {}

func (x *CreateDcimRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDcimRegionRequest.ProtoReflect.Descriptor instead.
func (*CreateDcimRegionRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDcimRegionRequest) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *CreateDcimRegionRequest) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *CreateDcimRegionRequest) GetCustomFieldData() string {
	if x != nil {
		return x.CustomFieldData
	}
	return ""
}

func (x *CreateDcimRegionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDcimRegionRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateDcimRegionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDcimRegionRequest) GetLft() int32 {
	if x != nil {
		return x.Lft
	}
	return 0
}

func (x *CreateDcimRegionRequest) GetRght() int32 {
	if x != nil {
		return x.Rght
	}
	return 0
}

func (x *CreateDcimRegionRequest) GetTreeID() int32 {
	if x != nil {
		return x.TreeID
	}
	return 0
}

func (x *CreateDcimRegionRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateDcimRegionRequest) GetParentID() int64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

func (x *CreateDcimRegionRequest) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

type CreateDcimRegionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDcimRegionReply) Reset() {
	*x = CreateDcimRegionReply{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDcimRegionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDcimRegionReply) ProtoMessage() {}

func (x *CreateDcimRegionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDcimRegionReply.ProtoReflect.Descriptor instead.
func (*CreateDcimRegionReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDcimRegionReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDcimRegionByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDcimRegionByIDRequest) Reset() {
	*x = DeleteDcimRegionByIDRequest{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDcimRegionByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDcimRegionByIDRequest) ProtoMessage() {}

func (x *DeleteDcimRegionByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDcimRegionByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteDcimRegionByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteDcimRegionByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDcimRegionByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDcimRegionByIDReply) Reset() {
	*x = DeleteDcimRegionByIDReply{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDcimRegionByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDcimRegionByIDReply) ProtoMessage() {}

func (x *DeleteDcimRegionByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDcimRegionByIDReply.ProtoReflect.Descriptor instead.
func (*DeleteDcimRegionByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{3}
}

type UpdateDcimRegionByIDRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Created         string                 `protobuf:"bytes,1,opt,name=created,proto3" json:"created"`
	LastUpdated     string                 `protobuf:"bytes,2,opt,name=lastUpdated,proto3" json:"lastUpdated"`
	CustomFieldData string                 `protobuf:"bytes,3,opt,name=customFieldData,proto3" json:"customFieldData"`
	Id              uint64                 `protobuf:"varint,4,opt,name=id,proto3" json:"id" uri:"id"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Slug            string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description"`
	Lft             int32                  `protobuf:"varint,8,opt,name=lft,proto3" json:"lft"`
	Rght            int32                  `protobuf:"varint,9,opt,name=rght,proto3" json:"rght"`
	TreeID          int32                  `protobuf:"varint,10,opt,name=treeID,proto3" json:"treeID"`
	Level           int32                  `protobuf:"varint,11,opt,name=level,proto3" json:"level"`
	ParentID        int64                  `protobuf:"varint,12,opt,name=parentID,proto3" json:"parentID"`
	Comments        string                 `protobuf:"bytes,13,opt,name=comments,proto3" json:"comments"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateDcimRegionByIDRequest) Reset() {
	*x = UpdateDcimRegionByIDRequest{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDcimRegionByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDcimRegionByIDRequest) ProtoMessage() {}

func (x *UpdateDcimRegionByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDcimRegionByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateDcimRegionByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDcimRegionByIDRequest) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *UpdateDcimRegionByIDRequest) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *UpdateDcimRegionByIDRequest) GetCustomFieldData() string {
	if x != nil {
		return x.CustomFieldData
	}
	return ""
}

func (x *UpdateDcimRegionByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDcimRegionByIDRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDcimRegionByIDRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateDcimRegionByIDRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateDcimRegionByIDRequest) GetLft() int32 {
	if x != nil {
		return x.Lft
	}
	return 0
}

func (x *UpdateDcimRegionByIDRequest) GetRght() int32 {
	if x != nil {
		return x.Rght
	}
	return 0
}

func (x *UpdateDcimRegionByIDRequest) GetTreeID() int32 {
	if x != nil {
		return x.TreeID
	}
	return 0
}

func (x *UpdateDcimRegionByIDRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpdateDcimRegionByIDRequest) GetParentID() int64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

func (x *UpdateDcimRegionByIDRequest) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

type UpdateDcimRegionByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDcimRegionByIDReply) Reset() {
	*x = UpdateDcimRegionByIDReply{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDcimRegionByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDcimRegionByIDReply) ProtoMessage() {}

func (x *UpdateDcimRegionByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDcimRegionByIDReply.ProtoReflect.Descriptor instead.
func (*UpdateDcimRegionByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{5}
}

type DcimRegion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Created         string                 `protobuf:"bytes,1,opt,name=created,proto3" json:"created"`
	LastUpdated     string                 `protobuf:"bytes,2,opt,name=lastUpdated,proto3" json:"lastUpdated"`
	CustomFieldData string                 `protobuf:"bytes,3,opt,name=customFieldData,proto3" json:"customFieldData"`
	Id              uint64                 `protobuf:"varint,4,opt,name=id,proto3" json:"id"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Slug            string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description"`
	Lft             int32                  `protobuf:"varint,8,opt,name=lft,proto3" json:"lft"`
	Rght            int32                  `protobuf:"varint,9,opt,name=rght,proto3" json:"rght"`
	TreeID          int32                  `protobuf:"varint,10,opt,name=treeID,proto3" json:"treeID"`
	Level           int32                  `protobuf:"varint,11,opt,name=level,proto3" json:"level"`
	ParentID        int64                  `protobuf:"varint,12,opt,name=parentID,proto3" json:"parentID"`
	Comments        string                 `protobuf:"bytes,13,opt,name=comments,proto3" json:"comments"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DcimRegion) Reset() {
	*x = DcimRegion{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DcimRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DcimRegion) ProtoMessage() {}

func (x *DcimRegion) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DcimRegion.ProtoReflect.Descriptor instead.
func (*DcimRegion) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{6}
}

func (x *DcimRegion) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *DcimRegion) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *DcimRegion) GetCustomFieldData() string {
	if x != nil {
		return x.CustomFieldData
	}
	return ""
}

func (x *DcimRegion) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DcimRegion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DcimRegion) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *DcimRegion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DcimRegion) GetLft() int32 {
	if x != nil {
		return x.Lft
	}
	return 0
}

func (x *DcimRegion) GetRght() int32 {
	if x != nil {
		return x.Rght
	}
	return 0
}

func (x *DcimRegion) GetTreeID() int32 {
	if x != nil {
		return x.TreeID
	}
	return 0
}

func (x *DcimRegion) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *DcimRegion) GetParentID() int64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

func (x *DcimRegion) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

type GetDcimRegionByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDcimRegionByIDRequest) Reset() {
	*x = GetDcimRegionByIDRequest{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDcimRegionByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDcimRegionByIDRequest) ProtoMessage() {}

func (x *GetDcimRegionByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDcimRegionByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDcimRegionByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{7}
}

func (x *GetDcimRegionByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDcimRegionByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DcimRegion    *DcimRegion            `protobuf:"bytes,1,opt,name=dcimRegion,proto3" json:"dcimRegion"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDcimRegionByIDReply) Reset() {
	*x = GetDcimRegionByIDReply{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDcimRegionByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDcimRegionByIDReply) ProtoMessage() {}

func (x *GetDcimRegionByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDcimRegionByIDReply.ProtoReflect.Descriptor instead.
func (*GetDcimRegionByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{8}
}

func (x *GetDcimRegionByIDReply) GetDcimRegion() *DcimRegion {
	if x != nil {
		return x.DcimRegion
	}
	return nil
}

type ListDcimRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *types.Params          `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDcimRegionRequest) Reset() {
	*x = ListDcimRegionRequest{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDcimRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDcimRegionRequest) ProtoMessage() {}

func (x *ListDcimRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDcimRegionRequest.ProtoReflect.Descriptor instead.
func (*ListDcimRegionRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{9}
}

func (x *ListDcimRegionRequest) GetParams() *types.Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type ListDcimRegionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	DcimRegions   []*DcimRegion          `protobuf:"bytes,2,rep,name=dcimRegions,proto3" json:"dcimRegions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDcimRegionReply) Reset() {
	*x = ListDcimRegionReply{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDcimRegionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDcimRegionReply) ProtoMessage() {}

func (x *ListDcimRegionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDcimRegionReply.ProtoReflect.Descriptor instead.
func (*ListDcimRegionReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{10}
}

func (x *ListDcimRegionReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDcimRegionReply) GetDcimRegions() []*DcimRegion {
	if x != nil {
		return x.DcimRegions
	}
	return nil
}

type DeleteDcimRegionByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDcimRegionByIDsRequest) Reset() {
	*x = DeleteDcimRegionByIDsRequest{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDcimRegionByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDcimRegionByIDsRequest) ProtoMessage() {}

func (x *DeleteDcimRegionByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDcimRegionByIDsRequest.ProtoReflect.Descriptor instead.
func (*DeleteDcimRegionByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDcimRegionByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteDcimRegionByIDsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDcimRegionByIDsReply) Reset() {
	*x = DeleteDcimRegionByIDsReply{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDcimRegionByIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDcimRegionByIDsReply) ProtoMessage() {}

func (x *DeleteDcimRegionByIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDcimRegionByIDsReply.ProtoReflect.Descriptor instead.
func (*DeleteDcimRegionByIDsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{12}
}

type GetDcimRegionByConditionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    *types.Conditions      `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDcimRegionByConditionRequest) Reset() {
	*x = GetDcimRegionByConditionRequest{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDcimRegionByConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDcimRegionByConditionRequest) ProtoMessage() {}

func (x *GetDcimRegionByConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDcimRegionByConditionRequest.ProtoReflect.Descriptor instead.
func (*GetDcimRegionByConditionRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{13}
}

func (x *GetDcimRegionByConditionRequest) GetConditions() *types.Conditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type GetDcimRegionByConditionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DcimRegion    *DcimRegion            `protobuf:"bytes,1,opt,name=dcimRegion,proto3" json:"dcimRegion"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDcimRegionByConditionReply) Reset() {
	*x = GetDcimRegionByConditionReply{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDcimRegionByConditionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDcimRegionByConditionReply) ProtoMessage() {}

func (x *GetDcimRegionByConditionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDcimRegionByConditionReply.ProtoReflect.Descriptor instead.
func (*GetDcimRegionByConditionReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{14}
}

func (x *GetDcimRegionByConditionReply) GetDcimRegion() *DcimRegion {
	if x != nil {
		return x.DcimRegion
	}
	return nil
}

type ListDcimRegionByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDcimRegionByIDsRequest) Reset() {
	*x = ListDcimRegionByIDsRequest{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDcimRegionByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDcimRegionByIDsRequest) ProtoMessage() {}

func (x *ListDcimRegionByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDcimRegionByIDsRequest.ProtoReflect.Descriptor instead.
func (*ListDcimRegionByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{15}
}

func (x *ListDcimRegionByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListDcimRegionByIDsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DcimRegions   []*DcimRegion          `protobuf:"bytes,1,rep,name=dcimRegions,proto3" json:"dcimRegions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDcimRegionByIDsReply) Reset() {
	*x = ListDcimRegionByIDsReply{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDcimRegionByIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDcimRegionByIDsReply) ProtoMessage() {}

func (x *ListDcimRegionByIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDcimRegionByIDsReply.ProtoReflect.Descriptor instead.
func (*ListDcimRegionByIDsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{16}
}

func (x *ListDcimRegionByIDsReply) GetDcimRegions() []*DcimRegion {
	if x != nil {
		return x.DcimRegions
	}
	return nil
}

type ListDcimRegionByLastIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastID        uint64                 `protobuf:"varint,1,opt,name=lastID,proto3" json:"lastID" form:"lastID"` // last id
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit" form:"limit"`    // limit size per page
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort" form:"sort"`        // sort by column name of table, default is -id, the - sign indicates descending order.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDcimRegionByLastIDRequest) Reset() {
	*x = ListDcimRegionByLastIDRequest{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDcimRegionByLastIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDcimRegionByLastIDRequest) ProtoMessage() {}

func (x *ListDcimRegionByLastIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDcimRegionByLastIDRequest.ProtoReflect.Descriptor instead.
func (*ListDcimRegionByLastIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{17}
}

func (x *ListDcimRegionByLastIDRequest) GetLastID() uint64 {
	if x != nil {
		return x.LastID
	}
	return 0
}

func (x *ListDcimRegionByLastIDRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDcimRegionByLastIDRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListDcimRegionByLastIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DcimRegions   []*DcimRegion          `protobuf:"bytes,1,rep,name=dcimRegions,proto3" json:"dcimRegions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDcimRegionByLastIDReply) Reset() {
	*x = ListDcimRegionByLastIDReply{}
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDcimRegionByLastIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDcimRegionByLastIDReply) ProtoMessage() {}

func (x *ListDcimRegionByLastIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_dcimRegion_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDcimRegionByLastIDReply.ProtoReflect.Descriptor instead.
func (*ListDcimRegionByLastIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP(), []int{18}
}

func (x *ListDcimRegionByLastIDReply) GetDcimRegions() []*DcimRegion {
	if x != nil {
		return x.DcimRegions
	}
	return nil
}

var File_api_netbox_go_v1_dcimRegion_proto protoreflect.FileDescriptor

const file_api_netbox_go_v1_dcimRegion_proto_rawDesc = "" +
	"\n" +
	"!api/netbox_go/v1/dcimRegion.proto\x12\x10api.netbox_go.v1\x1a\x15api/types/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x13tagger/tagger.proto\x1a\x17validate/validate.proto\"\xd5\x02\n" +
	"\x17CreateDcimRegionRequest\x12\x18\n" +
	"\acreated\x18\x01 \x01(\tR\acreated\x12 \n" +
	"\vlastUpdated\x18\x02 \x01(\tR\vlastUpdated\x12(\n" +
	"\x0fcustomFieldData\x18\x03 \x01(\tR\x0fcustomFieldData\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x10\n" +
	"\x03lft\x18\a \x01(\x05R\x03lft\x12\x12\n" +
	"\x04rght\x18\b \x01(\x05R\x04rght\x12\x16\n" +
	"\x06treeID\x18\t \x01(\x05R\x06treeID\x12\x14\n" +
	"\x05level\x18\n" +
	" \x01(\x05R\x05level\x12\x1a\n" +
	"\bparentID\x18\v \x01(\x03R\bparentID\x12\x1a\n" +
	"\bcomments\x18\f \x01(\tR\bcomments\"'\n" +
	"\x15CreateDcimRegionReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"C\n" +
	"\x1bDeleteDcimRegionByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"\x1b\n" +
	"\x19DeleteDcimRegionByIDReply\"\xff\x02\n" +
	"\x1bUpdateDcimRegionByIDRequest\x12\x18\n" +
	"\acreated\x18\x01 \x01(\tR\acreated\x12 \n" +
	"\vlastUpdated\x18\x02 \x01(\tR\vlastUpdated\x12(\n" +
	"\x0fcustomFieldData\x18\x03 \x01(\tR\x0fcustomFieldData\x12$\n" +
	"\x02id\x18\x04 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x10\n" +
	"\x03lft\x18\b \x01(\x05R\x03lft\x12\x12\n" +
	"\x04rght\x18\t \x01(\x05R\x04rght\x12\x16\n" +
	"\x06treeID\x18\n" +
	" \x01(\x05R\x06treeID\x12\x14\n" +
	"\x05level\x18\v \x01(\x05R\x05level\x12\x1a\n" +
	"\bparentID\x18\f \x01(\x03R\bparentID\x12\x1a\n" +
	"\bcomments\x18\r \x01(\tR\bcomments\"\x1b\n" +
	"\x19UpdateDcimRegionByIDReply\"\xd8\x02\n" +
	"\n" +
	"DcimRegion\x12\x18\n" +
	"\acreated\x18\x01 \x01(\tR\acreated\x12 \n" +
	"\vlastUpdated\x18\x02 \x01(\tR\vlastUpdated\x12(\n" +
	"\x0fcustomFieldData\x18\x03 \x01(\tR\x0fcustomFieldData\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x10\n" +
	"\x03lft\x18\b \x01(\x05R\x03lft\x12\x12\n" +
	"\x04rght\x18\t \x01(\x05R\x04rght\x12\x16\n" +
	"\x06treeID\x18\n" +
	" \x01(\x05R\x06treeID\x12\x14\n" +
	"\x05level\x18\v \x01(\x05R\x05level\x12\x1a\n" +
	"\bparentID\x18\f \x01(\x03R\bparentID\x12\x1a\n" +
	"\bcomments\x18\r \x01(\tR\bcomments\"@\n" +
	"\x18GetDcimRegionByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"V\n" +
	"\x16GetDcimRegionByIDReply\x12<\n" +
	"\n" +
	"dcimRegion\x18\x01 \x01(\v2\x1c.api.netbox_go.v1.DcimRegionR\n" +
	"dcimRegion\"B\n" +
	"\x15ListDcimRegionRequest\x12)\n" +
	"\x06params\x18\x01 \x01(\v2\x11.api.types.ParamsR\x06params\"k\n" +
	"\x13ListDcimRegionReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12>\n" +
	"\vdcimRegions\x18\x02 \x03(\v2\x1c.api.netbox_go.v1.DcimRegionR\vdcimRegions\":\n" +
	"\x1cDeleteDcimRegionByIDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"\x1c\n" +
	"\x1aDeleteDcimRegionByIDsReply\"X\n" +
	"\x1fGetDcimRegionByConditionRequest\x125\n" +
	"\n" +
	"conditions\x18\x01 \x01(\v2\x15.api.types.ConditionsR\n" +
	"conditions\"]\n" +
	"\x1dGetDcimRegionByConditionReply\x12<\n" +
	"\n" +
	"dcimRegion\x18\x01 \x01(\v2\x1c.api.netbox_go.v1.DcimRegionR\n" +
	"dcimRegion\"8\n" +
	"\x1aListDcimRegionByIDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"Z\n" +
	"\x18ListDcimRegionByIDsReply\x12>\n" +
	"\vdcimRegions\x18\x01 \x03(\v2\x1c.api.netbox_go.v1.DcimRegionR\vdcimRegions\"\xa1\x01\n" +
	"\x1dListDcimRegionByLastIDRequest\x12*\n" +
	"\x06lastID\x18\x01 \x01(\x04B\x12\x9a\x84\x9e\x03\rform:\"lastID\"R\x06lastID\x12.\n" +
	"\x05limit\x18\x02 \x01(\rB\x18\xfaB\x04*\x02 \x00\x9a\x84\x9e\x03\fform:\"limit\"R\x05limit\x12$\n" +
	"\x04sort\x18\x03 \x01(\tB\x10\x9a\x84\x9e\x03\vform:\"sort\"R\x04sort\"]\n" +
	"\x1bListDcimRegionByLastIDReply\x12>\n" +
	"\vdcimRegions\x18\x01 \x03(\v2\x1c.api.netbox_go.v1.DcimRegionR\vdcimRegions2\xee\t\n" +
	"\n" +
	"dcimRegion\x12z\n" +
	"\x06Create\x12).api.netbox_go.v1.CreateDcimRegionRequest\x1a'.api.netbox_go.v1.CreateDcimRegionReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/dcim/regions\x12\x88\x01\n" +
	"\n" +
	"DeleteByID\x12-.api.netbox_go.v1.DeleteDcimRegionByIDRequest\x1a+.api.netbox_go.v1.DeleteDcimRegionByIDReply\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/dcim/regions/{id}\x12\x8b\x01\n" +
	"\n" +
	"UpdateByID\x12-.api.netbox_go.v1.UpdateDcimRegionByIDRequest\x1a+.api.netbox_go.v1.UpdateDcimRegionByIDReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/dcim/regions/{id}\x12\x7f\n" +
	"\aGetByID\x12*.api.netbox_go.v1.GetDcimRegionByIDRequest\x1a(.api.netbox_go.v1.GetDcimRegionByIDReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/dcim/regions/{id}\x12y\n" +
	"\x04List\x12'.api.netbox_go.v1.ListDcimRegionRequest\x1a%.api.netbox_go.v1.ListDcimRegionReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/dcim/regions/list\x12\x94\x01\n" +
	"\vDeleteByIDs\x12..api.netbox_go.v1.DeleteDcimRegionByIDsRequest\x1a,.api.netbox_go.v1.DeleteDcimRegionByIDsReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/dcim/regions/delete/ids\x12\x9c\x01\n" +
	"\x0eGetByCondition\x121.api.netbox_go.v1.GetDcimRegionByConditionRequest\x1a/.api.netbox_go.v1.GetDcimRegionByConditionReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/dcim/regions/condition\x12\x8c\x01\n" +
	"\tListByIDs\x12,.api.netbox_go.v1.ListDcimRegionByIDsRequest\x1a*.api.netbox_go.v1.ListDcimRegionByIDsReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/dcim/regions/list/ids\x12\x89\x01\n" +
	"\fListByLastID\x12/.api.netbox_go.v1.ListDcimRegionByLastIDRequest\x1a-.api.netbox_go.v1.ListDcimRegionByLastIDReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/dcim/regionsB\xc3\x01\x92A\xa0\x01\x12\x1c\n" +
	"\x12netbox_go api docs2\x06v1.0.0\x1a\x0elocalhost:8080*\x02\x01\x022\x10application/json:\x10application/jsonZH\n" +
	"F\n" +
	"\n" +
	"BearerAuth\x128\b\x02\x12#Type Bearer your-jwt-token to Value\x1a\rAuthorization \x02Z\x1dnetbox-go/api/netbox_go/v1;v1b\x06proto3"

var (
	file_api_netbox_go_v1_dcimRegion_proto_rawDescOnce sync.Once
	file_api_netbox_go_v1_dcimRegion_proto_rawDescData []byte
)

func file_api_netbox_go_v1_dcimRegion_proto_rawDescGZIP() []byte {
	file_api_netbox_go_v1_dcimRegion_proto_rawDescOnce.Do(func() {
		file_api_netbox_go_v1_dcimRegion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_netbox_go_v1_dcimRegion_proto_rawDesc), len(file_api_netbox_go_v1_dcimRegion_proto_rawDesc)))
	})
	return file_api_netbox_go_v1_dcimRegion_proto_rawDescData
}

var file_api_netbox_go_v1_dcimRegion_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_netbox_go_v1_dcimRegion_proto_goTypes = []any{
	(*CreateDcimRegionRequest)(nil),         // 0: api.netbox_go.v1.CreateDcimRegionRequest
	(*CreateDcimRegionReply)(nil),           // 1: api.netbox_go.v1.CreateDcimRegionReply
	(*DeleteDcimRegionByIDRequest)(nil),     // 2: api.netbox_go.v1.DeleteDcimRegionByIDRequest
	(*DeleteDcimRegionByIDReply)(nil),       // 3: api.netbox_go.v1.DeleteDcimRegionByIDReply
	(*UpdateDcimRegionByIDRequest)(nil),     // 4: api.netbox_go.v1.UpdateDcimRegionByIDRequest
	(*UpdateDcimRegionByIDReply)(nil),       // 5: api.netbox_go.v1.UpdateDcimRegionByIDReply
	(*DcimRegion)(nil),                      // 6: api.netbox_go.v1.DcimRegion
	(*GetDcimRegionByIDRequest)(nil),        // 7: api.netbox_go.v1.GetDcimRegionByIDRequest
	(*GetDcimRegionByIDReply)(nil),          // 8: api.netbox_go.v1.GetDcimRegionByIDReply
	(*ListDcimRegionRequest)(nil),           // 9: api.netbox_go.v1.ListDcimRegionRequest
	(*ListDcimRegionReply)(nil),             // 10: api.netbox_go.v1.ListDcimRegionReply
	(*DeleteDcimRegionByIDsRequest)(nil),    // 11: api.netbox_go.v1.DeleteDcimRegionByIDsRequest
	(*DeleteDcimRegionByIDsReply)(nil),      // 12: api.netbox_go.v1.DeleteDcimRegionByIDsReply
	(*GetDcimRegionByConditionRequest)(nil), // 13: api.netbox_go.v1.GetDcimRegionByConditionRequest
	(*GetDcimRegionByConditionReply)(nil),   // 14: api.netbox_go.v1.GetDcimRegionByConditionReply
	(*ListDcimRegionByIDsRequest)(nil),      // 15: api.netbox_go.v1.ListDcimRegionByIDsRequest
	(*ListDcimRegionByIDsReply)(nil),        // 16: api.netbox_go.v1.ListDcimRegionByIDsReply
	(*ListDcimRegionByLastIDRequest)(nil),   // 17: api.netbox_go.v1.ListDcimRegionByLastIDRequest
	(*ListDcimRegionByLastIDReply)(nil),     // 18: api.netbox_go.v1.ListDcimRegionByLastIDReply
	(*types.Params)(nil),                    // 19: api.types.Params
	(*types.Conditions)(nil),                // 20: api.types.Conditions
}
var file_api_netbox_go_v1_dcimRegion_proto_depIdxs = []int32{
	6,  // 0: api.netbox_go.v1.GetDcimRegionByIDReply.dcimRegion:type_name -> api.netbox_go.v1.DcimRegion
	19, // 1: api.netbox_go.v1.ListDcimRegionRequest.params:type_name -> api.types.Params
	6,  // 2: api.netbox_go.v1.ListDcimRegionReply.dcimRegions:type_name -> api.netbox_go.v1.DcimRegion
	20, // 3: api.netbox_go.v1.GetDcimRegionByConditionRequest.conditions:type_name -> api.types.Conditions
	6,  // 4: api.netbox_go.v1.GetDcimRegionByConditionReply.dcimRegion:type_name -> api.netbox_go.v1.DcimRegion
	6,  // 5: api.netbox_go.v1.ListDcimRegionByIDsReply.dcimRegions:type_name -> api.netbox_go.v1.DcimRegion
	6,  // 6: api.netbox_go.v1.ListDcimRegionByLastIDReply.dcimRegions:type_name -> api.netbox_go.v1.DcimRegion
	0,  // 7: api.netbox_go.v1.dcimRegion.Create:input_type -> api.netbox_go.v1.CreateDcimRegionRequest
	2,  // 8: api.netbox_go.v1.dcimRegion.DeleteByID:input_type -> api.netbox_go.v1.DeleteDcimRegionByIDRequest
	4,  // 9: api.netbox_go.v1.dcimRegion.UpdateByID:input_type -> api.netbox_go.v1.UpdateDcimRegionByIDRequest
	7,  // 10: api.netbox_go.v1.dcimRegion.GetByID:input_type -> api.netbox_go.v1.GetDcimRegionByIDRequest
	9,  // 11: api.netbox_go.v1.dcimRegion.List:input_type -> api.netbox_go.v1.ListDcimRegionRequest
	11, // 12: api.netbox_go.v1.dcimRegion.DeleteByIDs:input_type -> api.netbox_go.v1.DeleteDcimRegionByIDsRequest
	13, // 13: api.netbox_go.v1.dcimRegion.GetByCondition:input_type -> api.netbox_go.v1.GetDcimRegionByConditionRequest
	15, // 14: api.netbox_go.v1.dcimRegion.ListByIDs:input_type -> api.netbox_go.v1.ListDcimRegionByIDsRequest
	17, // 15: api.netbox_go.v1.dcimRegion.ListByLastID:input_type -> api.netbox_go.v1.ListDcimRegionByLastIDRequest
	1,  // 16: api.netbox_go.v1.dcimRegion.Create:output_type -> api.netbox_go.v1.CreateDcimRegionReply
	3,  // 17: api.netbox_go.v1.dcimRegion.DeleteByID:output_type -> api.netbox_go.v1.DeleteDcimRegionByIDReply
	5,  // 18: api.netbox_go.v1.dcimRegion.UpdateByID:output_type -> api.netbox_go.v1.UpdateDcimRegionByIDReply
	8,  // 19: api.netbox_go.v1.dcimRegion.GetByID:output_type -> api.netbox_go.v1.GetDcimRegionByIDReply
	10, // 20: api.netbox_go.v1.dcimRegion.List:output_type -> api.netbox_go.v1.ListDcimRegionReply
	12, // 21: api.netbox_go.v1.dcimRegion.DeleteByIDs:output_type -> api.netbox_go.v1.DeleteDcimRegionByIDsReply
	14, // 22: api.netbox_go.v1.dcimRegion.GetByCondition:output_type -> api.netbox_go.v1.GetDcimRegionByConditionReply
	16, // 23: api.netbox_go.v1.dcimRegion.ListByIDs:output_type -> api.netbox_go.v1.ListDcimRegionByIDsReply
	18, // 24: api.netbox_go.v1.dcimRegion.ListByLastID:output_type -> api.netbox_go.v1.ListDcimRegionByLastIDReply
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_netbox_go_v1_dcimRegion_proto_init() }
func file_api_netbox_go_v1_dcimRegion_proto_init() {
	if File_api_netbox_go_v1_dcimRegion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_netbox_go_v1_dcimRegion_proto_rawDesc), len(file_api_netbox_go_v1_dcimRegion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_netbox_go_v1_dcimRegion_proto_goTypes,
		DependencyIndexes: file_api_netbox_go_v1_dcimRegion_proto_depIdxs,
		MessageInfos:      file_api_netbox_go_v1_dcimRegion_proto_msgTypes,
	}.Build()
	File_api_netbox_go_v1_dcimRegion_proto = out.File
	file_api_netbox_go_v1_dcimRegion_proto_goTypes = nil
	file_api_netbox_go_v1_dcimRegion_proto_depIdxs = nil
}
