syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service dcimVirtualchassis {
  // Create a new dcimVirtualchassis
  rpc Create(CreateDcimVirtualchassisRequest) returns (CreateDcimVirtualchassisReply) {
    option (google.api.http) = {
      post: "/api/dcim/virtualchassis"
      body: "*"
    };
  }

  // Delete a dcimVirtualchassis by id
  rpc DeleteByID(DeleteDcimVirtualchassisByIDRequest) returns (DeleteDcimVirtualchassisByIDReply) {
    option (google.api.http) = {
      delete: "/api/dcim/virtualchassis/{id}"
    };
  }

  // Update a dcimVirtualchassis by id
  rpc UpdateByID(UpdateDcimVirtualchassisByIDRequest) returns (UpdateDcimVirtualchassisByIDReply) {
    option (google.api.http) = {
      put: "/api/dcim/virtualchassis/{id}"
      body: "*"
    };
  }

  // Get a dcimVirtualchassis by id
  rpc GetByID(GetDcimVirtualchassisByIDRequest) returns (GetDcimVirtualchassisByIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/virtualchassis/{id}"
    };
  }

  // Get a paginated list of dcimVirtualchassis by custom conditions
  rpc List(ListDcimVirtualchassisRequest) returns (ListDcimVirtualchassisReply) {
    option (google.api.http) = {
      post: "/api/dcim/virtualchassis/list"
      body: "*"
    };
  }

  // Batch delete dcimVirtualchassis by ids
  rpc DeleteByIDs(DeleteDcimVirtualchassisByIDsRequest) returns (DeleteDcimVirtualchassisByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/virtualchassis/delete/ids"
      body: "*"
    };
  }

  // Get a dcimVirtualchassis by custom condition
  rpc GetByCondition(GetDcimVirtualchassisByConditionRequest) returns (GetDcimVirtualchassisByConditionReply) {
    option (google.api.http) = {
      post: "/api/dcim/virtualchassis/condition"
      body: "*"
    };
  }

  // Batch get dcimVirtualchassis by ids
  rpc ListByIDs(ListDcimVirtualchassisByIDsRequest) returns (ListDcimVirtualchassisByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/virtualchassis/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of dcimVirtualchassis by last id
  rpc ListByLastID(ListDcimVirtualchassisByLastIDRequest) returns (ListDcimVirtualchassisByLastIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/virtualchassis"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/dcimVirtualchassis/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getDcimVirtualchassis?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateDcimVirtualchassisRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	string name = 4; 
	string domain = 5; 
	int64 masterID = 6; 
	string comments = 7; 
	string description = 8; 
	int64 memberCount = 9; 
}

message CreateDcimVirtualchassisReply {
  uint64 id = 1;
}

message DeleteDcimVirtualchassisByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteDcimVirtualchassisByIDReply {

}

message UpdateDcimVirtualchassisByIDRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string name = 5; 
	string domain = 6; 
	int64 masterID = 7; 
	string comments = 8; 
	string description = 9; 
	int64 memberCount = 10; 
}

message UpdateDcimVirtualchassisByIDReply {

}

message DcimVirtualchassis {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4; 
	string name = 5; 
	string domain = 6; 
	int64 masterID = 7; 
	string comments = 8; 
	string description = 9; 
	int64 memberCount = 10; 
}

message GetDcimVirtualchassisByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetDcimVirtualchassisByIDReply {
  DcimVirtualchassis dcimVirtualchassis = 1;
}

message ListDcimVirtualchassisRequest {
  api.types.Params params = 1;
}

message ListDcimVirtualchassisReply {
  int64 total = 1;
  repeated DcimVirtualchassis dcimVirtualchassiss = 2;
}

message DeleteDcimVirtualchassisByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteDcimVirtualchassisByIDsReply {

}

message GetDcimVirtualchassisByConditionRequest {
  types.Conditions conditions = 1;
}

message GetDcimVirtualchassisByConditionReply {
  DcimVirtualchassis dcimVirtualchassis = 1;
}

message ListDcimVirtualchassisByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListDcimVirtualchassisByIDsReply {
  repeated DcimVirtualchassis dcimVirtualchassiss = 1;
}

message ListDcimVirtualchassisByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListDcimVirtualchassisByLastIDReply {
  repeated DcimVirtualchassis dcimVirtualchassiss = 1;
}


