syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service dcimModulebaytemplate {
  // Create a new dcimModulebaytemplate
  rpc Create(CreateDcimModulebaytemplateRequest) returns (CreateDcimModulebaytemplateReply) {
    option (google.api.http) = {
      post: "/api/dcim/modulebaytemplates"
      body: "*"
    };
  }

  // Delete a dcimModulebaytemplate by id
  rpc DeleteByID(DeleteDcimModulebaytemplateByIDRequest) returns (DeleteDcimModulebaytemplateByIDReply) {
    option (google.api.http) = {
      delete: "/api/dcim/modulebaytemplates/{id}"
    };
  }

  // Update a dcimModulebaytemplate by id
  rpc UpdateByID(UpdateDcimModulebaytemplateByIDRequest) returns (UpdateDcimModulebaytemplateByIDReply) {
    option (google.api.http) = {
      put: "/api/dcim/modulebaytemplates/{id}"
      body: "*"
    };
  }

  // Get a dcimModulebaytemplate by id
  rpc GetByID(GetDcimModulebaytemplateByIDRequest) returns (GetDcimModulebaytemplateByIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/modulebaytemplates/{id}"
    };
  }

  // Get a paginated list of dcimModulebaytemplate by custom conditions
  rpc List(ListDcimModulebaytemplateRequest) returns (ListDcimModulebaytemplateReply) {
    option (google.api.http) = {
      post: "/api/dcim/modulebaytemplates/list"
      body: "*"
    };
  }

  // Batch delete dcimModulebaytemplate by ids
  rpc DeleteByIDs(DeleteDcimModulebaytemplateByIDsRequest) returns (DeleteDcimModulebaytemplateByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/modulebaytemplates/delete/ids"
      body: "*"
    };
  }

  // Get a dcimModulebaytemplate by custom condition
  rpc GetByCondition(GetDcimModulebaytemplateByConditionRequest) returns (GetDcimModulebaytemplateByConditionReply) {
    option (google.api.http) = {
      post: "/api/dcim/modulebaytemplates/condition"
      body: "*"
    };
  }

  // Batch get dcimModulebaytemplate by ids
  rpc ListByIDs(ListDcimModulebaytemplateByIDsRequest) returns (ListDcimModulebaytemplateByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/modulebaytemplates/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of dcimModulebaytemplate by last id
  rpc ListByLastID(ListDcimModulebaytemplateByLastIDRequest) returns (ListDcimModulebaytemplateByLastIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/modulebaytemplates"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/dcimModulebaytemplate/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getDcimModulebaytemplate?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateDcimModulebaytemplateRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string name = 3; 
	string label = 4; 
	string position = 5; 
	string description = 6; 
	int64 deviceTypeID = 7; 
	int64 moduleTypeID = 8; 
}

message CreateDcimModulebaytemplateReply {
  uint64 id = 1;
}

message DeleteDcimModulebaytemplateByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteDcimModulebaytemplateByIDReply {

}

message UpdateDcimModulebaytemplateByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string created = 2; 
	string lastUpdated = 3; 
	string name = 4; 
	string label = 5; 
	string position = 6; 
	string description = 7; 
	int64 deviceTypeID = 8; 
	int64 moduleTypeID = 9; 
}

message UpdateDcimModulebaytemplateByIDReply {

}

message DcimModulebaytemplate {
	uint64 id = 1; 
	string created = 2; 
	string lastUpdated = 3; 
	string name = 4; 
	string label = 5; 
	string position = 6; 
	string description = 7; 
	int64 deviceTypeID = 8; 
	int64 moduleTypeID = 9; 
}

message GetDcimModulebaytemplateByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetDcimModulebaytemplateByIDReply {
  DcimModulebaytemplate dcimModulebaytemplate = 1;
}

message ListDcimModulebaytemplateRequest {
  api.types.Params params = 1;
}

message ListDcimModulebaytemplateReply {
  int64 total = 1;
  repeated DcimModulebaytemplate dcimModulebaytemplates = 2;
}

message DeleteDcimModulebaytemplateByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteDcimModulebaytemplateByIDsReply {

}

message GetDcimModulebaytemplateByConditionRequest {
  types.Conditions conditions = 1;
}

message GetDcimModulebaytemplateByConditionReply {
  DcimModulebaytemplate dcimModulebaytemplate = 1;
}

message ListDcimModulebaytemplateByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListDcimModulebaytemplateByIDsReply {
  repeated DcimModulebaytemplate dcimModulebaytemplates = 1;
}

message ListDcimModulebaytemplateByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListDcimModulebaytemplateByLastIDReply {
  repeated DcimModulebaytemplate dcimModulebaytemplates = 1;
}


