syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service dcimCabletermination {
  // Create a new dcimCabletermination
  rpc Create(CreateDcimCableterminationRequest) returns (CreateDcimCableterminationReply) {
    option (google.api.http) = {
      post: "/api/dcim/cableterminations"
      body: "*"
    };
  }

  // Delete a dcimCabletermination by id
  rpc DeleteByID(DeleteDcimCableterminationByIDRequest) returns (DeleteDcimCableterminationByIDReply) {
    option (google.api.http) = {
      delete: "/api/dcim/cableterminations/{id}"
    };
  }

  // Update a dcimCabletermination by id
  rpc UpdateByID(UpdateDcimCableterminationByIDRequest) returns (UpdateDcimCableterminationByIDReply) {
    option (google.api.http) = {
      put: "/api/dcim/cableterminations/{id}"
      body: "*"
    };
  }

  // Get a dcimCabletermination by id
  rpc GetByID(GetDcimCableterminationByIDRequest) returns (GetDcimCableterminationByIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/cableterminations/{id}"
    };
  }

  // Get a paginated list of dcimCabletermination by custom conditions
  rpc List(ListDcimCableterminationRequest) returns (ListDcimCableterminationReply) {
    option (google.api.http) = {
      post: "/api/dcim/cableterminations/list"
      body: "*"
    };
  }

  // Batch delete dcimCabletermination by ids
  rpc DeleteByIDs(DeleteDcimCableterminationByIDsRequest) returns (DeleteDcimCableterminationByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/cableterminations/delete/ids"
      body: "*"
    };
  }

  // Get a dcimCabletermination by custom condition
  rpc GetByCondition(GetDcimCableterminationByConditionRequest) returns (GetDcimCableterminationByConditionReply) {
    option (google.api.http) = {
      post: "/api/dcim/cableterminations/condition"
      body: "*"
    };
  }

  // Batch get dcimCabletermination by ids
  rpc ListByIDs(ListDcimCableterminationByIDsRequest) returns (ListDcimCableterminationByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/cableterminations/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of dcimCabletermination by last id
  rpc ListByLastID(ListDcimCableterminationByLastIDRequest) returns (ListDcimCableterminationByLastIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/cableterminations"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/dcimCabletermination/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getDcimCabletermination?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateDcimCableterminationRequest {
	string cableEnd = 1; 
	int64 terminationID = 2; 
	int64 cableID = 3; 
	int32 terminationTypeID = 4; 
	int64 xDeviceID = 5; 
	int64 xRackID = 6; 
	int64 xLocationID = 7; 
	int64 xSiteID = 8; 
	string created = 9; 
	string lastUpdated = 10; 
}

message CreateDcimCableterminationReply {
  uint64 id = 1;
}

message DeleteDcimCableterminationByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteDcimCableterminationByIDReply {

}

message UpdateDcimCableterminationByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string cableEnd = 2; 
	int64 terminationID = 3; 
	int64 cableID = 4; 
	int32 terminationTypeID = 5; 
	int64 xDeviceID = 6; 
	int64 xRackID = 7; 
	int64 xLocationID = 8; 
	int64 xSiteID = 9; 
	string created = 10; 
	string lastUpdated = 11; 
}

message UpdateDcimCableterminationByIDReply {

}

message DcimCabletermination {
	uint64 id = 1; 
	string cableEnd = 2; 
	int64 terminationID = 3; 
	int64 cableID = 4; 
	int32 terminationTypeID = 5; 
	int64 xDeviceID = 6; 
	int64 xRackID = 7; 
	int64 xLocationID = 8; 
	int64 xSiteID = 9; 
	string created = 10; 
	string lastUpdated = 11; 
}

message GetDcimCableterminationByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetDcimCableterminationByIDReply {
  DcimCabletermination dcimCabletermination = 1;
}

message ListDcimCableterminationRequest {
  api.types.Params params = 1;
}

message ListDcimCableterminationReply {
  int64 total = 1;
  repeated DcimCabletermination dcimCableterminations = 2;
}

message DeleteDcimCableterminationByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteDcimCableterminationByIDsReply {

}

message GetDcimCableterminationByConditionRequest {
  types.Conditions conditions = 1;
}

message GetDcimCableterminationByConditionReply {
  DcimCabletermination dcimCabletermination = 1;
}

message ListDcimCableterminationByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListDcimCableterminationByIDsReply {
  repeated DcimCabletermination dcimCableterminations = 1;
}

message ListDcimCableterminationByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListDcimCableterminationByLastIDReply {
  repeated DcimCabletermination dcimCableterminations = 1;
}


