// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/netbox_go/v1/dcimFrontport.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DcimFrontport_Create_FullMethodName         = "/api.netbox_go.v1.dcimFrontport/Create"
	DcimFrontport_DeleteByID_FullMethodName     = "/api.netbox_go.v1.dcimFrontport/DeleteByID"
	DcimFrontport_UpdateByID_FullMethodName     = "/api.netbox_go.v1.dcimFrontport/UpdateByID"
	DcimFrontport_GetByID_FullMethodName        = "/api.netbox_go.v1.dcimFrontport/GetByID"
	DcimFrontport_List_FullMethodName           = "/api.netbox_go.v1.dcimFrontport/List"
	DcimFrontport_DeleteByIDs_FullMethodName    = "/api.netbox_go.v1.dcimFrontport/DeleteByIDs"
	DcimFrontport_GetByCondition_FullMethodName = "/api.netbox_go.v1.dcimFrontport/GetByCondition"
	DcimFrontport_ListByIDs_FullMethodName      = "/api.netbox_go.v1.dcimFrontport/ListByIDs"
	DcimFrontport_ListByLastID_FullMethodName   = "/api.netbox_go.v1.dcimFrontport/ListByLastID"
)

// DcimFrontportClient is the client API for DcimFrontport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DcimFrontportClient interface {
	// Create a new dcimFrontport
	Create(ctx context.Context, in *CreateDcimFrontportRequest, opts ...grpc.CallOption) (*CreateDcimFrontportReply, error)
	// Delete a dcimFrontport by id
	DeleteByID(ctx context.Context, in *DeleteDcimFrontportByIDRequest, opts ...grpc.CallOption) (*DeleteDcimFrontportByIDReply, error)
	// Update a dcimFrontport by id
	UpdateByID(ctx context.Context, in *UpdateDcimFrontportByIDRequest, opts ...grpc.CallOption) (*UpdateDcimFrontportByIDReply, error)
	// Get a dcimFrontport by id
	GetByID(ctx context.Context, in *GetDcimFrontportByIDRequest, opts ...grpc.CallOption) (*GetDcimFrontportByIDReply, error)
	// Get a paginated list of dcimFrontport by custom conditions
	List(ctx context.Context, in *ListDcimFrontportRequest, opts ...grpc.CallOption) (*ListDcimFrontportReply, error)
	// Batch delete dcimFrontport by ids
	DeleteByIDs(ctx context.Context, in *DeleteDcimFrontportByIDsRequest, opts ...grpc.CallOption) (*DeleteDcimFrontportByIDsReply, error)
	// Get a dcimFrontport by custom condition
	GetByCondition(ctx context.Context, in *GetDcimFrontportByConditionRequest, opts ...grpc.CallOption) (*GetDcimFrontportByConditionReply, error)
	// Batch get dcimFrontport by ids
	ListByIDs(ctx context.Context, in *ListDcimFrontportByIDsRequest, opts ...grpc.CallOption) (*ListDcimFrontportByIDsReply, error)
	// Get a paginated list of dcimFrontport by last id
	ListByLastID(ctx context.Context, in *ListDcimFrontportByLastIDRequest, opts ...grpc.CallOption) (*ListDcimFrontportByLastIDReply, error)
}

type dcimFrontportClient struct {
	cc grpc.ClientConnInterface
}

func NewDcimFrontportClient(cc grpc.ClientConnInterface) DcimFrontportClient {
	return &dcimFrontportClient{cc}
}

func (c *dcimFrontportClient) Create(ctx context.Context, in *CreateDcimFrontportRequest, opts ...grpc.CallOption) (*CreateDcimFrontportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDcimFrontportReply)
	err := c.cc.Invoke(ctx, DcimFrontport_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcimFrontportClient) DeleteByID(ctx context.Context, in *DeleteDcimFrontportByIDRequest, opts ...grpc.CallOption) (*DeleteDcimFrontportByIDReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDcimFrontportByIDReply)
	err := c.cc.Invoke(ctx, DcimFrontport_DeleteByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcimFrontportClient) UpdateByID(ctx context.Context, in *UpdateDcimFrontportByIDRequest, opts ...grpc.CallOption) (*UpdateDcimFrontportByIDReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDcimFrontportByIDReply)
	err := c.cc.Invoke(ctx, DcimFrontport_UpdateByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcimFrontportClient) GetByID(ctx context.Context, in *GetDcimFrontportByIDRequest, opts ...grpc.CallOption) (*GetDcimFrontportByIDReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDcimFrontportByIDReply)
	err := c.cc.Invoke(ctx, DcimFrontport_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcimFrontportClient) List(ctx context.Context, in *ListDcimFrontportRequest, opts ...grpc.CallOption) (*ListDcimFrontportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDcimFrontportReply)
	err := c.cc.Invoke(ctx, DcimFrontport_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcimFrontportClient) DeleteByIDs(ctx context.Context, in *DeleteDcimFrontportByIDsRequest, opts ...grpc.CallOption) (*DeleteDcimFrontportByIDsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDcimFrontportByIDsReply)
	err := c.cc.Invoke(ctx, DcimFrontport_DeleteByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcimFrontportClient) GetByCondition(ctx context.Context, in *GetDcimFrontportByConditionRequest, opts ...grpc.CallOption) (*GetDcimFrontportByConditionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDcimFrontportByConditionReply)
	err := c.cc.Invoke(ctx, DcimFrontport_GetByCondition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcimFrontportClient) ListByIDs(ctx context.Context, in *ListDcimFrontportByIDsRequest, opts ...grpc.CallOption) (*ListDcimFrontportByIDsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDcimFrontportByIDsReply)
	err := c.cc.Invoke(ctx, DcimFrontport_ListByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcimFrontportClient) ListByLastID(ctx context.Context, in *ListDcimFrontportByLastIDRequest, opts ...grpc.CallOption) (*ListDcimFrontportByLastIDReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDcimFrontportByLastIDReply)
	err := c.cc.Invoke(ctx, DcimFrontport_ListByLastID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DcimFrontportServer is the server API for DcimFrontport service.
// All implementations must embed UnimplementedDcimFrontportServer
// for forward compatibility.
type DcimFrontportServer interface {
	// Create a new dcimFrontport
	Create(context.Context, *CreateDcimFrontportRequest) (*CreateDcimFrontportReply, error)
	// Delete a dcimFrontport by id
	DeleteByID(context.Context, *DeleteDcimFrontportByIDRequest) (*DeleteDcimFrontportByIDReply, error)
	// Update a dcimFrontport by id
	UpdateByID(context.Context, *UpdateDcimFrontportByIDRequest) (*UpdateDcimFrontportByIDReply, error)
	// Get a dcimFrontport by id
	GetByID(context.Context, *GetDcimFrontportByIDRequest) (*GetDcimFrontportByIDReply, error)
	// Get a paginated list of dcimFrontport by custom conditions
	List(context.Context, *ListDcimFrontportRequest) (*ListDcimFrontportReply, error)
	// Batch delete dcimFrontport by ids
	DeleteByIDs(context.Context, *DeleteDcimFrontportByIDsRequest) (*DeleteDcimFrontportByIDsReply, error)
	// Get a dcimFrontport by custom condition
	GetByCondition(context.Context, *GetDcimFrontportByConditionRequest) (*GetDcimFrontportByConditionReply, error)
	// Batch get dcimFrontport by ids
	ListByIDs(context.Context, *ListDcimFrontportByIDsRequest) (*ListDcimFrontportByIDsReply, error)
	// Get a paginated list of dcimFrontport by last id
	ListByLastID(context.Context, *ListDcimFrontportByLastIDRequest) (*ListDcimFrontportByLastIDReply, error)
	mustEmbedUnimplementedDcimFrontportServer()
}

// UnimplementedDcimFrontportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDcimFrontportServer struct{}

func (UnimplementedDcimFrontportServer) Create(context.Context, *CreateDcimFrontportRequest) (*CreateDcimFrontportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDcimFrontportServer) DeleteByID(context.Context, *DeleteDcimFrontportByIDRequest) (*DeleteDcimFrontportByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByID not implemented")
}
func (UnimplementedDcimFrontportServer) UpdateByID(context.Context, *UpdateDcimFrontportByIDRequest) (*UpdateDcimFrontportByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateByID not implemented")
}
func (UnimplementedDcimFrontportServer) GetByID(context.Context, *GetDcimFrontportByIDRequest) (*GetDcimFrontportByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedDcimFrontportServer) List(context.Context, *ListDcimFrontportRequest) (*ListDcimFrontportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDcimFrontportServer) DeleteByIDs(context.Context, *DeleteDcimFrontportByIDsRequest) (*DeleteDcimFrontportByIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByIDs not implemented")
}
func (UnimplementedDcimFrontportServer) GetByCondition(context.Context, *GetDcimFrontportByConditionRequest) (*GetDcimFrontportByConditionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByCondition not implemented")
}
func (UnimplementedDcimFrontportServer) ListByIDs(context.Context, *ListDcimFrontportByIDsRequest) (*ListDcimFrontportByIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByIDs not implemented")
}
func (UnimplementedDcimFrontportServer) ListByLastID(context.Context, *ListDcimFrontportByLastIDRequest) (*ListDcimFrontportByLastIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByLastID not implemented")
}
func (UnimplementedDcimFrontportServer) mustEmbedUnimplementedDcimFrontportServer() {}
func (UnimplementedDcimFrontportServer) testEmbeddedByValue()                       {}

// UnsafeDcimFrontportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DcimFrontportServer will
// result in compilation errors.
type UnsafeDcimFrontportServer interface {
	mustEmbedUnimplementedDcimFrontportServer()
}

func RegisterDcimFrontportServer(s grpc.ServiceRegistrar, srv DcimFrontportServer) {
	// If the following call pancis, it indicates UnimplementedDcimFrontportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DcimFrontport_ServiceDesc, srv)
}

func _DcimFrontport_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDcimFrontportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcimFrontportServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcimFrontport_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcimFrontportServer).Create(ctx, req.(*CreateDcimFrontportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcimFrontport_DeleteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDcimFrontportByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcimFrontportServer).DeleteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcimFrontport_DeleteByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcimFrontportServer).DeleteByID(ctx, req.(*DeleteDcimFrontportByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcimFrontport_UpdateByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDcimFrontportByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcimFrontportServer).UpdateByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcimFrontport_UpdateByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcimFrontportServer).UpdateByID(ctx, req.(*UpdateDcimFrontportByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcimFrontport_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDcimFrontportByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcimFrontportServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcimFrontport_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcimFrontportServer).GetByID(ctx, req.(*GetDcimFrontportByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcimFrontport_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDcimFrontportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcimFrontportServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcimFrontport_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcimFrontportServer).List(ctx, req.(*ListDcimFrontportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcimFrontport_DeleteByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDcimFrontportByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcimFrontportServer).DeleteByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcimFrontport_DeleteByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcimFrontportServer).DeleteByIDs(ctx, req.(*DeleteDcimFrontportByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcimFrontport_GetByCondition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDcimFrontportByConditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcimFrontportServer).GetByCondition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcimFrontport_GetByCondition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcimFrontportServer).GetByCondition(ctx, req.(*GetDcimFrontportByConditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcimFrontport_ListByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDcimFrontportByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcimFrontportServer).ListByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcimFrontport_ListByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcimFrontportServer).ListByIDs(ctx, req.(*ListDcimFrontportByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcimFrontport_ListByLastID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDcimFrontportByLastIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcimFrontportServer).ListByLastID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcimFrontport_ListByLastID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcimFrontportServer).ListByLastID(ctx, req.(*ListDcimFrontportByLastIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DcimFrontport_ServiceDesc is the grpc.ServiceDesc for DcimFrontport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DcimFrontport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.netbox_go.v1.dcimFrontport",
	HandlerType: (*DcimFrontportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DcimFrontport_Create_Handler,
		},
		{
			MethodName: "DeleteByID",
			Handler:    _DcimFrontport_DeleteByID_Handler,
		},
		{
			MethodName: "UpdateByID",
			Handler:    _DcimFrontport_UpdateByID_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _DcimFrontport_GetByID_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DcimFrontport_List_Handler,
		},
		{
			MethodName: "DeleteByIDs",
			Handler:    _DcimFrontport_DeleteByIDs_Handler,
		},
		{
			MethodName: "GetByCondition",
			Handler:    _DcimFrontport_GetByCondition_Handler,
		},
		{
			MethodName: "ListByIDs",
			Handler:    _DcimFrontport_ListByIDs_Handler,
		},
		{
			MethodName: "ListByLastID",
			Handler:    _DcimFrontport_ListByLastID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/netbox_go/v1/dcimFrontport.proto",
}
