syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service dcimCable {
  // Create a new dcimCable
  rpc Create(CreateDcimCableRequest) returns (CreateDcimCableReply) {
    option (google.api.http) = {
      post: "/api/dcim/cables"
      body: "*"
    };
  }

  // Delete a dcimCable by id
  rpc DeleteByID(DeleteDcimCableByIDRequest) returns (DeleteDcimCableByIDReply) {
    option (google.api.http) = {
      delete: "/api/dcim/cables/{id}"
    };
  }

  // Update a dcimCable by id
  rpc UpdateByID(UpdateDcimCableByIDRequest) returns (UpdateDcimCableByIDReply) {
    option (google.api.http) = {
      put: "/api/dcim/cables/{id}"
      body: "*"
    };
  }

  // Get a dcimCable by id
  rpc GetByID(GetDcimCableByIDRequest) returns (GetDcimCableByIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/cables/{id}"
    };
  }

  // Get a paginated list of dcimCable by custom conditions
  rpc List(ListDcimCableRequest) returns (ListDcimCableReply) {
    option (google.api.http) = {
      post: "/api/dcim/cables/list"
      body: "*"
    };
  }

  // Batch delete dcimCable by ids
  rpc DeleteByIDs(DeleteDcimCableByIDsRequest) returns (DeleteDcimCableByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/cables/delete/ids"
      body: "*"
    };
  }

  // Get a dcimCable by custom condition
  rpc GetByCondition(GetDcimCableByConditionRequest) returns (GetDcimCableByConditionReply) {
    option (google.api.http) = {
      post: "/api/dcim/cables/condition"
      body: "*"
    };
  }

  // Batch get dcimCable by ids
  rpc ListByIDs(ListDcimCableByIDsRequest) returns (ListDcimCableByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/cables/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of dcimCable by last id
  rpc ListByLastID(ListDcimCableByLastIDRequest) returns (ListDcimCableByLastIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/cables"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/dcimCable/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getDcimCable?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateDcimCableRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	string type = 4; 
	string status = 5; 
	string label = 6; 
	string color = 7; 
	string length = 8; 
	string lengthUnit = 9; 
	string xAbsLength = 10; 
	int64 tenantID = 11; 
	string comments = 12; 
	string description = 13; 
}

message CreateDcimCableReply {
  uint64 id = 1;
}

message DeleteDcimCableByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteDcimCableByIDReply {

}

message UpdateDcimCableByIDRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string type = 5; 
	string status = 6; 
	string label = 7; 
	string color = 8; 
	string length = 9; 
	string lengthUnit = 10; 
	string xAbsLength = 11; 
	int64 tenantID = 12; 
	string comments = 13; 
	string description = 14; 
}

message UpdateDcimCableByIDReply {

}

message DcimCable {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4; 
	string type = 5; 
	string status = 6; 
	string label = 7; 
	string color = 8; 
	string length = 9; 
	string lengthUnit = 10; 
	string xAbsLength = 11; 
	int64 tenantID = 12; 
	string comments = 13; 
	string description = 14; 
}

message GetDcimCableByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetDcimCableByIDReply {
  DcimCable dcimCable = 1;
}

message ListDcimCableRequest {
  api.types.Params params = 1;
}

message ListDcimCableReply {
  int64 total = 1;
  repeated DcimCable dcimCables = 2;
}

message DeleteDcimCableByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteDcimCableByIDsReply {

}

message GetDcimCableByConditionRequest {
  types.Conditions conditions = 1;
}

message GetDcimCableByConditionReply {
  DcimCable dcimCable = 1;
}

message ListDcimCableByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListDcimCableByIDsReply {
  repeated DcimCable dcimCables = 1;
}

message ListDcimCableByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListDcimCableByLastIDReply {
  repeated DcimCable dcimCables = 1;
}


