syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service dcimModulebay {
  // Create a new dcimModulebay
  rpc Create(CreateDcimModulebayRequest) returns (CreateDcimModulebayReply) {
    option (google.api.http) = {
      post: "/api/dcim/modulebays"
      body: "*"
    };
  }

  // Delete a dcimModulebay by id
  rpc DeleteByID(DeleteDcimModulebayByIDRequest) returns (DeleteDcimModulebayByIDReply) {
    option (google.api.http) = {
      delete: "/api/dcim/modulebays/{id}"
    };
  }

  // Update a dcimModulebay by id
  rpc UpdateByID(UpdateDcimModulebayByIDRequest) returns (UpdateDcimModulebayByIDReply) {
    option (google.api.http) = {
      put: "/api/dcim/modulebays/{id}"
      body: "*"
    };
  }

  // Get a dcimModulebay by id
  rpc GetByID(GetDcimModulebayByIDRequest) returns (GetDcimModulebayByIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/modulebays/{id}"
    };
  }

  // Get a paginated list of dcimModulebay by custom conditions
  rpc List(ListDcimModulebayRequest) returns (ListDcimModulebayReply) {
    option (google.api.http) = {
      post: "/api/dcim/modulebays/list"
      body: "*"
    };
  }

  // Batch delete dcimModulebay by ids
  rpc DeleteByIDs(DeleteDcimModulebayByIDsRequest) returns (DeleteDcimModulebayByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/modulebays/delete/ids"
      body: "*"
    };
  }

  // Get a dcimModulebay by custom condition
  rpc GetByCondition(GetDcimModulebayByConditionRequest) returns (GetDcimModulebayByConditionReply) {
    option (google.api.http) = {
      post: "/api/dcim/modulebays/condition"
      body: "*"
    };
  }

  // Batch get dcimModulebay by ids
  rpc ListByIDs(ListDcimModulebayByIDsRequest) returns (ListDcimModulebayByIDsReply) {
    option (google.api.http) = {
      post: "/api/dcim/modulebays/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of dcimModulebay by last id
  rpc ListByLastID(ListDcimModulebayByLastIDRequest) returns (ListDcimModulebayByLastIDReply) {
    option (google.api.http) = {
      get: "/api/dcim/modulebays"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/dcimModulebay/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getDcimModulebay?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateDcimModulebayRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	string name = 4; 
	string label = 5; 
	string position = 6; 
	string description = 7; 
	int64 deviceID = 8; 
	int32 level = 9; 
	int32 lft = 10; 
	int64 moduleID = 11; 
	int64 parentID = 12; 
	int32 rght = 13; 
	int32 treeID = 14; 
	int64 xLocationID = 15; 
	int64 xRackID = 16; 
	int64 xSiteID = 17; 
}

message CreateDcimModulebayReply {
  uint64 id = 1;
}

message DeleteDcimModulebayByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteDcimModulebayByIDReply {

}

message UpdateDcimModulebayByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string created = 2; 
	string lastUpdated = 3; 
	string customFieldData = 4; 
	string name = 5; 
	string label = 6; 
	string position = 7; 
	string description = 8; 
	int64 deviceID = 9; 
	int32 level = 10; 
	int32 lft = 11; 
	int64 moduleID = 12; 
	int64 parentID = 13; 
	int32 rght = 14; 
	int32 treeID = 15; 
	int64 xLocationID = 16; 
	int64 xRackID = 17; 
	int64 xSiteID = 18; 
}

message UpdateDcimModulebayByIDReply {

}

message DcimModulebay {
	uint64 id = 1; 
	string created = 2; 
	string lastUpdated = 3; 
	string customFieldData = 4; 
	string name = 5; 
	string label = 6; 
	string position = 7; 
	string description = 8; 
	int64 deviceID = 9; 
	int32 level = 10; 
	int32 lft = 11; 
	int64 moduleID = 12; 
	int64 parentID = 13; 
	int32 rght = 14; 
	int32 treeID = 15; 
	int64 xLocationID = 16; 
	int64 xRackID = 17; 
	int64 xSiteID = 18; 
}

message GetDcimModulebayByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetDcimModulebayByIDReply {
  DcimModulebay dcimModulebay = 1;
}

message ListDcimModulebayRequest {
  api.types.Params params = 1;
}

message ListDcimModulebayReply {
  int64 total = 1;
  repeated DcimModulebay dcimModulebays = 2;
}

message DeleteDcimModulebayByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteDcimModulebayByIDsReply {

}

message GetDcimModulebayByConditionRequest {
  types.Conditions conditions = 1;
}

message GetDcimModulebayByConditionReply {
  DcimModulebay dcimModulebay = 1;
}

message ListDcimModulebayByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListDcimModulebayByIDsReply {
  repeated DcimModulebay dcimModulebays = 1;
}

message ListDcimModulebayByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListDcimModulebayByLastIDReply {
  repeated DcimModulebay dcimModulebays = 1;
}


