// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type DcimPoweroutlettemplateLogicer interface {
	Create(ctx context.Context, req *CreateDcimPoweroutlettemplateRequest) (*CreateDcimPoweroutlettemplateReply, error)
	DeleteByID(ctx context.Context, req *DeleteDcimPoweroutlettemplateByIDRequest) (*DeleteDcimPoweroutlettemplateByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateDcimPoweroutlettemplateByIDRequest) (*UpdateDcimPoweroutlettemplateByIDReply, error)
	GetByID(ctx context.Context, req *GetDcimPoweroutlettemplateByIDRequest) (*GetDcimPoweroutlettemplateByIDReply, error)
	List(ctx context.Context, req *ListDcimPoweroutlettemplateRequest) (*ListDcimPoweroutlettemplateReply, error)
	DeleteByIDs(ctx context.Context, req *DeleteDcimPoweroutlettemplateByIDsRequest) (*DeleteDcimPoweroutlettemplateByIDsReply, error)
	GetByCondition(ctx context.Context, req *GetDcimPoweroutlettemplateByConditionRequest) (*GetDcimPoweroutlettemplateByConditionReply, error)
	ListByIDs(ctx context.Context, req *ListDcimPoweroutlettemplateByIDsRequest) (*ListDcimPoweroutlettemplateByIDsReply, error)
	ListByLastID(ctx context.Context, req *ListDcimPoweroutlettemplateByLastIDRequest) (*ListDcimPoweroutlettemplateByLastIDReply, error)
}

type DcimPoweroutlettemplateOption func(*dcimPoweroutlettemplateOptions)

type dcimPoweroutlettemplateOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *dcimPoweroutlettemplateOptions) apply(opts ...DcimPoweroutlettemplateOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithDcimPoweroutlettemplateHTTPResponse() DcimPoweroutlettemplateOption {
	return func(o *dcimPoweroutlettemplateOptions) {
		o.isFromRPC = false
	}
}

func WithDcimPoweroutlettemplateRPCResponse() DcimPoweroutlettemplateOption {
	return func(o *dcimPoweroutlettemplateOptions) {
		o.isFromRPC = true
	}
}

func WithDcimPoweroutlettemplateResponser(responser errcode.Responser) DcimPoweroutlettemplateOption {
	return func(o *dcimPoweroutlettemplateOptions) {
		o.responser = responser
	}
}

func WithDcimPoweroutlettemplateLogger(zapLog *zap.Logger) DcimPoweroutlettemplateOption {
	return func(o *dcimPoweroutlettemplateOptions) {
		o.zapLog = zapLog
	}
}

func WithDcimPoweroutlettemplateErrorToHTTPCode(e ...*errcode.Error) DcimPoweroutlettemplateOption {
	return func(o *dcimPoweroutlettemplateOptions) {
		o.httpErrors = e
	}
}

func WithDcimPoweroutlettemplateRPCStatusToHTTPCode(s ...*errcode.RPCStatus) DcimPoweroutlettemplateOption {
	return func(o *dcimPoweroutlettemplateOptions) {
		o.rpcStatus = s
	}
}

func WithDcimPoweroutlettemplateWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) DcimPoweroutlettemplateOption {
	return func(o *dcimPoweroutlettemplateOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterDcimPoweroutlettemplateRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic DcimPoweroutlettemplateLogicer,
	opts ...DcimPoweroutlettemplateOption) {

	o := &dcimPoweroutlettemplateOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &dcimPoweroutlettemplateRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type dcimPoweroutlettemplateRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                DcimPoweroutlettemplateLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *dcimPoweroutlettemplateRouter) register() {
	r.iRouter.Handle("POST", "/api/dcim/poweroutlettemplates", r.withMiddleware("POST", "/api/dcim/poweroutlettemplates", r.Create_112)...)
	r.iRouter.Handle("DELETE", "/api/dcim/poweroutlettemplates/:id", r.withMiddleware("DELETE", "/api/dcim/poweroutlettemplates/:id", r.DeleteByID_110)...)
	r.iRouter.Handle("PUT", "/api/dcim/poweroutlettemplates/:id", r.withMiddleware("PUT", "/api/dcim/poweroutlettemplates/:id", r.UpdateByID_110)...)
	r.iRouter.Handle("GET", "/api/dcim/poweroutlettemplates/:id", r.withMiddleware("GET", "/api/dcim/poweroutlettemplates/:id", r.GetByID_110)...)
	r.iRouter.Handle("POST", "/api/dcim/poweroutlettemplates/list", r.withMiddleware("POST", "/api/dcim/poweroutlettemplates/list", r.List_112)...)
	r.iRouter.Handle("POST", "/api/dcim/poweroutlettemplates/delete/ids", r.withMiddleware("POST", "/api/dcim/poweroutlettemplates/delete/ids", r.DeleteByIDs_110)...)
	r.iRouter.Handle("POST", "/api/dcim/poweroutlettemplates/condition", r.withMiddleware("POST", "/api/dcim/poweroutlettemplates/condition", r.GetByCondition_112)...)
	r.iRouter.Handle("POST", "/api/dcim/poweroutlettemplates/list/ids", r.withMiddleware("POST", "/api/dcim/poweroutlettemplates/list/ids", r.ListByIDs_110)...)
	r.iRouter.Handle("GET", "/api/dcim/poweroutlettemplates", r.withMiddleware("GET", "/api/dcim/poweroutlettemplates", r.ListByLastID_110)...)

}

func (r *dcimPoweroutlettemplateRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *dcimPoweroutlettemplateRouter) Create_112(c *gin.Context) {
	req := &CreateDcimPoweroutlettemplateRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *dcimPoweroutlettemplateRouter) DeleteByID_110(c *gin.Context) {
	req := &DeleteDcimPoweroutlettemplateByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *dcimPoweroutlettemplateRouter) UpdateByID_110(c *gin.Context) {
	req := &UpdateDcimPoweroutlettemplateByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *dcimPoweroutlettemplateRouter) GetByID_110(c *gin.Context) {
	req := &GetDcimPoweroutlettemplateByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *dcimPoweroutlettemplateRouter) List_112(c *gin.Context) {
	req := &ListDcimPoweroutlettemplateRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *dcimPoweroutlettemplateRouter) DeleteByIDs_110(c *gin.Context) {
	req := &DeleteDcimPoweroutlettemplateByIDsRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByIDs(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *dcimPoweroutlettemplateRouter) GetByCondition_112(c *gin.Context) {
	req := &GetDcimPoweroutlettemplateByConditionRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByCondition(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *dcimPoweroutlettemplateRouter) ListByIDs_110(c *gin.Context) {
	req := &ListDcimPoweroutlettemplateByIDsRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.ListByIDs(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *dcimPoweroutlettemplateRouter) ListByLastID_110(c *gin.Context) {
	req := &ListDcimPoweroutlettemplateByLastIDRequest{}
	var err error

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.ListByLastID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
