syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user details by id",
      description: "Gets detailed information of a extrasCachedvalue specified by the given id in the path.",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service extrasCachedvalue {
  // Create a new extrasCachedvalue
  rpc Create(CreateExtrasCachedvalueRequest) returns (CreateExtrasCachedvalueReply) {
    option (google.api.http) = {
      post: "/api/extras/cachedvalues"
      body: "*"
    };
  }

  // Delete a extrasCachedvalue by id
  rpc DeleteByID(DeleteExtrasCachedvalueByIDRequest) returns (DeleteExtrasCachedvalueByIDReply) {
    option (google.api.http) = {
      delete: "/api/extras/cachedvalues/{id}"
    };
  }

  // Update a extrasCachedvalue by id
  rpc UpdateByID(UpdateExtrasCachedvalueByIDRequest) returns (UpdateExtrasCachedvalueByIDReply) {
    option (google.api.http) = {
      put: "/api/extras/cachedvalues/{id}"
      body: "*"
    };
  }

  // Get a extrasCachedvalue by id
  rpc GetByID(GetExtrasCachedvalueByIDRequest) returns (GetExtrasCachedvalueByIDReply) {
    option (google.api.http) = {
      get: "/api/extras/cachedvalues/{id}"
    };
  }

  // Get a paginated list of extrasCachedvalue by custom conditions
  rpc List(ListExtrasCachedvalueRequest) returns (ListExtrasCachedvalueReply) {
    option (google.api.http) = {
      post: "/api/extras/cachedvalues/list"
      body: "*"
    };
  }

  // Batch delete extrasCachedvalue by id
  rpc DeleteByIDs(DeleteExtrasCachedvalueByIDsRequest) returns (DeleteExtrasCachedvalueByIDsReply) {
    option (google.api.http) = {
      post: "/api/extras/cachedvalues/delete/ids"
      body: "*"
    };
  }

  // Get a extrasCachedvalue by custom conditions
  rpc GetByCondition(GetExtrasCachedvalueByConditionRequest) returns (GetExtrasCachedvalueByConditionReply) {
    option (google.api.http) = {
      post: "/api/extras/cachedvalues/condition"
      body: "*"
    };
  }

  // Batch get extrasCachedvalue by id
  rpc ListByIDs(ListExtrasCachedvalueByIDsRequest) returns (ListExtrasCachedvalueByIDsReply) {
    option (google.api.http) = {
      post: "/api/extras/cachedvalues/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of extrasCachedvalue by last id
  rpc ListByLastID(ListExtrasCachedvalueByLastIDRequest) returns (ListExtrasCachedvalueByLastIDReply) {
    option (google.api.http) = {
      get: "/api/extras/cachedvalues"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/extrasCachedvalue/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getExtrasCachedvalue?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateExtrasCachedvalueRequest {
	string timestamp = 1; 
	int64 objectID = 2; 
	string field = 3; 
	string type = 4; 
	string value = 5; 
	int32 weight = 6; 
	int32 objectTypeID = 7; 
}

message CreateExtrasCachedvalueReply {
  string id = 1;
}

message DeleteExtrasCachedvalueByIDRequest {
  string id = 1 [(validate.rules).string.min_len = 1, (tagger.tags) = "uri:\"id\""];
}

message DeleteExtrasCachedvalueByIDReply {

}

message UpdateExtrasCachedvalueByIDRequest {
	string id = 1 [(validate.rules).string.min_len = 1, (tagger.tags) = "uri:\"id\""]; 
	string timestamp = 2; 
	int64 objectID = 3; 
	string field = 4; 
	string type = 5; 
	string value = 6; 
	int32 weight = 7; 
	int32 objectTypeID = 8; 
}

message UpdateExtrasCachedvalueByIDReply {

}

message ExtrasCachedvalue {
	string id = 1; 
	string timestamp = 2; 
	int64 objectID = 3; 
	string field = 4; 
	string type = 5; 
	string value = 6; 
	int32 weight = 7; 
	int32 objectTypeID = 8; 
}

message GetExtrasCachedvalueByIDRequest {
  string id = 1 [(validate.rules).string.min_len = 1, (tagger.tags) = "uri:\"id\""];
}

message GetExtrasCachedvalueByIDReply {
  ExtrasCachedvalue extrasCachedvalue = 1;
}

message ListExtrasCachedvalueRequest {
  api.types.Params params = 1;
}

message ListExtrasCachedvalueReply {
  int64 total = 1;
  repeated ExtrasCachedvalue extrasCachedvalues = 2;
}

message DeleteExtrasCachedvalueByIDsRequest {
  repeated string ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteExtrasCachedvalueByIDsReply {

}

message GetExtrasCachedvalueByConditionRequest {
  types.Conditions conditions = 1;
}

message GetExtrasCachedvalueByConditionReply {
  ExtrasCachedvalue extrasCachedvalue = 1;
}

message ListExtrasCachedvalueByIDsRequest {
  repeated string ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListExtrasCachedvalueByIDsReply {
  repeated ExtrasCachedvalue extrasCachedvalues = 1;
}

message ListExtrasCachedvalueByLastIDRequest {
  string lastID = 1 [(tagger.tags) = "form:\"lastID\""];
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListExtrasCachedvalueByLastIDReply {
  repeated ExtrasCachedvalue extrasCachedvalues = 1;
}


