syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service extrasCustomfieldchoiceset {
  // Create a new extrasCustomfieldchoiceset
  rpc Create(CreateExtrasCustomfieldchoicesetRequest) returns (CreateExtrasCustomfieldchoicesetReply) {
    option (google.api.http) = {
      post: "/api/extras/customfieldchoicesets"
      body: "*"
    };
  }

  // Delete a extrasCustomfieldchoiceset by id
  rpc DeleteByID(DeleteExtrasCustomfieldchoicesetByIDRequest) returns (DeleteExtrasCustomfieldchoicesetByIDReply) {
    option (google.api.http) = {
      delete: "/api/extras/customfieldchoicesets/{id}"
    };
  }

  // Update a extrasCustomfieldchoiceset by id
  rpc UpdateByID(UpdateExtrasCustomfieldchoicesetByIDRequest) returns (UpdateExtrasCustomfieldchoicesetByIDReply) {
    option (google.api.http) = {
      put: "/api/extras/customfieldchoicesets/{id}"
      body: "*"
    };
  }

  // Get a extrasCustomfieldchoiceset by id
  rpc GetByID(GetExtrasCustomfieldchoicesetByIDRequest) returns (GetExtrasCustomfieldchoicesetByIDReply) {
    option (google.api.http) = {
      get: "/api/extras/customfieldchoicesets/{id}"
    };
  }

  // Get a paginated list of extrasCustomfieldchoiceset by custom conditions
  rpc List(ListExtrasCustomfieldchoicesetRequest) returns (ListExtrasCustomfieldchoicesetReply) {
    option (google.api.http) = {
      post: "/api/extras/customfieldchoicesets/list"
      body: "*"
    };
  }

  // Batch delete extrasCustomfieldchoiceset by ids
  rpc DeleteByIDs(DeleteExtrasCustomfieldchoicesetByIDsRequest) returns (DeleteExtrasCustomfieldchoicesetByIDsReply) {
    option (google.api.http) = {
      post: "/api/extras/customfieldchoicesets/delete/ids"
      body: "*"
    };
  }

  // Get a extrasCustomfieldchoiceset by custom condition
  rpc GetByCondition(GetExtrasCustomfieldchoicesetByConditionRequest) returns (GetExtrasCustomfieldchoicesetByConditionReply) {
    option (google.api.http) = {
      post: "/api/extras/customfieldchoicesets/condition"
      body: "*"
    };
  }

  // Batch get extrasCustomfieldchoiceset by ids
  rpc ListByIDs(ListExtrasCustomfieldchoicesetByIDsRequest) returns (ListExtrasCustomfieldchoicesetByIDsReply) {
    option (google.api.http) = {
      post: "/api/extras/customfieldchoicesets/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of extrasCustomfieldchoiceset by last id
  rpc ListByLastID(ListExtrasCustomfieldchoicesetByLastIDRequest) returns (ListExtrasCustomfieldchoicesetByLastIDReply) {
    option (google.api.http) = {
      get: "/api/extras/customfieldchoicesets"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/extrasCustomfieldchoiceset/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getExtrasCustomfieldchoiceset?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateExtrasCustomfieldchoicesetRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string name = 3; 
	string description = 4; 
	string baseChoices = 5; 
	string extraChoices = 6; 
	bool orderAlphabetically = 7; 
}

message CreateExtrasCustomfieldchoicesetReply {
  uint64 id = 1;
}

message DeleteExtrasCustomfieldchoicesetByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteExtrasCustomfieldchoicesetByIDReply {

}

message UpdateExtrasCustomfieldchoicesetByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string created = 2; 
	string lastUpdated = 3; 
	string name = 4; 
	string description = 5; 
	string baseChoices = 6; 
	string extraChoices = 7; 
	bool orderAlphabetically = 8; 
}

message UpdateExtrasCustomfieldchoicesetByIDReply {

}

message ExtrasCustomfieldchoiceset {
	uint64 id = 1; 
	string created = 2; 
	string lastUpdated = 3; 
	string name = 4; 
	string description = 5; 
	string baseChoices = 6; 
	string extraChoices = 7; 
	bool orderAlphabetically = 8; 
}

message GetExtrasCustomfieldchoicesetByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetExtrasCustomfieldchoicesetByIDReply {
  ExtrasCustomfieldchoiceset extrasCustomfieldchoiceset = 1;
}

message ListExtrasCustomfieldchoicesetRequest {
  api.types.Params params = 1;
}

message ListExtrasCustomfieldchoicesetReply {
  int64 total = 1;
  repeated ExtrasCustomfieldchoiceset extrasCustomfieldchoicesets = 2;
}

message DeleteExtrasCustomfieldchoicesetByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteExtrasCustomfieldchoicesetByIDsReply {

}

message GetExtrasCustomfieldchoicesetByConditionRequest {
  types.Conditions conditions = 1;
}

message GetExtrasCustomfieldchoicesetByConditionReply {
  ExtrasCustomfieldchoiceset extrasCustomfieldchoiceset = 1;
}

message ListExtrasCustomfieldchoicesetByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListExtrasCustomfieldchoicesetByIDsReply {
  repeated ExtrasCustomfieldchoiceset extrasCustomfieldchoicesets = 1;
}

message ListExtrasCustomfieldchoicesetByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListExtrasCustomfieldchoicesetByLastIDReply {
  repeated ExtrasCustomfieldchoiceset extrasCustomfieldchoicesets = 1;
}


