syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service extrasConfigcontextPlatforms {
  // Create a new extrasConfigcontextPlatforms
  rpc Create(CreateExtrasConfigcontextPlatformsRequest) returns (CreateExtrasConfigcontextPlatformsReply) {
    option (google.api.http) = {
      post: "/api/extras/extrasConfigcontextPlatforms"
      body: "*"
    };
  }

  // Delete a extrasConfigcontextPlatforms by id
  rpc DeleteByID(DeleteExtrasConfigcontextPlatformsByIDRequest) returns (DeleteExtrasConfigcontextPlatformsByIDReply) {
    option (google.api.http) = {
      delete: "/api/extras/extrasConfigcontextPlatforms/{id}"
    };
  }

  // Update a extrasConfigcontextPlatforms by id
  rpc UpdateByID(UpdateExtrasConfigcontextPlatformsByIDRequest) returns (UpdateExtrasConfigcontextPlatformsByIDReply) {
    option (google.api.http) = {
      put: "/api/extras/extrasConfigcontextPlatforms/{id}"
      body: "*"
    };
  }

  // Get a extrasConfigcontextPlatforms by id
  rpc GetByID(GetExtrasConfigcontextPlatformsByIDRequest) returns (GetExtrasConfigcontextPlatformsByIDReply) {
    option (google.api.http) = {
      get: "/api/extras/extrasConfigcontextPlatforms/{id}"
    };
  }

  // Get a paginated list of extrasConfigcontextPlatforms by custom conditions
  rpc List(ListExtrasConfigcontextPlatformsRequest) returns (ListExtrasConfigcontextPlatformsReply) {
    option (google.api.http) = {
      post: "/api/extras/extrasConfigcontextPlatforms/list"
      body: "*"
    };
  }

  // Batch delete extrasConfigcontextPlatforms by ids
  rpc DeleteByIDs(DeleteExtrasConfigcontextPlatformsByIDsRequest) returns (DeleteExtrasConfigcontextPlatformsByIDsReply) {
    option (google.api.http) = {
      post: "/api/extras/extrasConfigcontextPlatforms/delete/ids"
      body: "*"
    };
  }

  // Get a extrasConfigcontextPlatforms by custom condition
  rpc GetByCondition(GetExtrasConfigcontextPlatformsByConditionRequest) returns (GetExtrasConfigcontextPlatformsByConditionReply) {
    option (google.api.http) = {
      post: "/api/extras/extrasConfigcontextPlatforms/condition"
      body: "*"
    };
  }

  // Batch get extrasConfigcontextPlatforms by ids
  rpc ListByIDs(ListExtrasConfigcontextPlatformsByIDsRequest) returns (ListExtrasConfigcontextPlatformsByIDsReply) {
    option (google.api.http) = {
      post: "/api/extras/extrasConfigcontextPlatforms/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of extrasConfigcontextPlatforms by last id
  rpc ListByLastID(ListExtrasConfigcontextPlatformsByLastIDRequest) returns (ListExtrasConfigcontextPlatformsByLastIDReply) {
    option (google.api.http) = {
      get: "/api/extras/extrasConfigcontextPlatforms"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/extrasConfigcontextPlatforms/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getExtrasConfigcontextPlatforms?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateExtrasConfigcontextPlatformsRequest {
	int64 configcontextID = 1; 
	int64 platformID = 2; 
}

message CreateExtrasConfigcontextPlatformsReply {
  uint64 id = 1;
}

message DeleteExtrasConfigcontextPlatformsByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteExtrasConfigcontextPlatformsByIDReply {

}

message UpdateExtrasConfigcontextPlatformsByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	int64 configcontextID = 2; 
	int64 platformID = 3; 
}

message UpdateExtrasConfigcontextPlatformsByIDReply {

}

message ExtrasConfigcontextPlatforms {
	uint64 id = 1; 
	int64 configcontextID = 2; 
	int64 platformID = 3; 
}

message GetExtrasConfigcontextPlatformsByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetExtrasConfigcontextPlatformsByIDReply {
  ExtrasConfigcontextPlatforms extrasConfigcontextPlatforms = 1;
}

message ListExtrasConfigcontextPlatformsRequest {
  api.types.Params params = 1;
}

message ListExtrasConfigcontextPlatformsReply {
  int64 total = 1;
  repeated ExtrasConfigcontextPlatforms extrasConfigcontextPlatformss = 2;
}

message DeleteExtrasConfigcontextPlatformsByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteExtrasConfigcontextPlatformsByIDsReply {

}

message GetExtrasConfigcontextPlatformsByConditionRequest {
  types.Conditions conditions = 1;
}

message GetExtrasConfigcontextPlatformsByConditionReply {
  ExtrasConfigcontextPlatforms extrasConfigcontextPlatforms = 1;
}

message ListExtrasConfigcontextPlatformsByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListExtrasConfigcontextPlatformsByIDsReply {
  repeated ExtrasConfigcontextPlatforms extrasConfigcontextPlatformss = 1;
}

message ListExtrasConfigcontextPlatformsByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListExtrasConfigcontextPlatformsByLastIDReply {
  repeated ExtrasConfigcontextPlatforms extrasConfigcontextPlatformss = 1;
}


