// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type ExtrasTagObjectTypesLogicer interface {
	Create(ctx context.Context, req *CreateExtrasTagObjectTypesRequest) (*CreateExtrasTagObjectTypesReply, error)
	DeleteByID(ctx context.Context, req *DeleteExtrasTagObjectTypesByIDRequest) (*DeleteExtrasTagObjectTypesByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateExtrasTagObjectTypesByIDRequest) (*UpdateExtrasTagObjectTypesByIDReply, error)
	GetByID(ctx context.Context, req *GetExtrasTagObjectTypesByIDRequest) (*GetExtrasTagObjectTypesByIDReply, error)
	List(ctx context.Context, req *ListExtrasTagObjectTypesRequest) (*ListExtrasTagObjectTypesReply, error)
	DeleteByIDs(ctx context.Context, req *DeleteExtrasTagObjectTypesByIDsRequest) (*DeleteExtrasTagObjectTypesByIDsReply, error)
	GetByCondition(ctx context.Context, req *GetExtrasTagObjectTypesByConditionRequest) (*GetExtrasTagObjectTypesByConditionReply, error)
	ListByIDs(ctx context.Context, req *ListExtrasTagObjectTypesByIDsRequest) (*ListExtrasTagObjectTypesByIDsReply, error)
	ListByLastID(ctx context.Context, req *ListExtrasTagObjectTypesByLastIDRequest) (*ListExtrasTagObjectTypesByLastIDReply, error)
}

type ExtrasTagObjectTypesOption func(*extrasTagObjectTypesOptions)

type extrasTagObjectTypesOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *extrasTagObjectTypesOptions) apply(opts ...ExtrasTagObjectTypesOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithExtrasTagObjectTypesHTTPResponse() ExtrasTagObjectTypesOption {
	return func(o *extrasTagObjectTypesOptions) {
		o.isFromRPC = false
	}
}

func WithExtrasTagObjectTypesRPCResponse() ExtrasTagObjectTypesOption {
	return func(o *extrasTagObjectTypesOptions) {
		o.isFromRPC = true
	}
}

func WithExtrasTagObjectTypesResponser(responser errcode.Responser) ExtrasTagObjectTypesOption {
	return func(o *extrasTagObjectTypesOptions) {
		o.responser = responser
	}
}

func WithExtrasTagObjectTypesLogger(zapLog *zap.Logger) ExtrasTagObjectTypesOption {
	return func(o *extrasTagObjectTypesOptions) {
		o.zapLog = zapLog
	}
}

func WithExtrasTagObjectTypesErrorToHTTPCode(e ...*errcode.Error) ExtrasTagObjectTypesOption {
	return func(o *extrasTagObjectTypesOptions) {
		o.httpErrors = e
	}
}

func WithExtrasTagObjectTypesRPCStatusToHTTPCode(s ...*errcode.RPCStatus) ExtrasTagObjectTypesOption {
	return func(o *extrasTagObjectTypesOptions) {
		o.rpcStatus = s
	}
}

func WithExtrasTagObjectTypesWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) ExtrasTagObjectTypesOption {
	return func(o *extrasTagObjectTypesOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterExtrasTagObjectTypesRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic ExtrasTagObjectTypesLogicer,
	opts ...ExtrasTagObjectTypesOption) {

	o := &extrasTagObjectTypesOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &extrasTagObjectTypesRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type extrasTagObjectTypesRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                ExtrasTagObjectTypesLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *extrasTagObjectTypesRouter) register() {
	r.iRouter.Handle("POST", "/api/extras/extrasTagObjectTypes", r.withMiddleware("POST", "/api/extras/extrasTagObjectTypes", r.Create_230)...)
	r.iRouter.Handle("DELETE", "/api/extras/extrasTagObjectTypes/:id", r.withMiddleware("DELETE", "/api/extras/extrasTagObjectTypes/:id", r.DeleteByID_226)...)
	r.iRouter.Handle("PUT", "/api/extras/extrasTagObjectTypes/:id", r.withMiddleware("PUT", "/api/extras/extrasTagObjectTypes/:id", r.UpdateByID_226)...)
	r.iRouter.Handle("GET", "/api/extras/extrasTagObjectTypes/:id", r.withMiddleware("GET", "/api/extras/extrasTagObjectTypes/:id", r.GetByID_226)...)
	r.iRouter.Handle("POST", "/api/extras/extrasTagObjectTypes/list", r.withMiddleware("POST", "/api/extras/extrasTagObjectTypes/list", r.List_230)...)
	r.iRouter.Handle("POST", "/api/extras/extrasTagObjectTypes/delete/ids", r.withMiddleware("POST", "/api/extras/extrasTagObjectTypes/delete/ids", r.DeleteByIDs_226)...)
	r.iRouter.Handle("POST", "/api/extras/extrasTagObjectTypes/condition", r.withMiddleware("POST", "/api/extras/extrasTagObjectTypes/condition", r.GetByCondition_230)...)
	r.iRouter.Handle("POST", "/api/extras/extrasTagObjectTypes/list/ids", r.withMiddleware("POST", "/api/extras/extrasTagObjectTypes/list/ids", r.ListByIDs_226)...)
	r.iRouter.Handle("GET", "/api/extras/extrasTagObjectTypes", r.withMiddleware("GET", "/api/extras/extrasTagObjectTypes", r.ListByLastID_226)...)

}

func (r *extrasTagObjectTypesRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *extrasTagObjectTypesRouter) Create_230(c *gin.Context) {
	req := &CreateExtrasTagObjectTypesRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *extrasTagObjectTypesRouter) DeleteByID_226(c *gin.Context) {
	req := &DeleteExtrasTagObjectTypesByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *extrasTagObjectTypesRouter) UpdateByID_226(c *gin.Context) {
	req := &UpdateExtrasTagObjectTypesByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *extrasTagObjectTypesRouter) GetByID_226(c *gin.Context) {
	req := &GetExtrasTagObjectTypesByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *extrasTagObjectTypesRouter) List_230(c *gin.Context) {
	req := &ListExtrasTagObjectTypesRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *extrasTagObjectTypesRouter) DeleteByIDs_226(c *gin.Context) {
	req := &DeleteExtrasTagObjectTypesByIDsRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByIDs(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *extrasTagObjectTypesRouter) GetByCondition_230(c *gin.Context) {
	req := &GetExtrasTagObjectTypesByConditionRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByCondition(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *extrasTagObjectTypesRouter) ListByIDs_226(c *gin.Context) {
	req := &ListExtrasTagObjectTypesByIDsRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.ListByIDs(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *extrasTagObjectTypesRouter) ListByLastID_226(c *gin.Context) {
	req := &ListExtrasTagObjectTypesByLastIDRequest{}
	var err error

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.ListByLastID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
