syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service extrasConfigcontextRoles {
  // Create a new extrasConfigcontextRoles
  rpc Create(CreateExtrasConfigcontextRolesRequest) returns (CreateExtrasConfigcontextRolesReply) {
    option (google.api.http) = {
      post: "/api/extras/extrasConfigcontextRoles"
      body: "*"
    };
  }

  // Delete a extrasConfigcontextRoles by id
  rpc DeleteByID(DeleteExtrasConfigcontextRolesByIDRequest) returns (DeleteExtrasConfigcontextRolesByIDReply) {
    option (google.api.http) = {
      delete: "/api/extras/extrasConfigcontextRoles/{id}"
    };
  }

  // Update a extrasConfigcontextRoles by id
  rpc UpdateByID(UpdateExtrasConfigcontextRolesByIDRequest) returns (UpdateExtrasConfigcontextRolesByIDReply) {
    option (google.api.http) = {
      put: "/api/extras/extrasConfigcontextRoles/{id}"
      body: "*"
    };
  }

  // Get a extrasConfigcontextRoles by id
  rpc GetByID(GetExtrasConfigcontextRolesByIDRequest) returns (GetExtrasConfigcontextRolesByIDReply) {
    option (google.api.http) = {
      get: "/api/extras/extrasConfigcontextRoles/{id}"
    };
  }

  // Get a paginated list of extrasConfigcontextRoles by custom conditions
  rpc List(ListExtrasConfigcontextRolesRequest) returns (ListExtrasConfigcontextRolesReply) {
    option (google.api.http) = {
      post: "/api/extras/extrasConfigcontextRoles/list"
      body: "*"
    };
  }

  // Batch delete extrasConfigcontextRoles by ids
  rpc DeleteByIDs(DeleteExtrasConfigcontextRolesByIDsRequest) returns (DeleteExtrasConfigcontextRolesByIDsReply) {
    option (google.api.http) = {
      post: "/api/extras/extrasConfigcontextRoles/delete/ids"
      body: "*"
    };
  }

  // Get a extrasConfigcontextRoles by custom condition
  rpc GetByCondition(GetExtrasConfigcontextRolesByConditionRequest) returns (GetExtrasConfigcontextRolesByConditionReply) {
    option (google.api.http) = {
      post: "/api/extras/extrasConfigcontextRoles/condition"
      body: "*"
    };
  }

  // Batch get extrasConfigcontextRoles by ids
  rpc ListByIDs(ListExtrasConfigcontextRolesByIDsRequest) returns (ListExtrasConfigcontextRolesByIDsReply) {
    option (google.api.http) = {
      post: "/api/extras/extrasConfigcontextRoles/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of extrasConfigcontextRoles by last id
  rpc ListByLastID(ListExtrasConfigcontextRolesByLastIDRequest) returns (ListExtrasConfigcontextRolesByLastIDReply) {
    option (google.api.http) = {
      get: "/api/extras/extrasConfigcontextRoles"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/extrasConfigcontextRoles/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getExtrasConfigcontextRoles?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateExtrasConfigcontextRolesRequest {
	int64 configcontextID = 1; 
	int64 deviceroleID = 2; 
}

message CreateExtrasConfigcontextRolesReply {
  uint64 id = 1;
}

message DeleteExtrasConfigcontextRolesByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteExtrasConfigcontextRolesByIDReply {

}

message UpdateExtrasConfigcontextRolesByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	int64 configcontextID = 2; 
	int64 deviceroleID = 3; 
}

message UpdateExtrasConfigcontextRolesByIDReply {

}

message ExtrasConfigcontextRoles {
	uint64 id = 1; 
	int64 configcontextID = 2; 
	int64 deviceroleID = 3; 
}

message GetExtrasConfigcontextRolesByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetExtrasConfigcontextRolesByIDReply {
  ExtrasConfigcontextRoles extrasConfigcontextRoles = 1;
}

message ListExtrasConfigcontextRolesRequest {
  api.types.Params params = 1;
}

message ListExtrasConfigcontextRolesReply {
  int64 total = 1;
  repeated ExtrasConfigcontextRoles extrasConfigcontextRoless = 2;
}

message DeleteExtrasConfigcontextRolesByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteExtrasConfigcontextRolesByIDsReply {

}

message GetExtrasConfigcontextRolesByConditionRequest {
  types.Conditions conditions = 1;
}

message GetExtrasConfigcontextRolesByConditionReply {
  ExtrasConfigcontextRoles extrasConfigcontextRoles = 1;
}

message ListExtrasConfigcontextRolesByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListExtrasConfigcontextRolesByIDsReply {
  repeated ExtrasConfigcontextRoles extrasConfigcontextRoless = 1;
}

message ListExtrasConfigcontextRolesByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListExtrasConfigcontextRolesByLastIDReply {
  repeated ExtrasConfigcontextRoles extrasConfigcontextRoless = 1;
}


