syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service extrasDashboard {
  // Create a new extrasDashboard
  rpc Create(CreateExtrasDashboardRequest) returns (CreateExtrasDashboardReply) {
    option (google.api.http) = {
      post: "/api/extras/dashboards"
      body: "*"
    };
  }

  // Delete a extrasDashboard by id
  rpc DeleteByID(DeleteExtrasDashboardByIDRequest) returns (DeleteExtrasDashboardByIDReply) {
    option (google.api.http) = {
      delete: "/api/extras/dashboards/{id}"
    };
  }

  // Update a extrasDashboard by id
  rpc UpdateByID(UpdateExtrasDashboardByIDRequest) returns (UpdateExtrasDashboardByIDReply) {
    option (google.api.http) = {
      put: "/api/extras/dashboards/{id}"
      body: "*"
    };
  }

  // Get a extrasDashboard by id
  rpc GetByID(GetExtrasDashboardByIDRequest) returns (GetExtrasDashboardByIDReply) {
    option (google.api.http) = {
      get: "/api/extras/dashboards/{id}"
    };
  }

  // Get a paginated list of extrasDashboard by custom conditions
  rpc List(ListExtrasDashboardRequest) returns (ListExtrasDashboardReply) {
    option (google.api.http) = {
      post: "/api/extras/dashboards/list"
      body: "*"
    };
  }

  // Batch delete extrasDashboard by ids
  rpc DeleteByIDs(DeleteExtrasDashboardByIDsRequest) returns (DeleteExtrasDashboardByIDsReply) {
    option (google.api.http) = {
      post: "/api/extras/dashboards/delete/ids"
      body: "*"
    };
  }

  // Get a extrasDashboard by custom condition
  rpc GetByCondition(GetExtrasDashboardByConditionRequest) returns (GetExtrasDashboardByConditionReply) {
    option (google.api.http) = {
      post: "/api/extras/dashboards/condition"
      body: "*"
    };
  }

  // Batch get extrasDashboard by ids
  rpc ListByIDs(ListExtrasDashboardByIDsRequest) returns (ListExtrasDashboardByIDsReply) {
    option (google.api.http) = {
      post: "/api/extras/dashboards/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of extrasDashboard by last id
  rpc ListByLastID(ListExtrasDashboardByLastIDRequest) returns (ListExtrasDashboardByLastIDReply) {
    option (google.api.http) = {
      get: "/api/extras/dashboards"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/extrasDashboard/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getExtrasDashboard?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateExtrasDashboardRequest {
	string layout = 1; 
	string config = 2; 
	int64 userID = 3; 
}

message CreateExtrasDashboardReply {
  uint64 id = 1;
}

message DeleteExtrasDashboardByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteExtrasDashboardByIDReply {

}

message UpdateExtrasDashboardByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string layout = 2; 
	string config = 3; 
	int64 userID = 4; 
}

message UpdateExtrasDashboardByIDReply {

}

message ExtrasDashboard {
	uint64 id = 1; 
	string layout = 2; 
	string config = 3; 
	int64 userID = 4; 
}

message GetExtrasDashboardByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetExtrasDashboardByIDReply {
  ExtrasDashboard extrasDashboard = 1;
}

message ListExtrasDashboardRequest {
  api.types.Params params = 1;
}

message ListExtrasDashboardReply {
  int64 total = 1;
  repeated ExtrasDashboard extrasDashboards = 2;
}

message DeleteExtrasDashboardByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteExtrasDashboardByIDsReply {

}

message GetExtrasDashboardByConditionRequest {
  types.Conditions conditions = 1;
}

message GetExtrasDashboardByConditionReply {
  ExtrasDashboard extrasDashboard = 1;
}

message ListExtrasDashboardByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListExtrasDashboardByIDsReply {
  repeated ExtrasDashboard extrasDashboards = 1;
}

message ListExtrasDashboardByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListExtrasDashboardByLastIDReply {
  repeated ExtrasDashboard extrasDashboards = 1;
}


