// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/netbox_go/v1/ipamVlangroup.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateIpamVlangroupRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateIpamVlangroupRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateIpamVlangroupRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateIpamVlangroupRequestMultiError, or nil if none found.
func (m *CreateIpamVlangroupRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateIpamVlangroupRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Created

	// no validation rules for LastUpdated

	// no validation rules for CustomFieldData

	// no validation rules for Name

	// no validation rules for Slug

	// no validation rules for ScopeID

	// no validation rules for Description

	// no validation rules for ScopeTypeID

	// no validation rules for VidRanges

	// no validation rules for XTotalVlanIds

	// no validation rules for TenantID

	if len(errors) > 0 {
		return CreateIpamVlangroupRequestMultiError(errors)
	}

	return nil
}

// CreateIpamVlangroupRequestMultiError is an error wrapping multiple
// validation errors returned by CreateIpamVlangroupRequest.ValidateAll() if
// the designated constraints aren't met.
type CreateIpamVlangroupRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateIpamVlangroupRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateIpamVlangroupRequestMultiError) AllErrors() []error { return m }

// CreateIpamVlangroupRequestValidationError is the validation error returned
// by CreateIpamVlangroupRequest.Validate if the designated constraints aren't met.
type CreateIpamVlangroupRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateIpamVlangroupRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateIpamVlangroupRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateIpamVlangroupRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateIpamVlangroupRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateIpamVlangroupRequestValidationError) ErrorName() string {
	return "CreateIpamVlangroupRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateIpamVlangroupRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateIpamVlangroupRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateIpamVlangroupRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateIpamVlangroupRequestValidationError{}

// Validate checks the field values on CreateIpamVlangroupReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateIpamVlangroupReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateIpamVlangroupReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateIpamVlangroupReplyMultiError, or nil if none found.
func (m *CreateIpamVlangroupReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateIpamVlangroupReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateIpamVlangroupReplyMultiError(errors)
	}

	return nil
}

// CreateIpamVlangroupReplyMultiError is an error wrapping multiple validation
// errors returned by CreateIpamVlangroupReply.ValidateAll() if the designated
// constraints aren't met.
type CreateIpamVlangroupReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateIpamVlangroupReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateIpamVlangroupReplyMultiError) AllErrors() []error { return m }

// CreateIpamVlangroupReplyValidationError is the validation error returned by
// CreateIpamVlangroupReply.Validate if the designated constraints aren't met.
type CreateIpamVlangroupReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateIpamVlangroupReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateIpamVlangroupReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateIpamVlangroupReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateIpamVlangroupReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateIpamVlangroupReplyValidationError) ErrorName() string {
	return "CreateIpamVlangroupReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateIpamVlangroupReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateIpamVlangroupReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateIpamVlangroupReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateIpamVlangroupReplyValidationError{}

// Validate checks the field values on DeleteIpamVlangroupByIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteIpamVlangroupByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteIpamVlangroupByIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteIpamVlangroupByIDRequestMultiError, or nil if none found.
func (m *DeleteIpamVlangroupByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteIpamVlangroupByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := DeleteIpamVlangroupByIDRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteIpamVlangroupByIDRequestMultiError(errors)
	}

	return nil
}

// DeleteIpamVlangroupByIDRequestMultiError is an error wrapping multiple
// validation errors returned by DeleteIpamVlangroupByIDRequest.ValidateAll()
// if the designated constraints aren't met.
type DeleteIpamVlangroupByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteIpamVlangroupByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteIpamVlangroupByIDRequestMultiError) AllErrors() []error { return m }

// DeleteIpamVlangroupByIDRequestValidationError is the validation error
// returned by DeleteIpamVlangroupByIDRequest.Validate if the designated
// constraints aren't met.
type DeleteIpamVlangroupByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteIpamVlangroupByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteIpamVlangroupByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteIpamVlangroupByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteIpamVlangroupByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteIpamVlangroupByIDRequestValidationError) ErrorName() string {
	return "DeleteIpamVlangroupByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteIpamVlangroupByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteIpamVlangroupByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteIpamVlangroupByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteIpamVlangroupByIDRequestValidationError{}

// Validate checks the field values on DeleteIpamVlangroupByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteIpamVlangroupByIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteIpamVlangroupByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteIpamVlangroupByIDReplyMultiError, or nil if none found.
func (m *DeleteIpamVlangroupByIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteIpamVlangroupByIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteIpamVlangroupByIDReplyMultiError(errors)
	}

	return nil
}

// DeleteIpamVlangroupByIDReplyMultiError is an error wrapping multiple
// validation errors returned by DeleteIpamVlangroupByIDReply.ValidateAll() if
// the designated constraints aren't met.
type DeleteIpamVlangroupByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteIpamVlangroupByIDReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteIpamVlangroupByIDReplyMultiError) AllErrors() []error { return m }

// DeleteIpamVlangroupByIDReplyValidationError is the validation error returned
// by DeleteIpamVlangroupByIDReply.Validate if the designated constraints
// aren't met.
type DeleteIpamVlangroupByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteIpamVlangroupByIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteIpamVlangroupByIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteIpamVlangroupByIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteIpamVlangroupByIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteIpamVlangroupByIDReplyValidationError) ErrorName() string {
	return "DeleteIpamVlangroupByIDReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteIpamVlangroupByIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteIpamVlangroupByIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteIpamVlangroupByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteIpamVlangroupByIDReplyValidationError{}

// Validate checks the field values on UpdateIpamVlangroupByIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateIpamVlangroupByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateIpamVlangroupByIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateIpamVlangroupByIDRequestMultiError, or nil if none found.
func (m *UpdateIpamVlangroupByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateIpamVlangroupByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Created

	// no validation rules for LastUpdated

	// no validation rules for CustomFieldData

	if m.GetId() <= 0 {
		err := UpdateIpamVlangroupByIDRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Name

	// no validation rules for Slug

	// no validation rules for ScopeID

	// no validation rules for Description

	// no validation rules for ScopeTypeID

	// no validation rules for VidRanges

	// no validation rules for XTotalVlanIds

	// no validation rules for TenantID

	if len(errors) > 0 {
		return UpdateIpamVlangroupByIDRequestMultiError(errors)
	}

	return nil
}

// UpdateIpamVlangroupByIDRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateIpamVlangroupByIDRequest.ValidateAll()
// if the designated constraints aren't met.
type UpdateIpamVlangroupByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateIpamVlangroupByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateIpamVlangroupByIDRequestMultiError) AllErrors() []error { return m }

// UpdateIpamVlangroupByIDRequestValidationError is the validation error
// returned by UpdateIpamVlangroupByIDRequest.Validate if the designated
// constraints aren't met.
type UpdateIpamVlangroupByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateIpamVlangroupByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateIpamVlangroupByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateIpamVlangroupByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateIpamVlangroupByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateIpamVlangroupByIDRequestValidationError) ErrorName() string {
	return "UpdateIpamVlangroupByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateIpamVlangroupByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateIpamVlangroupByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateIpamVlangroupByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateIpamVlangroupByIDRequestValidationError{}

// Validate checks the field values on UpdateIpamVlangroupByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateIpamVlangroupByIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateIpamVlangroupByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateIpamVlangroupByIDReplyMultiError, or nil if none found.
func (m *UpdateIpamVlangroupByIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateIpamVlangroupByIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateIpamVlangroupByIDReplyMultiError(errors)
	}

	return nil
}

// UpdateIpamVlangroupByIDReplyMultiError is an error wrapping multiple
// validation errors returned by UpdateIpamVlangroupByIDReply.ValidateAll() if
// the designated constraints aren't met.
type UpdateIpamVlangroupByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateIpamVlangroupByIDReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateIpamVlangroupByIDReplyMultiError) AllErrors() []error { return m }

// UpdateIpamVlangroupByIDReplyValidationError is the validation error returned
// by UpdateIpamVlangroupByIDReply.Validate if the designated constraints
// aren't met.
type UpdateIpamVlangroupByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateIpamVlangroupByIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateIpamVlangroupByIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateIpamVlangroupByIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateIpamVlangroupByIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateIpamVlangroupByIDReplyValidationError) ErrorName() string {
	return "UpdateIpamVlangroupByIDReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateIpamVlangroupByIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateIpamVlangroupByIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateIpamVlangroupByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateIpamVlangroupByIDReplyValidationError{}

// Validate checks the field values on IpamVlangroup with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IpamVlangroup) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IpamVlangroup with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IpamVlangroupMultiError, or
// nil if none found.
func (m *IpamVlangroup) ValidateAll() error {
	return m.validate(true)
}

func (m *IpamVlangroup) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Created

	// no validation rules for LastUpdated

	// no validation rules for CustomFieldData

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Slug

	// no validation rules for ScopeID

	// no validation rules for Description

	// no validation rules for ScopeTypeID

	// no validation rules for VidRanges

	// no validation rules for XTotalVlanIds

	// no validation rules for TenantID

	if len(errors) > 0 {
		return IpamVlangroupMultiError(errors)
	}

	return nil
}

// IpamVlangroupMultiError is an error wrapping multiple validation errors
// returned by IpamVlangroup.ValidateAll() if the designated constraints
// aren't met.
type IpamVlangroupMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IpamVlangroupMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IpamVlangroupMultiError) AllErrors() []error { return m }

// IpamVlangroupValidationError is the validation error returned by
// IpamVlangroup.Validate if the designated constraints aren't met.
type IpamVlangroupValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IpamVlangroupValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IpamVlangroupValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IpamVlangroupValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IpamVlangroupValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IpamVlangroupValidationError) ErrorName() string { return "IpamVlangroupValidationError" }

// Error satisfies the builtin error interface
func (e IpamVlangroupValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIpamVlangroup.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IpamVlangroupValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IpamVlangroupValidationError{}

// Validate checks the field values on GetIpamVlangroupByIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetIpamVlangroupByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIpamVlangroupByIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIpamVlangroupByIDRequestMultiError, or nil if none found.
func (m *GetIpamVlangroupByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIpamVlangroupByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := GetIpamVlangroupByIDRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetIpamVlangroupByIDRequestMultiError(errors)
	}

	return nil
}

// GetIpamVlangroupByIDRequestMultiError is an error wrapping multiple
// validation errors returned by GetIpamVlangroupByIDRequest.ValidateAll() if
// the designated constraints aren't met.
type GetIpamVlangroupByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIpamVlangroupByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIpamVlangroupByIDRequestMultiError) AllErrors() []error { return m }

// GetIpamVlangroupByIDRequestValidationError is the validation error returned
// by GetIpamVlangroupByIDRequest.Validate if the designated constraints
// aren't met.
type GetIpamVlangroupByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIpamVlangroupByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIpamVlangroupByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIpamVlangroupByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIpamVlangroupByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIpamVlangroupByIDRequestValidationError) ErrorName() string {
	return "GetIpamVlangroupByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetIpamVlangroupByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIpamVlangroupByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIpamVlangroupByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIpamVlangroupByIDRequestValidationError{}

// Validate checks the field values on GetIpamVlangroupByIDReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetIpamVlangroupByIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIpamVlangroupByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIpamVlangroupByIDReplyMultiError, or nil if none found.
func (m *GetIpamVlangroupByIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIpamVlangroupByIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIpamVlangroup()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetIpamVlangroupByIDReplyValidationError{
					field:  "IpamVlangroup",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetIpamVlangroupByIDReplyValidationError{
					field:  "IpamVlangroup",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIpamVlangroup()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetIpamVlangroupByIDReplyValidationError{
				field:  "IpamVlangroup",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetIpamVlangroupByIDReplyMultiError(errors)
	}

	return nil
}

// GetIpamVlangroupByIDReplyMultiError is an error wrapping multiple validation
// errors returned by GetIpamVlangroupByIDReply.ValidateAll() if the
// designated constraints aren't met.
type GetIpamVlangroupByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIpamVlangroupByIDReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIpamVlangroupByIDReplyMultiError) AllErrors() []error { return m }

// GetIpamVlangroupByIDReplyValidationError is the validation error returned by
// GetIpamVlangroupByIDReply.Validate if the designated constraints aren't met.
type GetIpamVlangroupByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIpamVlangroupByIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIpamVlangroupByIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIpamVlangroupByIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIpamVlangroupByIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIpamVlangroupByIDReplyValidationError) ErrorName() string {
	return "GetIpamVlangroupByIDReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetIpamVlangroupByIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIpamVlangroupByIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIpamVlangroupByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIpamVlangroupByIDReplyValidationError{}

// Validate checks the field values on ListIpamVlangroupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIpamVlangroupRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIpamVlangroupRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIpamVlangroupRequestMultiError, or nil if none found.
func (m *ListIpamVlangroupRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIpamVlangroupRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetParams()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListIpamVlangroupRequestValidationError{
					field:  "Params",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListIpamVlangroupRequestValidationError{
					field:  "Params",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetParams()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListIpamVlangroupRequestValidationError{
				field:  "Params",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListIpamVlangroupRequestMultiError(errors)
	}

	return nil
}

// ListIpamVlangroupRequestMultiError is an error wrapping multiple validation
// errors returned by ListIpamVlangroupRequest.ValidateAll() if the designated
// constraints aren't met.
type ListIpamVlangroupRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIpamVlangroupRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIpamVlangroupRequestMultiError) AllErrors() []error { return m }

// ListIpamVlangroupRequestValidationError is the validation error returned by
// ListIpamVlangroupRequest.Validate if the designated constraints aren't met.
type ListIpamVlangroupRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIpamVlangroupRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIpamVlangroupRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIpamVlangroupRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIpamVlangroupRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIpamVlangroupRequestValidationError) ErrorName() string {
	return "ListIpamVlangroupRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListIpamVlangroupRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIpamVlangroupRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIpamVlangroupRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIpamVlangroupRequestValidationError{}

// Validate checks the field values on ListIpamVlangroupReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIpamVlangroupReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIpamVlangroupReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIpamVlangroupReplyMultiError, or nil if none found.
func (m *ListIpamVlangroupReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIpamVlangroupReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetIpamVlangroups() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListIpamVlangroupReplyValidationError{
						field:  fmt.Sprintf("IpamVlangroups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListIpamVlangroupReplyValidationError{
						field:  fmt.Sprintf("IpamVlangroups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListIpamVlangroupReplyValidationError{
					field:  fmt.Sprintf("IpamVlangroups[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListIpamVlangroupReplyMultiError(errors)
	}

	return nil
}

// ListIpamVlangroupReplyMultiError is an error wrapping multiple validation
// errors returned by ListIpamVlangroupReply.ValidateAll() if the designated
// constraints aren't met.
type ListIpamVlangroupReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIpamVlangroupReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIpamVlangroupReplyMultiError) AllErrors() []error { return m }

// ListIpamVlangroupReplyValidationError is the validation error returned by
// ListIpamVlangroupReply.Validate if the designated constraints aren't met.
type ListIpamVlangroupReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIpamVlangroupReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIpamVlangroupReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIpamVlangroupReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIpamVlangroupReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIpamVlangroupReplyValidationError) ErrorName() string {
	return "ListIpamVlangroupReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListIpamVlangroupReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIpamVlangroupReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIpamVlangroupReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIpamVlangroupReplyValidationError{}

// Validate checks the field values on DeleteIpamVlangroupByIDsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteIpamVlangroupByIDsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteIpamVlangroupByIDsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteIpamVlangroupByIDsRequestMultiError, or nil if none found.
func (m *DeleteIpamVlangroupByIDsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteIpamVlangroupByIDsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetIds()) < 1 {
		err := DeleteIpamVlangroupByIDsRequestValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteIpamVlangroupByIDsRequestMultiError(errors)
	}

	return nil
}

// DeleteIpamVlangroupByIDsRequestMultiError is an error wrapping multiple
// validation errors returned by DeleteIpamVlangroupByIDsRequest.ValidateAll()
// if the designated constraints aren't met.
type DeleteIpamVlangroupByIDsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteIpamVlangroupByIDsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteIpamVlangroupByIDsRequestMultiError) AllErrors() []error { return m }

// DeleteIpamVlangroupByIDsRequestValidationError is the validation error
// returned by DeleteIpamVlangroupByIDsRequest.Validate if the designated
// constraints aren't met.
type DeleteIpamVlangroupByIDsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteIpamVlangroupByIDsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteIpamVlangroupByIDsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteIpamVlangroupByIDsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteIpamVlangroupByIDsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteIpamVlangroupByIDsRequestValidationError) ErrorName() string {
	return "DeleteIpamVlangroupByIDsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteIpamVlangroupByIDsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteIpamVlangroupByIDsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteIpamVlangroupByIDsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteIpamVlangroupByIDsRequestValidationError{}

// Validate checks the field values on DeleteIpamVlangroupByIDsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteIpamVlangroupByIDsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteIpamVlangroupByIDsReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteIpamVlangroupByIDsReplyMultiError, or nil if none found.
func (m *DeleteIpamVlangroupByIDsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteIpamVlangroupByIDsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteIpamVlangroupByIDsReplyMultiError(errors)
	}

	return nil
}

// DeleteIpamVlangroupByIDsReplyMultiError is an error wrapping multiple
// validation errors returned by DeleteIpamVlangroupByIDsReply.ValidateAll()
// if the designated constraints aren't met.
type DeleteIpamVlangroupByIDsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteIpamVlangroupByIDsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteIpamVlangroupByIDsReplyMultiError) AllErrors() []error { return m }

// DeleteIpamVlangroupByIDsReplyValidationError is the validation error
// returned by DeleteIpamVlangroupByIDsReply.Validate if the designated
// constraints aren't met.
type DeleteIpamVlangroupByIDsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteIpamVlangroupByIDsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteIpamVlangroupByIDsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteIpamVlangroupByIDsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteIpamVlangroupByIDsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteIpamVlangroupByIDsReplyValidationError) ErrorName() string {
	return "DeleteIpamVlangroupByIDsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteIpamVlangroupByIDsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteIpamVlangroupByIDsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteIpamVlangroupByIDsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteIpamVlangroupByIDsReplyValidationError{}

// Validate checks the field values on GetIpamVlangroupByConditionRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetIpamVlangroupByConditionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIpamVlangroupByConditionRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetIpamVlangroupByConditionRequestMultiError, or nil if none found.
func (m *GetIpamVlangroupByConditionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIpamVlangroupByConditionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConditions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetIpamVlangroupByConditionRequestValidationError{
					field:  "Conditions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetIpamVlangroupByConditionRequestValidationError{
					field:  "Conditions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConditions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetIpamVlangroupByConditionRequestValidationError{
				field:  "Conditions",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetIpamVlangroupByConditionRequestMultiError(errors)
	}

	return nil
}

// GetIpamVlangroupByConditionRequestMultiError is an error wrapping multiple
// validation errors returned by
// GetIpamVlangroupByConditionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetIpamVlangroupByConditionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIpamVlangroupByConditionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIpamVlangroupByConditionRequestMultiError) AllErrors() []error { return m }

// GetIpamVlangroupByConditionRequestValidationError is the validation error
// returned by GetIpamVlangroupByConditionRequest.Validate if the designated
// constraints aren't met.
type GetIpamVlangroupByConditionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIpamVlangroupByConditionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIpamVlangroupByConditionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIpamVlangroupByConditionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIpamVlangroupByConditionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIpamVlangroupByConditionRequestValidationError) ErrorName() string {
	return "GetIpamVlangroupByConditionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetIpamVlangroupByConditionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIpamVlangroupByConditionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIpamVlangroupByConditionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIpamVlangroupByConditionRequestValidationError{}

// Validate checks the field values on GetIpamVlangroupByConditionReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetIpamVlangroupByConditionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIpamVlangroupByConditionReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetIpamVlangroupByConditionReplyMultiError, or nil if none found.
func (m *GetIpamVlangroupByConditionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIpamVlangroupByConditionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIpamVlangroup()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetIpamVlangroupByConditionReplyValidationError{
					field:  "IpamVlangroup",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetIpamVlangroupByConditionReplyValidationError{
					field:  "IpamVlangroup",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIpamVlangroup()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetIpamVlangroupByConditionReplyValidationError{
				field:  "IpamVlangroup",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetIpamVlangroupByConditionReplyMultiError(errors)
	}

	return nil
}

// GetIpamVlangroupByConditionReplyMultiError is an error wrapping multiple
// validation errors returned by
// GetIpamVlangroupByConditionReply.ValidateAll() if the designated
// constraints aren't met.
type GetIpamVlangroupByConditionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIpamVlangroupByConditionReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIpamVlangroupByConditionReplyMultiError) AllErrors() []error { return m }

// GetIpamVlangroupByConditionReplyValidationError is the validation error
// returned by GetIpamVlangroupByConditionReply.Validate if the designated
// constraints aren't met.
type GetIpamVlangroupByConditionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIpamVlangroupByConditionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIpamVlangroupByConditionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIpamVlangroupByConditionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIpamVlangroupByConditionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIpamVlangroupByConditionReplyValidationError) ErrorName() string {
	return "GetIpamVlangroupByConditionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetIpamVlangroupByConditionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIpamVlangroupByConditionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIpamVlangroupByConditionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIpamVlangroupByConditionReplyValidationError{}

// Validate checks the field values on ListIpamVlangroupByIDsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIpamVlangroupByIDsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIpamVlangroupByIDsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListIpamVlangroupByIDsRequestMultiError, or nil if none found.
func (m *ListIpamVlangroupByIDsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIpamVlangroupByIDsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetIds()) < 1 {
		err := ListIpamVlangroupByIDsRequestValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListIpamVlangroupByIDsRequestMultiError(errors)
	}

	return nil
}

// ListIpamVlangroupByIDsRequestMultiError is an error wrapping multiple
// validation errors returned by ListIpamVlangroupByIDsRequest.ValidateAll()
// if the designated constraints aren't met.
type ListIpamVlangroupByIDsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIpamVlangroupByIDsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIpamVlangroupByIDsRequestMultiError) AllErrors() []error { return m }

// ListIpamVlangroupByIDsRequestValidationError is the validation error
// returned by ListIpamVlangroupByIDsRequest.Validate if the designated
// constraints aren't met.
type ListIpamVlangroupByIDsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIpamVlangroupByIDsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIpamVlangroupByIDsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIpamVlangroupByIDsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIpamVlangroupByIDsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIpamVlangroupByIDsRequestValidationError) ErrorName() string {
	return "ListIpamVlangroupByIDsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListIpamVlangroupByIDsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIpamVlangroupByIDsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIpamVlangroupByIDsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIpamVlangroupByIDsRequestValidationError{}

// Validate checks the field values on ListIpamVlangroupByIDsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIpamVlangroupByIDsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIpamVlangroupByIDsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIpamVlangroupByIDsReplyMultiError, or nil if none found.
func (m *ListIpamVlangroupByIDsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIpamVlangroupByIDsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetIpamVlangroups() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListIpamVlangroupByIDsReplyValidationError{
						field:  fmt.Sprintf("IpamVlangroups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListIpamVlangroupByIDsReplyValidationError{
						field:  fmt.Sprintf("IpamVlangroups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListIpamVlangroupByIDsReplyValidationError{
					field:  fmt.Sprintf("IpamVlangroups[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListIpamVlangroupByIDsReplyMultiError(errors)
	}

	return nil
}

// ListIpamVlangroupByIDsReplyMultiError is an error wrapping multiple
// validation errors returned by ListIpamVlangroupByIDsReply.ValidateAll() if
// the designated constraints aren't met.
type ListIpamVlangroupByIDsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIpamVlangroupByIDsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIpamVlangroupByIDsReplyMultiError) AllErrors() []error { return m }

// ListIpamVlangroupByIDsReplyValidationError is the validation error returned
// by ListIpamVlangroupByIDsReply.Validate if the designated constraints
// aren't met.
type ListIpamVlangroupByIDsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIpamVlangroupByIDsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIpamVlangroupByIDsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIpamVlangroupByIDsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIpamVlangroupByIDsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIpamVlangroupByIDsReplyValidationError) ErrorName() string {
	return "ListIpamVlangroupByIDsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListIpamVlangroupByIDsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIpamVlangroupByIDsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIpamVlangroupByIDsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIpamVlangroupByIDsReplyValidationError{}

// Validate checks the field values on ListIpamVlangroupByLastIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListIpamVlangroupByLastIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIpamVlangroupByLastIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListIpamVlangroupByLastIDRequestMultiError, or nil if none found.
func (m *ListIpamVlangroupByLastIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIpamVlangroupByLastIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LastID

	if m.GetLimit() <= 0 {
		err := ListIpamVlangroupByLastIDRequestValidationError{
			field:  "Limit",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Sort

	if len(errors) > 0 {
		return ListIpamVlangroupByLastIDRequestMultiError(errors)
	}

	return nil
}

// ListIpamVlangroupByLastIDRequestMultiError is an error wrapping multiple
// validation errors returned by
// ListIpamVlangroupByLastIDRequest.ValidateAll() if the designated
// constraints aren't met.
type ListIpamVlangroupByLastIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIpamVlangroupByLastIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIpamVlangroupByLastIDRequestMultiError) AllErrors() []error { return m }

// ListIpamVlangroupByLastIDRequestValidationError is the validation error
// returned by ListIpamVlangroupByLastIDRequest.Validate if the designated
// constraints aren't met.
type ListIpamVlangroupByLastIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIpamVlangroupByLastIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIpamVlangroupByLastIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIpamVlangroupByLastIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIpamVlangroupByLastIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIpamVlangroupByLastIDRequestValidationError) ErrorName() string {
	return "ListIpamVlangroupByLastIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListIpamVlangroupByLastIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIpamVlangroupByLastIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIpamVlangroupByLastIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIpamVlangroupByLastIDRequestValidationError{}

// Validate checks the field values on ListIpamVlangroupByLastIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIpamVlangroupByLastIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIpamVlangroupByLastIDReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListIpamVlangroupByLastIDReplyMultiError, or nil if none found.
func (m *ListIpamVlangroupByLastIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIpamVlangroupByLastIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetIpamVlangroups() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListIpamVlangroupByLastIDReplyValidationError{
						field:  fmt.Sprintf("IpamVlangroups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListIpamVlangroupByLastIDReplyValidationError{
						field:  fmt.Sprintf("IpamVlangroups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListIpamVlangroupByLastIDReplyValidationError{
					field:  fmt.Sprintf("IpamVlangroups[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListIpamVlangroupByLastIDReplyMultiError(errors)
	}

	return nil
}

// ListIpamVlangroupByLastIDReplyMultiError is an error wrapping multiple
// validation errors returned by ListIpamVlangroupByLastIDReply.ValidateAll()
// if the designated constraints aren't met.
type ListIpamVlangroupByLastIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIpamVlangroupByLastIDReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIpamVlangroupByLastIDReplyMultiError) AllErrors() []error { return m }

// ListIpamVlangroupByLastIDReplyValidationError is the validation error
// returned by ListIpamVlangroupByLastIDReply.Validate if the designated
// constraints aren't met.
type ListIpamVlangroupByLastIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIpamVlangroupByLastIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIpamVlangroupByLastIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIpamVlangroupByLastIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIpamVlangroupByLastIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIpamVlangroupByLastIDReplyValidationError) ErrorName() string {
	return "ListIpamVlangroupByLastIDReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListIpamVlangroupByLastIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIpamVlangroupByLastIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIpamVlangroupByLastIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIpamVlangroupByLastIDReplyValidationError{}
