syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service ipamRoutetarget {
  // Create a new ipamRoutetarget
  rpc Create(CreateIpamRoutetargetRequest) returns (CreateIpamRoutetargetReply) {
    option (google.api.http) = {
      post: "/api/ipam/routetargets"
      body: "*"
    };
  }

  // Delete a ipamRoutetarget by id
  rpc DeleteByID(DeleteIpamRoutetargetByIDRequest) returns (DeleteIpamRoutetargetByIDReply) {
    option (google.api.http) = {
      delete: "/api/ipam/routetargets/{id}"
    };
  }

  // Update a ipamRoutetarget by id
  rpc UpdateByID(UpdateIpamRoutetargetByIDRequest) returns (UpdateIpamRoutetargetByIDReply) {
    option (google.api.http) = {
      put: "/api/ipam/routetargets/{id}"
      body: "*"
    };
  }

  // Get a ipamRoutetarget by id
  rpc GetByID(GetIpamRoutetargetByIDRequest) returns (GetIpamRoutetargetByIDReply) {
    option (google.api.http) = {
      get: "/api/ipam/routetargets/{id}"
    };
  }

  // Get a paginated list of ipamRoutetarget by custom conditions
  rpc List(ListIpamRoutetargetRequest) returns (ListIpamRoutetargetReply) {
    option (google.api.http) = {
      post: "/api/ipam/routetargets/list"
      body: "*"
    };
  }

  // Batch delete ipamRoutetarget by ids
  rpc DeleteByIDs(DeleteIpamRoutetargetByIDsRequest) returns (DeleteIpamRoutetargetByIDsReply) {
    option (google.api.http) = {
      post: "/api/ipam/routetargets/delete/ids"
      body: "*"
    };
  }

  // Get a ipamRoutetarget by custom condition
  rpc GetByCondition(GetIpamRoutetargetByConditionRequest) returns (GetIpamRoutetargetByConditionReply) {
    option (google.api.http) = {
      post: "/api/ipam/routetargets/condition"
      body: "*"
    };
  }

  // Batch get ipamRoutetarget by ids
  rpc ListByIDs(ListIpamRoutetargetByIDsRequest) returns (ListIpamRoutetargetByIDsReply) {
    option (google.api.http) = {
      post: "/api/ipam/routetargets/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of ipamRoutetarget by last id
  rpc ListByLastID(ListIpamRoutetargetByLastIDRequest) returns (ListIpamRoutetargetByLastIDReply) {
    option (google.api.http) = {
      get: "/api/ipam/routetargets"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/ipamRoutetarget/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getIpamRoutetarget?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateIpamRoutetargetRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	string name = 4; 
	string description = 5; 
	int64 tenantID = 6; 
	string comments = 7; 
}

message CreateIpamRoutetargetReply {
  uint64 id = 1;
}

message DeleteIpamRoutetargetByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteIpamRoutetargetByIDReply {

}

message UpdateIpamRoutetargetByIDRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string name = 5; 
	string description = 6; 
	int64 tenantID = 7; 
	string comments = 8; 
}

message UpdateIpamRoutetargetByIDReply {

}

message IpamRoutetarget {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4; 
	string name = 5; 
	string description = 6; 
	int64 tenantID = 7; 
	string comments = 8; 
}

message GetIpamRoutetargetByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetIpamRoutetargetByIDReply {
  IpamRoutetarget ipamRoutetarget = 1;
}

message ListIpamRoutetargetRequest {
  api.types.Params params = 1;
}

message ListIpamRoutetargetReply {
  int64 total = 1;
  repeated IpamRoutetarget ipamRoutetargets = 2;
}

message DeleteIpamRoutetargetByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteIpamRoutetargetByIDsReply {

}

message GetIpamRoutetargetByConditionRequest {
  types.Conditions conditions = 1;
}

message GetIpamRoutetargetByConditionReply {
  IpamRoutetarget ipamRoutetarget = 1;
}

message ListIpamRoutetargetByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListIpamRoutetargetByIDsReply {
  repeated IpamRoutetarget ipamRoutetargets = 1;
}

message ListIpamRoutetargetByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListIpamRoutetargetByLastIDReply {
  repeated IpamRoutetarget ipamRoutetargets = 1;
}


