syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service ipamIprange {
  // Create a new ipamIprange
  rpc Create(CreateIpamIprangeRequest) returns (CreateIpamIprangeReply) {
    option (google.api.http) = {
      post: "/api/ipam/ipranges"
      body: "*"
    };
  }

  // Delete a ipamIprange by id
  rpc DeleteByID(DeleteIpamIprangeByIDRequest) returns (DeleteIpamIprangeByIDReply) {
    option (google.api.http) = {
      delete: "/api/ipam/ipranges/{id}"
    };
  }

  // Update a ipamIprange by id
  rpc UpdateByID(UpdateIpamIprangeByIDRequest) returns (UpdateIpamIprangeByIDReply) {
    option (google.api.http) = {
      put: "/api/ipam/ipranges/{id}"
      body: "*"
    };
  }

  // Get a ipamIprange by id
  rpc GetByID(GetIpamIprangeByIDRequest) returns (GetIpamIprangeByIDReply) {
    option (google.api.http) = {
      get: "/api/ipam/ipranges/{id}"
    };
  }

  // Get a paginated list of ipamIprange by custom conditions
  rpc List(ListIpamIprangeRequest) returns (ListIpamIprangeReply) {
    option (google.api.http) = {
      post: "/api/ipam/ipranges/list"
      body: "*"
    };
  }

  // Batch delete ipamIprange by ids
  rpc DeleteByIDs(DeleteIpamIprangeByIDsRequest) returns (DeleteIpamIprangeByIDsReply) {
    option (google.api.http) = {
      post: "/api/ipam/ipranges/delete/ids"
      body: "*"
    };
  }

  // Get a ipamIprange by custom condition
  rpc GetByCondition(GetIpamIprangeByConditionRequest) returns (GetIpamIprangeByConditionReply) {
    option (google.api.http) = {
      post: "/api/ipam/ipranges/condition"
      body: "*"
    };
  }

  // Batch get ipamIprange by ids
  rpc ListByIDs(ListIpamIprangeByIDsRequest) returns (ListIpamIprangeByIDsReply) {
    option (google.api.http) = {
      post: "/api/ipam/ipranges/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of ipamIprange by last id
  rpc ListByLastID(ListIpamIprangeByLastIDRequest) returns (ListIpamIprangeByLastIDReply) {
    option (google.api.http) = {
      get: "/api/ipam/ipranges"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/ipamIprange/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getIpamIprange?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateIpamIprangeRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	string startAddress = 4; 
	string endAddress = 5; 
	int32 size = 6; 
	string status = 7; 
	string description = 8; 
	int64 roleID = 9; 
	int64 tenantID = 10; 
	int64 vrfID = 11; 
	string comments = 12; 
	bool markUtilized = 13; 
	bool markPopulated = 14; 
}

message CreateIpamIprangeReply {
  uint64 id = 1;
}

message DeleteIpamIprangeByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteIpamIprangeByIDReply {

}

message UpdateIpamIprangeByIDRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string startAddress = 5; 
	string endAddress = 6; 
	int32 size = 7; 
	string status = 8; 
	string description = 9; 
	int64 roleID = 10; 
	int64 tenantID = 11; 
	int64 vrfID = 12; 
	string comments = 13; 
	bool markUtilized = 14; 
	bool markPopulated = 15; 
}

message UpdateIpamIprangeByIDReply {

}

message IpamIprange {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4; 
	string startAddress = 5; 
	string endAddress = 6; 
	int32 size = 7; 
	string status = 8; 
	string description = 9; 
	int64 roleID = 10; 
	int64 tenantID = 11; 
	int64 vrfID = 12; 
	string comments = 13; 
	bool markUtilized = 14; 
	bool markPopulated = 15; 
}

message GetIpamIprangeByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetIpamIprangeByIDReply {
  IpamIprange ipamIprange = 1;
}

message ListIpamIprangeRequest {
  api.types.Params params = 1;
}

message ListIpamIprangeReply {
  int64 total = 1;
  repeated IpamIprange ipamIpranges = 2;
}

message DeleteIpamIprangeByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteIpamIprangeByIDsReply {

}

message GetIpamIprangeByConditionRequest {
  types.Conditions conditions = 1;
}

message GetIpamIprangeByConditionReply {
  IpamIprange ipamIprange = 1;
}

message ListIpamIprangeByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListIpamIprangeByIDsReply {
  repeated IpamIprange ipamIpranges = 1;
}

message ListIpamIprangeByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListIpamIprangeByLastIDReply {
  repeated IpamIprange ipamIpranges = 1;
}


