// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/netbox_go/v1/socialAuthAssociation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "netbox-go/api/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSocialAuthAssociationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerURL     string                 `protobuf:"bytes,1,opt,name=serverURL,proto3" json:"serverURL"`
	Handle        string                 `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret"`
	Issued        int32                  `protobuf:"varint,4,opt,name=issued,proto3" json:"issued"`
	Lifetime      int32                  `protobuf:"varint,5,opt,name=lifetime,proto3" json:"lifetime"`
	AssocType     string                 `protobuf:"bytes,6,opt,name=assocType,proto3" json:"assocType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSocialAuthAssociationRequest) Reset() {
	*x = CreateSocialAuthAssociationRequest{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSocialAuthAssociationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSocialAuthAssociationRequest) ProtoMessage() {}

func (x *CreateSocialAuthAssociationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSocialAuthAssociationRequest.ProtoReflect.Descriptor instead.
func (*CreateSocialAuthAssociationRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSocialAuthAssociationRequest) GetServerURL() string {
	if x != nil {
		return x.ServerURL
	}
	return ""
}

func (x *CreateSocialAuthAssociationRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *CreateSocialAuthAssociationRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CreateSocialAuthAssociationRequest) GetIssued() int32 {
	if x != nil {
		return x.Issued
	}
	return 0
}

func (x *CreateSocialAuthAssociationRequest) GetLifetime() int32 {
	if x != nil {
		return x.Lifetime
	}
	return 0
}

func (x *CreateSocialAuthAssociationRequest) GetAssocType() string {
	if x != nil {
		return x.AssocType
	}
	return ""
}

type CreateSocialAuthAssociationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSocialAuthAssociationReply) Reset() {
	*x = CreateSocialAuthAssociationReply{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSocialAuthAssociationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSocialAuthAssociationReply) ProtoMessage() {}

func (x *CreateSocialAuthAssociationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSocialAuthAssociationReply.ProtoReflect.Descriptor instead.
func (*CreateSocialAuthAssociationReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSocialAuthAssociationReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSocialAuthAssociationByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSocialAuthAssociationByIDRequest) Reset() {
	*x = DeleteSocialAuthAssociationByIDRequest{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSocialAuthAssociationByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSocialAuthAssociationByIDRequest) ProtoMessage() {}

func (x *DeleteSocialAuthAssociationByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSocialAuthAssociationByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteSocialAuthAssociationByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSocialAuthAssociationByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSocialAuthAssociationByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSocialAuthAssociationByIDReply) Reset() {
	*x = DeleteSocialAuthAssociationByIDReply{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSocialAuthAssociationByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSocialAuthAssociationByIDReply) ProtoMessage() {}

func (x *DeleteSocialAuthAssociationByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSocialAuthAssociationByIDReply.ProtoReflect.Descriptor instead.
func (*DeleteSocialAuthAssociationByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{3}
}

type UpdateSocialAuthAssociationByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	ServerURL     string                 `protobuf:"bytes,2,opt,name=serverURL,proto3" json:"serverURL"`
	Handle        string                 `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle"`
	Secret        string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret"`
	Issued        int32                  `protobuf:"varint,5,opt,name=issued,proto3" json:"issued"`
	Lifetime      int32                  `protobuf:"varint,6,opt,name=lifetime,proto3" json:"lifetime"`
	AssocType     string                 `protobuf:"bytes,7,opt,name=assocType,proto3" json:"assocType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSocialAuthAssociationByIDRequest) Reset() {
	*x = UpdateSocialAuthAssociationByIDRequest{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSocialAuthAssociationByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSocialAuthAssociationByIDRequest) ProtoMessage() {}

func (x *UpdateSocialAuthAssociationByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSocialAuthAssociationByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateSocialAuthAssociationByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSocialAuthAssociationByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSocialAuthAssociationByIDRequest) GetServerURL() string {
	if x != nil {
		return x.ServerURL
	}
	return ""
}

func (x *UpdateSocialAuthAssociationByIDRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *UpdateSocialAuthAssociationByIDRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *UpdateSocialAuthAssociationByIDRequest) GetIssued() int32 {
	if x != nil {
		return x.Issued
	}
	return 0
}

func (x *UpdateSocialAuthAssociationByIDRequest) GetLifetime() int32 {
	if x != nil {
		return x.Lifetime
	}
	return 0
}

func (x *UpdateSocialAuthAssociationByIDRequest) GetAssocType() string {
	if x != nil {
		return x.AssocType
	}
	return ""
}

type UpdateSocialAuthAssociationByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSocialAuthAssociationByIDReply) Reset() {
	*x = UpdateSocialAuthAssociationByIDReply{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSocialAuthAssociationByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSocialAuthAssociationByIDReply) ProtoMessage() {}

func (x *UpdateSocialAuthAssociationByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSocialAuthAssociationByIDReply.ProtoReflect.Descriptor instead.
func (*UpdateSocialAuthAssociationByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{5}
}

type SocialAuthAssociation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	ServerURL     string                 `protobuf:"bytes,2,opt,name=serverURL,proto3" json:"serverURL"`
	Handle        string                 `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle"`
	Secret        string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret"`
	Issued        int32                  `protobuf:"varint,5,opt,name=issued,proto3" json:"issued"`
	Lifetime      int32                  `protobuf:"varint,6,opt,name=lifetime,proto3" json:"lifetime"`
	AssocType     string                 `protobuf:"bytes,7,opt,name=assocType,proto3" json:"assocType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialAuthAssociation) Reset() {
	*x = SocialAuthAssociation{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialAuthAssociation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialAuthAssociation) ProtoMessage() {}

func (x *SocialAuthAssociation) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialAuthAssociation.ProtoReflect.Descriptor instead.
func (*SocialAuthAssociation) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{6}
}

func (x *SocialAuthAssociation) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialAuthAssociation) GetServerURL() string {
	if x != nil {
		return x.ServerURL
	}
	return ""
}

func (x *SocialAuthAssociation) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *SocialAuthAssociation) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *SocialAuthAssociation) GetIssued() int32 {
	if x != nil {
		return x.Issued
	}
	return 0
}

func (x *SocialAuthAssociation) GetLifetime() int32 {
	if x != nil {
		return x.Lifetime
	}
	return 0
}

func (x *SocialAuthAssociation) GetAssocType() string {
	if x != nil {
		return x.AssocType
	}
	return ""
}

type GetSocialAuthAssociationByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSocialAuthAssociationByIDRequest) Reset() {
	*x = GetSocialAuthAssociationByIDRequest{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSocialAuthAssociationByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocialAuthAssociationByIDRequest) ProtoMessage() {}

func (x *GetSocialAuthAssociationByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocialAuthAssociationByIDRequest.ProtoReflect.Descriptor instead.
func (*GetSocialAuthAssociationByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{7}
}

func (x *GetSocialAuthAssociationByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSocialAuthAssociationByIDReply struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SocialAuthAssociation *SocialAuthAssociation `protobuf:"bytes,1,opt,name=socialAuthAssociation,proto3" json:"socialAuthAssociation"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSocialAuthAssociationByIDReply) Reset() {
	*x = GetSocialAuthAssociationByIDReply{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSocialAuthAssociationByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocialAuthAssociationByIDReply) ProtoMessage() {}

func (x *GetSocialAuthAssociationByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocialAuthAssociationByIDReply.ProtoReflect.Descriptor instead.
func (*GetSocialAuthAssociationByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{8}
}

func (x *GetSocialAuthAssociationByIDReply) GetSocialAuthAssociation() *SocialAuthAssociation {
	if x != nil {
		return x.SocialAuthAssociation
	}
	return nil
}

type ListSocialAuthAssociationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *types.Params          `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSocialAuthAssociationRequest) Reset() {
	*x = ListSocialAuthAssociationRequest{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSocialAuthAssociationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSocialAuthAssociationRequest) ProtoMessage() {}

func (x *ListSocialAuthAssociationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSocialAuthAssociationRequest.ProtoReflect.Descriptor instead.
func (*ListSocialAuthAssociationRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{9}
}

func (x *ListSocialAuthAssociationRequest) GetParams() *types.Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type ListSocialAuthAssociationReply struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	Total                  int64                    `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	SocialAuthAssociations []*SocialAuthAssociation `protobuf:"bytes,2,rep,name=socialAuthAssociations,proto3" json:"socialAuthAssociations"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListSocialAuthAssociationReply) Reset() {
	*x = ListSocialAuthAssociationReply{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSocialAuthAssociationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSocialAuthAssociationReply) ProtoMessage() {}

func (x *ListSocialAuthAssociationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSocialAuthAssociationReply.ProtoReflect.Descriptor instead.
func (*ListSocialAuthAssociationReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{10}
}

func (x *ListSocialAuthAssociationReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSocialAuthAssociationReply) GetSocialAuthAssociations() []*SocialAuthAssociation {
	if x != nil {
		return x.SocialAuthAssociations
	}
	return nil
}

type DeleteSocialAuthAssociationByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSocialAuthAssociationByIDsRequest) Reset() {
	*x = DeleteSocialAuthAssociationByIDsRequest{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSocialAuthAssociationByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSocialAuthAssociationByIDsRequest) ProtoMessage() {}

func (x *DeleteSocialAuthAssociationByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSocialAuthAssociationByIDsRequest.ProtoReflect.Descriptor instead.
func (*DeleteSocialAuthAssociationByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSocialAuthAssociationByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteSocialAuthAssociationByIDsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSocialAuthAssociationByIDsReply) Reset() {
	*x = DeleteSocialAuthAssociationByIDsReply{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSocialAuthAssociationByIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSocialAuthAssociationByIDsReply) ProtoMessage() {}

func (x *DeleteSocialAuthAssociationByIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSocialAuthAssociationByIDsReply.ProtoReflect.Descriptor instead.
func (*DeleteSocialAuthAssociationByIDsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{12}
}

type GetSocialAuthAssociationByConditionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    *types.Conditions      `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSocialAuthAssociationByConditionRequest) Reset() {
	*x = GetSocialAuthAssociationByConditionRequest{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSocialAuthAssociationByConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocialAuthAssociationByConditionRequest) ProtoMessage() {}

func (x *GetSocialAuthAssociationByConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocialAuthAssociationByConditionRequest.ProtoReflect.Descriptor instead.
func (*GetSocialAuthAssociationByConditionRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{13}
}

func (x *GetSocialAuthAssociationByConditionRequest) GetConditions() *types.Conditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type GetSocialAuthAssociationByConditionReply struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SocialAuthAssociation *SocialAuthAssociation `protobuf:"bytes,1,opt,name=socialAuthAssociation,proto3" json:"socialAuthAssociation"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSocialAuthAssociationByConditionReply) Reset() {
	*x = GetSocialAuthAssociationByConditionReply{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSocialAuthAssociationByConditionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocialAuthAssociationByConditionReply) ProtoMessage() {}

func (x *GetSocialAuthAssociationByConditionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocialAuthAssociationByConditionReply.ProtoReflect.Descriptor instead.
func (*GetSocialAuthAssociationByConditionReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{14}
}

func (x *GetSocialAuthAssociationByConditionReply) GetSocialAuthAssociation() *SocialAuthAssociation {
	if x != nil {
		return x.SocialAuthAssociation
	}
	return nil
}

type ListSocialAuthAssociationByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSocialAuthAssociationByIDsRequest) Reset() {
	*x = ListSocialAuthAssociationByIDsRequest{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSocialAuthAssociationByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSocialAuthAssociationByIDsRequest) ProtoMessage() {}

func (x *ListSocialAuthAssociationByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSocialAuthAssociationByIDsRequest.ProtoReflect.Descriptor instead.
func (*ListSocialAuthAssociationByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{15}
}

func (x *ListSocialAuthAssociationByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListSocialAuthAssociationByIDsReply struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	SocialAuthAssociations []*SocialAuthAssociation `protobuf:"bytes,1,rep,name=socialAuthAssociations,proto3" json:"socialAuthAssociations"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListSocialAuthAssociationByIDsReply) Reset() {
	*x = ListSocialAuthAssociationByIDsReply{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSocialAuthAssociationByIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSocialAuthAssociationByIDsReply) ProtoMessage() {}

func (x *ListSocialAuthAssociationByIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSocialAuthAssociationByIDsReply.ProtoReflect.Descriptor instead.
func (*ListSocialAuthAssociationByIDsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{16}
}

func (x *ListSocialAuthAssociationByIDsReply) GetSocialAuthAssociations() []*SocialAuthAssociation {
	if x != nil {
		return x.SocialAuthAssociations
	}
	return nil
}

type ListSocialAuthAssociationByLastIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastID        uint64                 `protobuf:"varint,1,opt,name=lastID,proto3" json:"lastID" form:"lastID"` // last id
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit" form:"limit"`    // limit size per page
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort" form:"sort"`        // sort by column name of table, default is -id, the - sign indicates descending order.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSocialAuthAssociationByLastIDRequest) Reset() {
	*x = ListSocialAuthAssociationByLastIDRequest{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSocialAuthAssociationByLastIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSocialAuthAssociationByLastIDRequest) ProtoMessage() {}

func (x *ListSocialAuthAssociationByLastIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSocialAuthAssociationByLastIDRequest.ProtoReflect.Descriptor instead.
func (*ListSocialAuthAssociationByLastIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{17}
}

func (x *ListSocialAuthAssociationByLastIDRequest) GetLastID() uint64 {
	if x != nil {
		return x.LastID
	}
	return 0
}

func (x *ListSocialAuthAssociationByLastIDRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSocialAuthAssociationByLastIDRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListSocialAuthAssociationByLastIDReply struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	SocialAuthAssociations []*SocialAuthAssociation `protobuf:"bytes,1,rep,name=socialAuthAssociations,proto3" json:"socialAuthAssociations"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListSocialAuthAssociationByLastIDReply) Reset() {
	*x = ListSocialAuthAssociationByLastIDReply{}
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSocialAuthAssociationByLastIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSocialAuthAssociationByLastIDReply) ProtoMessage() {}

func (x *ListSocialAuthAssociationByLastIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSocialAuthAssociationByLastIDReply.ProtoReflect.Descriptor instead.
func (*ListSocialAuthAssociationByLastIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP(), []int{18}
}

func (x *ListSocialAuthAssociationByLastIDReply) GetSocialAuthAssociations() []*SocialAuthAssociation {
	if x != nil {
		return x.SocialAuthAssociations
	}
	return nil
}

var File_api_netbox_go_v1_socialAuthAssociation_proto protoreflect.FileDescriptor

const file_api_netbox_go_v1_socialAuthAssociation_proto_rawDesc = "" +
	"\n" +
	",api/netbox_go/v1/socialAuthAssociation.proto\x12\x10api.netbox_go.v1\x1a\x15api/types/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x13tagger/tagger.proto\x1a\x17validate/validate.proto\"\xc4\x01\n" +
	"\"CreateSocialAuthAssociationRequest\x12\x1c\n" +
	"\tserverURL\x18\x01 \x01(\tR\tserverURL\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x16\n" +
	"\x06issued\x18\x04 \x01(\x05R\x06issued\x12\x1a\n" +
	"\blifetime\x18\x05 \x01(\x05R\blifetime\x12\x1c\n" +
	"\tassocType\x18\x06 \x01(\tR\tassocType\"2\n" +
	" CreateSocialAuthAssociationReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"N\n" +
	"&DeleteSocialAuthAssociationByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"&\n" +
	"$DeleteSocialAuthAssociationByIDReply\"\xee\x01\n" +
	"&UpdateSocialAuthAssociationByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\x12\x1c\n" +
	"\tserverURL\x18\x02 \x01(\tR\tserverURL\x12\x16\n" +
	"\x06handle\x18\x03 \x01(\tR\x06handle\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\x12\x16\n" +
	"\x06issued\x18\x05 \x01(\x05R\x06issued\x12\x1a\n" +
	"\blifetime\x18\x06 \x01(\x05R\blifetime\x12\x1c\n" +
	"\tassocType\x18\a \x01(\tR\tassocType\"&\n" +
	"$UpdateSocialAuthAssociationByIDReply\"\xc7\x01\n" +
	"\x15SocialAuthAssociation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\tserverURL\x18\x02 \x01(\tR\tserverURL\x12\x16\n" +
	"\x06handle\x18\x03 \x01(\tR\x06handle\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\x12\x16\n" +
	"\x06issued\x18\x05 \x01(\x05R\x06issued\x12\x1a\n" +
	"\blifetime\x18\x06 \x01(\x05R\blifetime\x12\x1c\n" +
	"\tassocType\x18\a \x01(\tR\tassocType\"K\n" +
	"#GetSocialAuthAssociationByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"\x82\x01\n" +
	"!GetSocialAuthAssociationByIDReply\x12]\n" +
	"\x15socialAuthAssociation\x18\x01 \x01(\v2'.api.netbox_go.v1.SocialAuthAssociationR\x15socialAuthAssociation\"M\n" +
	" ListSocialAuthAssociationRequest\x12)\n" +
	"\x06params\x18\x01 \x01(\v2\x11.api.types.ParamsR\x06params\"\x97\x01\n" +
	"\x1eListSocialAuthAssociationReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12_\n" +
	"\x16socialAuthAssociations\x18\x02 \x03(\v2'.api.netbox_go.v1.SocialAuthAssociationR\x16socialAuthAssociations\"E\n" +
	"'DeleteSocialAuthAssociationByIDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"'\n" +
	"%DeleteSocialAuthAssociationByIDsReply\"c\n" +
	"*GetSocialAuthAssociationByConditionRequest\x125\n" +
	"\n" +
	"conditions\x18\x01 \x01(\v2\x15.api.types.ConditionsR\n" +
	"conditions\"\x89\x01\n" +
	"(GetSocialAuthAssociationByConditionReply\x12]\n" +
	"\x15socialAuthAssociation\x18\x01 \x01(\v2'.api.netbox_go.v1.SocialAuthAssociationR\x15socialAuthAssociation\"C\n" +
	"%ListSocialAuthAssociationByIDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"\x86\x01\n" +
	"#ListSocialAuthAssociationByIDsReply\x12_\n" +
	"\x16socialAuthAssociations\x18\x01 \x03(\v2'.api.netbox_go.v1.SocialAuthAssociationR\x16socialAuthAssociations\"\xac\x01\n" +
	"(ListSocialAuthAssociationByLastIDRequest\x12*\n" +
	"\x06lastID\x18\x01 \x01(\x04B\x12\x9a\x84\x9e\x03\rform:\"lastID\"R\x06lastID\x12.\n" +
	"\x05limit\x18\x02 \x01(\rB\x18\xfaB\x04*\x02 \x00\x9a\x84\x9e\x03\fform:\"limit\"R\x05limit\x12$\n" +
	"\x04sort\x18\x03 \x01(\tB\x10\x9a\x84\x9e\x03\vform:\"sort\"R\x04sort\"\x89\x01\n" +
	"&ListSocialAuthAssociationByLastIDReply\x12_\n" +
	"\x16socialAuthAssociations\x18\x01 \x03(\v2'.api.netbox_go.v1.SocialAuthAssociationR\x16socialAuthAssociations2\xa5\f\n" +
	"\x15socialAuthAssociation\x12\x9b\x01\n" +
	"\x06Create\x124.api.netbox_go.v1.CreateSocialAuthAssociationRequest\x1a2.api.netbox_go.v1.CreateSocialAuthAssociationReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/users/auth-associations\x12\xa9\x01\n" +
	"\n" +
	"DeleteByID\x128.api.netbox_go.v1.DeleteSocialAuthAssociationByIDRequest\x1a6.api.netbox_go.v1.DeleteSocialAuthAssociationByIDReply\")\x82\xd3\xe4\x93\x02#*!/api/users/auth-associations/{id}\x12\xac\x01\n" +
	"\n" +
	"UpdateByID\x128.api.netbox_go.v1.UpdateSocialAuthAssociationByIDRequest\x1a6.api.netbox_go.v1.UpdateSocialAuthAssociationByIDReply\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/users/auth-associations/{id}\x12\xa0\x01\n" +
	"\aGetByID\x125.api.netbox_go.v1.GetSocialAuthAssociationByIDRequest\x1a3.api.netbox_go.v1.GetSocialAuthAssociationByIDReply\")\x82\xd3\xe4\x93\x02#\x12!/api/users/auth-associations/{id}\x12\x9a\x01\n" +
	"\x04List\x122.api.netbox_go.v1.ListSocialAuthAssociationRequest\x1a0.api.netbox_go.v1.ListSocialAuthAssociationReply\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/users/auth-associations/list\x12\xb5\x01\n" +
	"\vDeleteByIDs\x129.api.netbox_go.v1.DeleteSocialAuthAssociationByIDsRequest\x1a7.api.netbox_go.v1.DeleteSocialAuthAssociationByIDsReply\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/api/users/auth-associations/delete/ids\x12\xbd\x01\n" +
	"\x0eGetByCondition\x12<.api.netbox_go.v1.GetSocialAuthAssociationByConditionRequest\x1a:.api.netbox_go.v1.GetSocialAuthAssociationByConditionReply\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/users/auth-associations/condition\x12\xad\x01\n" +
	"\tListByIDs\x127.api.netbox_go.v1.ListSocialAuthAssociationByIDsRequest\x1a5.api.netbox_go.v1.ListSocialAuthAssociationByIDsReply\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/users/auth-associations/list/ids\x12\xaa\x01\n" +
	"\fListByLastID\x12:.api.netbox_go.v1.ListSocialAuthAssociationByLastIDRequest\x1a8.api.netbox_go.v1.ListSocialAuthAssociationByLastIDReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/users/auth-associationsB\xc3\x01\x92A\xa0\x01\x12\x1c\n" +
	"\x12netbox_go api docs2\x06v1.0.0\x1a\x0elocalhost:8080*\x02\x01\x022\x10application/json:\x10application/jsonZH\n" +
	"F\n" +
	"\n" +
	"BearerAuth\x128\b\x02\x12#Type Bearer your-jwt-token to Value\x1a\rAuthorization \x02Z\x1dnetbox-go/api/netbox_go/v1;v1b\x06proto3"

var (
	file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescOnce sync.Once
	file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescData []byte
)

func file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescGZIP() []byte {
	file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescOnce.Do(func() {
		file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_netbox_go_v1_socialAuthAssociation_proto_rawDesc), len(file_api_netbox_go_v1_socialAuthAssociation_proto_rawDesc)))
	})
	return file_api_netbox_go_v1_socialAuthAssociation_proto_rawDescData
}

var file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_netbox_go_v1_socialAuthAssociation_proto_goTypes = []any{
	(*CreateSocialAuthAssociationRequest)(nil),         // 0: api.netbox_go.v1.CreateSocialAuthAssociationRequest
	(*CreateSocialAuthAssociationReply)(nil),           // 1: api.netbox_go.v1.CreateSocialAuthAssociationReply
	(*DeleteSocialAuthAssociationByIDRequest)(nil),     // 2: api.netbox_go.v1.DeleteSocialAuthAssociationByIDRequest
	(*DeleteSocialAuthAssociationByIDReply)(nil),       // 3: api.netbox_go.v1.DeleteSocialAuthAssociationByIDReply
	(*UpdateSocialAuthAssociationByIDRequest)(nil),     // 4: api.netbox_go.v1.UpdateSocialAuthAssociationByIDRequest
	(*UpdateSocialAuthAssociationByIDReply)(nil),       // 5: api.netbox_go.v1.UpdateSocialAuthAssociationByIDReply
	(*SocialAuthAssociation)(nil),                      // 6: api.netbox_go.v1.SocialAuthAssociation
	(*GetSocialAuthAssociationByIDRequest)(nil),        // 7: api.netbox_go.v1.GetSocialAuthAssociationByIDRequest
	(*GetSocialAuthAssociationByIDReply)(nil),          // 8: api.netbox_go.v1.GetSocialAuthAssociationByIDReply
	(*ListSocialAuthAssociationRequest)(nil),           // 9: api.netbox_go.v1.ListSocialAuthAssociationRequest
	(*ListSocialAuthAssociationReply)(nil),             // 10: api.netbox_go.v1.ListSocialAuthAssociationReply
	(*DeleteSocialAuthAssociationByIDsRequest)(nil),    // 11: api.netbox_go.v1.DeleteSocialAuthAssociationByIDsRequest
	(*DeleteSocialAuthAssociationByIDsReply)(nil),      // 12: api.netbox_go.v1.DeleteSocialAuthAssociationByIDsReply
	(*GetSocialAuthAssociationByConditionRequest)(nil), // 13: api.netbox_go.v1.GetSocialAuthAssociationByConditionRequest
	(*GetSocialAuthAssociationByConditionReply)(nil),   // 14: api.netbox_go.v1.GetSocialAuthAssociationByConditionReply
	(*ListSocialAuthAssociationByIDsRequest)(nil),      // 15: api.netbox_go.v1.ListSocialAuthAssociationByIDsRequest
	(*ListSocialAuthAssociationByIDsReply)(nil),        // 16: api.netbox_go.v1.ListSocialAuthAssociationByIDsReply
	(*ListSocialAuthAssociationByLastIDRequest)(nil),   // 17: api.netbox_go.v1.ListSocialAuthAssociationByLastIDRequest
	(*ListSocialAuthAssociationByLastIDReply)(nil),     // 18: api.netbox_go.v1.ListSocialAuthAssociationByLastIDReply
	(*types.Params)(nil),                               // 19: api.types.Params
	(*types.Conditions)(nil),                           // 20: api.types.Conditions
}
var file_api_netbox_go_v1_socialAuthAssociation_proto_depIdxs = []int32{
	6,  // 0: api.netbox_go.v1.GetSocialAuthAssociationByIDReply.socialAuthAssociation:type_name -> api.netbox_go.v1.SocialAuthAssociation
	19, // 1: api.netbox_go.v1.ListSocialAuthAssociationRequest.params:type_name -> api.types.Params
	6,  // 2: api.netbox_go.v1.ListSocialAuthAssociationReply.socialAuthAssociations:type_name -> api.netbox_go.v1.SocialAuthAssociation
	20, // 3: api.netbox_go.v1.GetSocialAuthAssociationByConditionRequest.conditions:type_name -> api.types.Conditions
	6,  // 4: api.netbox_go.v1.GetSocialAuthAssociationByConditionReply.socialAuthAssociation:type_name -> api.netbox_go.v1.SocialAuthAssociation
	6,  // 5: api.netbox_go.v1.ListSocialAuthAssociationByIDsReply.socialAuthAssociations:type_name -> api.netbox_go.v1.SocialAuthAssociation
	6,  // 6: api.netbox_go.v1.ListSocialAuthAssociationByLastIDReply.socialAuthAssociations:type_name -> api.netbox_go.v1.SocialAuthAssociation
	0,  // 7: api.netbox_go.v1.socialAuthAssociation.Create:input_type -> api.netbox_go.v1.CreateSocialAuthAssociationRequest
	2,  // 8: api.netbox_go.v1.socialAuthAssociation.DeleteByID:input_type -> api.netbox_go.v1.DeleteSocialAuthAssociationByIDRequest
	4,  // 9: api.netbox_go.v1.socialAuthAssociation.UpdateByID:input_type -> api.netbox_go.v1.UpdateSocialAuthAssociationByIDRequest
	7,  // 10: api.netbox_go.v1.socialAuthAssociation.GetByID:input_type -> api.netbox_go.v1.GetSocialAuthAssociationByIDRequest
	9,  // 11: api.netbox_go.v1.socialAuthAssociation.List:input_type -> api.netbox_go.v1.ListSocialAuthAssociationRequest
	11, // 12: api.netbox_go.v1.socialAuthAssociation.DeleteByIDs:input_type -> api.netbox_go.v1.DeleteSocialAuthAssociationByIDsRequest
	13, // 13: api.netbox_go.v1.socialAuthAssociation.GetByCondition:input_type -> api.netbox_go.v1.GetSocialAuthAssociationByConditionRequest
	15, // 14: api.netbox_go.v1.socialAuthAssociation.ListByIDs:input_type -> api.netbox_go.v1.ListSocialAuthAssociationByIDsRequest
	17, // 15: api.netbox_go.v1.socialAuthAssociation.ListByLastID:input_type -> api.netbox_go.v1.ListSocialAuthAssociationByLastIDRequest
	1,  // 16: api.netbox_go.v1.socialAuthAssociation.Create:output_type -> api.netbox_go.v1.CreateSocialAuthAssociationReply
	3,  // 17: api.netbox_go.v1.socialAuthAssociation.DeleteByID:output_type -> api.netbox_go.v1.DeleteSocialAuthAssociationByIDReply
	5,  // 18: api.netbox_go.v1.socialAuthAssociation.UpdateByID:output_type -> api.netbox_go.v1.UpdateSocialAuthAssociationByIDReply
	8,  // 19: api.netbox_go.v1.socialAuthAssociation.GetByID:output_type -> api.netbox_go.v1.GetSocialAuthAssociationByIDReply
	10, // 20: api.netbox_go.v1.socialAuthAssociation.List:output_type -> api.netbox_go.v1.ListSocialAuthAssociationReply
	12, // 21: api.netbox_go.v1.socialAuthAssociation.DeleteByIDs:output_type -> api.netbox_go.v1.DeleteSocialAuthAssociationByIDsReply
	14, // 22: api.netbox_go.v1.socialAuthAssociation.GetByCondition:output_type -> api.netbox_go.v1.GetSocialAuthAssociationByConditionReply
	16, // 23: api.netbox_go.v1.socialAuthAssociation.ListByIDs:output_type -> api.netbox_go.v1.ListSocialAuthAssociationByIDsReply
	18, // 24: api.netbox_go.v1.socialAuthAssociation.ListByLastID:output_type -> api.netbox_go.v1.ListSocialAuthAssociationByLastIDReply
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_netbox_go_v1_socialAuthAssociation_proto_init() }
func file_api_netbox_go_v1_socialAuthAssociation_proto_init() {
	if File_api_netbox_go_v1_socialAuthAssociation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_netbox_go_v1_socialAuthAssociation_proto_rawDesc), len(file_api_netbox_go_v1_socialAuthAssociation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_netbox_go_v1_socialAuthAssociation_proto_goTypes,
		DependencyIndexes: file_api_netbox_go_v1_socialAuthAssociation_proto_depIdxs,
		MessageInfos:      file_api_netbox_go_v1_socialAuthAssociation_proto_msgTypes,
	}.Build()
	File_api_netbox_go_v1_socialAuthAssociation_proto = out.File
	file_api_netbox_go_v1_socialAuthAssociation_proto_goTypes = nil
	file_api_netbox_go_v1_socialAuthAssociation_proto_depIdxs = nil
}
