// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/netbox_go/v1/socialAuthNonce.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateSocialAuthNonceRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSocialAuthNonceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSocialAuthNonceRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSocialAuthNonceRequestMultiError, or nil if none found.
func (m *CreateSocialAuthNonceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSocialAuthNonceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ServerURL

	// no validation rules for Timestamp

	// no validation rules for Salt

	if len(errors) > 0 {
		return CreateSocialAuthNonceRequestMultiError(errors)
	}

	return nil
}

// CreateSocialAuthNonceRequestMultiError is an error wrapping multiple
// validation errors returned by CreateSocialAuthNonceRequest.ValidateAll() if
// the designated constraints aren't met.
type CreateSocialAuthNonceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSocialAuthNonceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSocialAuthNonceRequestMultiError) AllErrors() []error { return m }

// CreateSocialAuthNonceRequestValidationError is the validation error returned
// by CreateSocialAuthNonceRequest.Validate if the designated constraints
// aren't met.
type CreateSocialAuthNonceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSocialAuthNonceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSocialAuthNonceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSocialAuthNonceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSocialAuthNonceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSocialAuthNonceRequestValidationError) ErrorName() string {
	return "CreateSocialAuthNonceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSocialAuthNonceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSocialAuthNonceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSocialAuthNonceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSocialAuthNonceRequestValidationError{}

// Validate checks the field values on CreateSocialAuthNonceReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSocialAuthNonceReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSocialAuthNonceReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSocialAuthNonceReplyMultiError, or nil if none found.
func (m *CreateSocialAuthNonceReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSocialAuthNonceReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateSocialAuthNonceReplyMultiError(errors)
	}

	return nil
}

// CreateSocialAuthNonceReplyMultiError is an error wrapping multiple
// validation errors returned by CreateSocialAuthNonceReply.ValidateAll() if
// the designated constraints aren't met.
type CreateSocialAuthNonceReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSocialAuthNonceReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSocialAuthNonceReplyMultiError) AllErrors() []error { return m }

// CreateSocialAuthNonceReplyValidationError is the validation error returned
// by CreateSocialAuthNonceReply.Validate if the designated constraints aren't met.
type CreateSocialAuthNonceReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSocialAuthNonceReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSocialAuthNonceReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSocialAuthNonceReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSocialAuthNonceReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSocialAuthNonceReplyValidationError) ErrorName() string {
	return "CreateSocialAuthNonceReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSocialAuthNonceReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSocialAuthNonceReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSocialAuthNonceReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSocialAuthNonceReplyValidationError{}

// Validate checks the field values on DeleteSocialAuthNonceByIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *DeleteSocialAuthNonceByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSocialAuthNonceByIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteSocialAuthNonceByIDRequestMultiError, or nil if none found.
func (m *DeleteSocialAuthNonceByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSocialAuthNonceByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := DeleteSocialAuthNonceByIDRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteSocialAuthNonceByIDRequestMultiError(errors)
	}

	return nil
}

// DeleteSocialAuthNonceByIDRequestMultiError is an error wrapping multiple
// validation errors returned by
// DeleteSocialAuthNonceByIDRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteSocialAuthNonceByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSocialAuthNonceByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSocialAuthNonceByIDRequestMultiError) AllErrors() []error { return m }

// DeleteSocialAuthNonceByIDRequestValidationError is the validation error
// returned by DeleteSocialAuthNonceByIDRequest.Validate if the designated
// constraints aren't met.
type DeleteSocialAuthNonceByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSocialAuthNonceByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSocialAuthNonceByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSocialAuthNonceByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSocialAuthNonceByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSocialAuthNonceByIDRequestValidationError) ErrorName() string {
	return "DeleteSocialAuthNonceByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSocialAuthNonceByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSocialAuthNonceByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSocialAuthNonceByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSocialAuthNonceByIDRequestValidationError{}

// Validate checks the field values on DeleteSocialAuthNonceByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteSocialAuthNonceByIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSocialAuthNonceByIDReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteSocialAuthNonceByIDReplyMultiError, or nil if none found.
func (m *DeleteSocialAuthNonceByIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSocialAuthNonceByIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteSocialAuthNonceByIDReplyMultiError(errors)
	}

	return nil
}

// DeleteSocialAuthNonceByIDReplyMultiError is an error wrapping multiple
// validation errors returned by DeleteSocialAuthNonceByIDReply.ValidateAll()
// if the designated constraints aren't met.
type DeleteSocialAuthNonceByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSocialAuthNonceByIDReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSocialAuthNonceByIDReplyMultiError) AllErrors() []error { return m }

// DeleteSocialAuthNonceByIDReplyValidationError is the validation error
// returned by DeleteSocialAuthNonceByIDReply.Validate if the designated
// constraints aren't met.
type DeleteSocialAuthNonceByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSocialAuthNonceByIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSocialAuthNonceByIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSocialAuthNonceByIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSocialAuthNonceByIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSocialAuthNonceByIDReplyValidationError) ErrorName() string {
	return "DeleteSocialAuthNonceByIDReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSocialAuthNonceByIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSocialAuthNonceByIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSocialAuthNonceByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSocialAuthNonceByIDReplyValidationError{}

// Validate checks the field values on UpdateSocialAuthNonceByIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateSocialAuthNonceByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateSocialAuthNonceByIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateSocialAuthNonceByIDRequestMultiError, or nil if none found.
func (m *UpdateSocialAuthNonceByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateSocialAuthNonceByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateSocialAuthNonceByIDRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ServerURL

	// no validation rules for Timestamp

	// no validation rules for Salt

	if len(errors) > 0 {
		return UpdateSocialAuthNonceByIDRequestMultiError(errors)
	}

	return nil
}

// UpdateSocialAuthNonceByIDRequestMultiError is an error wrapping multiple
// validation errors returned by
// UpdateSocialAuthNonceByIDRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateSocialAuthNonceByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateSocialAuthNonceByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateSocialAuthNonceByIDRequestMultiError) AllErrors() []error { return m }

// UpdateSocialAuthNonceByIDRequestValidationError is the validation error
// returned by UpdateSocialAuthNonceByIDRequest.Validate if the designated
// constraints aren't met.
type UpdateSocialAuthNonceByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateSocialAuthNonceByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateSocialAuthNonceByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateSocialAuthNonceByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateSocialAuthNonceByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateSocialAuthNonceByIDRequestValidationError) ErrorName() string {
	return "UpdateSocialAuthNonceByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateSocialAuthNonceByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateSocialAuthNonceByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateSocialAuthNonceByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateSocialAuthNonceByIDRequestValidationError{}

// Validate checks the field values on UpdateSocialAuthNonceByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateSocialAuthNonceByIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateSocialAuthNonceByIDReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateSocialAuthNonceByIDReplyMultiError, or nil if none found.
func (m *UpdateSocialAuthNonceByIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateSocialAuthNonceByIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateSocialAuthNonceByIDReplyMultiError(errors)
	}

	return nil
}

// UpdateSocialAuthNonceByIDReplyMultiError is an error wrapping multiple
// validation errors returned by UpdateSocialAuthNonceByIDReply.ValidateAll()
// if the designated constraints aren't met.
type UpdateSocialAuthNonceByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateSocialAuthNonceByIDReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateSocialAuthNonceByIDReplyMultiError) AllErrors() []error { return m }

// UpdateSocialAuthNonceByIDReplyValidationError is the validation error
// returned by UpdateSocialAuthNonceByIDReply.Validate if the designated
// constraints aren't met.
type UpdateSocialAuthNonceByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateSocialAuthNonceByIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateSocialAuthNonceByIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateSocialAuthNonceByIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateSocialAuthNonceByIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateSocialAuthNonceByIDReplyValidationError) ErrorName() string {
	return "UpdateSocialAuthNonceByIDReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateSocialAuthNonceByIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateSocialAuthNonceByIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateSocialAuthNonceByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateSocialAuthNonceByIDReplyValidationError{}

// Validate checks the field values on SocialAuthNonce with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SocialAuthNonce) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SocialAuthNonce with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SocialAuthNonceMultiError, or nil if none found.
func (m *SocialAuthNonce) ValidateAll() error {
	return m.validate(true)
}

func (m *SocialAuthNonce) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ServerURL

	// no validation rules for Timestamp

	// no validation rules for Salt

	if len(errors) > 0 {
		return SocialAuthNonceMultiError(errors)
	}

	return nil
}

// SocialAuthNonceMultiError is an error wrapping multiple validation errors
// returned by SocialAuthNonce.ValidateAll() if the designated constraints
// aren't met.
type SocialAuthNonceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SocialAuthNonceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SocialAuthNonceMultiError) AllErrors() []error { return m }

// SocialAuthNonceValidationError is the validation error returned by
// SocialAuthNonce.Validate if the designated constraints aren't met.
type SocialAuthNonceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SocialAuthNonceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SocialAuthNonceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SocialAuthNonceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SocialAuthNonceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SocialAuthNonceValidationError) ErrorName() string { return "SocialAuthNonceValidationError" }

// Error satisfies the builtin error interface
func (e SocialAuthNonceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSocialAuthNonce.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SocialAuthNonceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SocialAuthNonceValidationError{}

// Validate checks the field values on GetSocialAuthNonceByIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSocialAuthNonceByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSocialAuthNonceByIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetSocialAuthNonceByIDRequestMultiError, or nil if none found.
func (m *GetSocialAuthNonceByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSocialAuthNonceByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := GetSocialAuthNonceByIDRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetSocialAuthNonceByIDRequestMultiError(errors)
	}

	return nil
}

// GetSocialAuthNonceByIDRequestMultiError is an error wrapping multiple
// validation errors returned by GetSocialAuthNonceByIDRequest.ValidateAll()
// if the designated constraints aren't met.
type GetSocialAuthNonceByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSocialAuthNonceByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSocialAuthNonceByIDRequestMultiError) AllErrors() []error { return m }

// GetSocialAuthNonceByIDRequestValidationError is the validation error
// returned by GetSocialAuthNonceByIDRequest.Validate if the designated
// constraints aren't met.
type GetSocialAuthNonceByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSocialAuthNonceByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSocialAuthNonceByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSocialAuthNonceByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSocialAuthNonceByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSocialAuthNonceByIDRequestValidationError) ErrorName() string {
	return "GetSocialAuthNonceByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSocialAuthNonceByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSocialAuthNonceByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSocialAuthNonceByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSocialAuthNonceByIDRequestValidationError{}

// Validate checks the field values on GetSocialAuthNonceByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSocialAuthNonceByIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSocialAuthNonceByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSocialAuthNonceByIDReplyMultiError, or nil if none found.
func (m *GetSocialAuthNonceByIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSocialAuthNonceByIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSocialAuthNonce()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSocialAuthNonceByIDReplyValidationError{
					field:  "SocialAuthNonce",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSocialAuthNonceByIDReplyValidationError{
					field:  "SocialAuthNonce",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSocialAuthNonce()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSocialAuthNonceByIDReplyValidationError{
				field:  "SocialAuthNonce",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetSocialAuthNonceByIDReplyMultiError(errors)
	}

	return nil
}

// GetSocialAuthNonceByIDReplyMultiError is an error wrapping multiple
// validation errors returned by GetSocialAuthNonceByIDReply.ValidateAll() if
// the designated constraints aren't met.
type GetSocialAuthNonceByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSocialAuthNonceByIDReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSocialAuthNonceByIDReplyMultiError) AllErrors() []error { return m }

// GetSocialAuthNonceByIDReplyValidationError is the validation error returned
// by GetSocialAuthNonceByIDReply.Validate if the designated constraints
// aren't met.
type GetSocialAuthNonceByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSocialAuthNonceByIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSocialAuthNonceByIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSocialAuthNonceByIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSocialAuthNonceByIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSocialAuthNonceByIDReplyValidationError) ErrorName() string {
	return "GetSocialAuthNonceByIDReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetSocialAuthNonceByIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSocialAuthNonceByIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSocialAuthNonceByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSocialAuthNonceByIDReplyValidationError{}

// Validate checks the field values on ListSocialAuthNonceRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSocialAuthNonceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSocialAuthNonceRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSocialAuthNonceRequestMultiError, or nil if none found.
func (m *ListSocialAuthNonceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSocialAuthNonceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetParams()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListSocialAuthNonceRequestValidationError{
					field:  "Params",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListSocialAuthNonceRequestValidationError{
					field:  "Params",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetParams()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListSocialAuthNonceRequestValidationError{
				field:  "Params",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListSocialAuthNonceRequestMultiError(errors)
	}

	return nil
}

// ListSocialAuthNonceRequestMultiError is an error wrapping multiple
// validation errors returned by ListSocialAuthNonceRequest.ValidateAll() if
// the designated constraints aren't met.
type ListSocialAuthNonceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSocialAuthNonceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSocialAuthNonceRequestMultiError) AllErrors() []error { return m }

// ListSocialAuthNonceRequestValidationError is the validation error returned
// by ListSocialAuthNonceRequest.Validate if the designated constraints aren't met.
type ListSocialAuthNonceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSocialAuthNonceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSocialAuthNonceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSocialAuthNonceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSocialAuthNonceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSocialAuthNonceRequestValidationError) ErrorName() string {
	return "ListSocialAuthNonceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListSocialAuthNonceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSocialAuthNonceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSocialAuthNonceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSocialAuthNonceRequestValidationError{}

// Validate checks the field values on ListSocialAuthNonceReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSocialAuthNonceReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSocialAuthNonceReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSocialAuthNonceReplyMultiError, or nil if none found.
func (m *ListSocialAuthNonceReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSocialAuthNonceReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetSocialAuthNonces() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListSocialAuthNonceReplyValidationError{
						field:  fmt.Sprintf("SocialAuthNonces[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListSocialAuthNonceReplyValidationError{
						field:  fmt.Sprintf("SocialAuthNonces[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListSocialAuthNonceReplyValidationError{
					field:  fmt.Sprintf("SocialAuthNonces[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListSocialAuthNonceReplyMultiError(errors)
	}

	return nil
}

// ListSocialAuthNonceReplyMultiError is an error wrapping multiple validation
// errors returned by ListSocialAuthNonceReply.ValidateAll() if the designated
// constraints aren't met.
type ListSocialAuthNonceReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSocialAuthNonceReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSocialAuthNonceReplyMultiError) AllErrors() []error { return m }

// ListSocialAuthNonceReplyValidationError is the validation error returned by
// ListSocialAuthNonceReply.Validate if the designated constraints aren't met.
type ListSocialAuthNonceReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSocialAuthNonceReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSocialAuthNonceReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSocialAuthNonceReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSocialAuthNonceReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSocialAuthNonceReplyValidationError) ErrorName() string {
	return "ListSocialAuthNonceReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListSocialAuthNonceReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSocialAuthNonceReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSocialAuthNonceReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSocialAuthNonceReplyValidationError{}

// Validate checks the field values on DeleteSocialAuthNonceByIDsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *DeleteSocialAuthNonceByIDsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSocialAuthNonceByIDsRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// DeleteSocialAuthNonceByIDsRequestMultiError, or nil if none found.
func (m *DeleteSocialAuthNonceByIDsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSocialAuthNonceByIDsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetIds()) < 1 {
		err := DeleteSocialAuthNonceByIDsRequestValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteSocialAuthNonceByIDsRequestMultiError(errors)
	}

	return nil
}

// DeleteSocialAuthNonceByIDsRequestMultiError is an error wrapping multiple
// validation errors returned by
// DeleteSocialAuthNonceByIDsRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteSocialAuthNonceByIDsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSocialAuthNonceByIDsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSocialAuthNonceByIDsRequestMultiError) AllErrors() []error { return m }

// DeleteSocialAuthNonceByIDsRequestValidationError is the validation error
// returned by DeleteSocialAuthNonceByIDsRequest.Validate if the designated
// constraints aren't met.
type DeleteSocialAuthNonceByIDsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSocialAuthNonceByIDsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSocialAuthNonceByIDsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSocialAuthNonceByIDsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSocialAuthNonceByIDsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSocialAuthNonceByIDsRequestValidationError) ErrorName() string {
	return "DeleteSocialAuthNonceByIDsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSocialAuthNonceByIDsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSocialAuthNonceByIDsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSocialAuthNonceByIDsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSocialAuthNonceByIDsRequestValidationError{}

// Validate checks the field values on DeleteSocialAuthNonceByIDsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteSocialAuthNonceByIDsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSocialAuthNonceByIDsReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteSocialAuthNonceByIDsReplyMultiError, or nil if none found.
func (m *DeleteSocialAuthNonceByIDsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSocialAuthNonceByIDsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteSocialAuthNonceByIDsReplyMultiError(errors)
	}

	return nil
}

// DeleteSocialAuthNonceByIDsReplyMultiError is an error wrapping multiple
// validation errors returned by DeleteSocialAuthNonceByIDsReply.ValidateAll()
// if the designated constraints aren't met.
type DeleteSocialAuthNonceByIDsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSocialAuthNonceByIDsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSocialAuthNonceByIDsReplyMultiError) AllErrors() []error { return m }

// DeleteSocialAuthNonceByIDsReplyValidationError is the validation error
// returned by DeleteSocialAuthNonceByIDsReply.Validate if the designated
// constraints aren't met.
type DeleteSocialAuthNonceByIDsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSocialAuthNonceByIDsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSocialAuthNonceByIDsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSocialAuthNonceByIDsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSocialAuthNonceByIDsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSocialAuthNonceByIDsReplyValidationError) ErrorName() string {
	return "DeleteSocialAuthNonceByIDsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSocialAuthNonceByIDsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSocialAuthNonceByIDsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSocialAuthNonceByIDsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSocialAuthNonceByIDsReplyValidationError{}

// Validate checks the field values on GetSocialAuthNonceByConditionRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *GetSocialAuthNonceByConditionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSocialAuthNonceByConditionRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetSocialAuthNonceByConditionRequestMultiError, or nil if none found.
func (m *GetSocialAuthNonceByConditionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSocialAuthNonceByConditionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConditions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSocialAuthNonceByConditionRequestValidationError{
					field:  "Conditions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSocialAuthNonceByConditionRequestValidationError{
					field:  "Conditions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConditions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSocialAuthNonceByConditionRequestValidationError{
				field:  "Conditions",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetSocialAuthNonceByConditionRequestMultiError(errors)
	}

	return nil
}

// GetSocialAuthNonceByConditionRequestMultiError is an error wrapping multiple
// validation errors returned by
// GetSocialAuthNonceByConditionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetSocialAuthNonceByConditionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSocialAuthNonceByConditionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSocialAuthNonceByConditionRequestMultiError) AllErrors() []error { return m }

// GetSocialAuthNonceByConditionRequestValidationError is the validation error
// returned by GetSocialAuthNonceByConditionRequest.Validate if the designated
// constraints aren't met.
type GetSocialAuthNonceByConditionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSocialAuthNonceByConditionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSocialAuthNonceByConditionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSocialAuthNonceByConditionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSocialAuthNonceByConditionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSocialAuthNonceByConditionRequestValidationError) ErrorName() string {
	return "GetSocialAuthNonceByConditionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSocialAuthNonceByConditionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSocialAuthNonceByConditionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSocialAuthNonceByConditionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSocialAuthNonceByConditionRequestValidationError{}

// Validate checks the field values on GetSocialAuthNonceByConditionReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetSocialAuthNonceByConditionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSocialAuthNonceByConditionReply
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetSocialAuthNonceByConditionReplyMultiError, or nil if none found.
func (m *GetSocialAuthNonceByConditionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSocialAuthNonceByConditionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSocialAuthNonce()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSocialAuthNonceByConditionReplyValidationError{
					field:  "SocialAuthNonce",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSocialAuthNonceByConditionReplyValidationError{
					field:  "SocialAuthNonce",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSocialAuthNonce()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSocialAuthNonceByConditionReplyValidationError{
				field:  "SocialAuthNonce",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetSocialAuthNonceByConditionReplyMultiError(errors)
	}

	return nil
}

// GetSocialAuthNonceByConditionReplyMultiError is an error wrapping multiple
// validation errors returned by
// GetSocialAuthNonceByConditionReply.ValidateAll() if the designated
// constraints aren't met.
type GetSocialAuthNonceByConditionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSocialAuthNonceByConditionReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSocialAuthNonceByConditionReplyMultiError) AllErrors() []error { return m }

// GetSocialAuthNonceByConditionReplyValidationError is the validation error
// returned by GetSocialAuthNonceByConditionReply.Validate if the designated
// constraints aren't met.
type GetSocialAuthNonceByConditionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSocialAuthNonceByConditionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSocialAuthNonceByConditionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSocialAuthNonceByConditionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSocialAuthNonceByConditionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSocialAuthNonceByConditionReplyValidationError) ErrorName() string {
	return "GetSocialAuthNonceByConditionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetSocialAuthNonceByConditionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSocialAuthNonceByConditionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSocialAuthNonceByConditionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSocialAuthNonceByConditionReplyValidationError{}

// Validate checks the field values on ListSocialAuthNonceByIDsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSocialAuthNonceByIDsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSocialAuthNonceByIDsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListSocialAuthNonceByIDsRequestMultiError, or nil if none found.
func (m *ListSocialAuthNonceByIDsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSocialAuthNonceByIDsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetIds()) < 1 {
		err := ListSocialAuthNonceByIDsRequestValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListSocialAuthNonceByIDsRequestMultiError(errors)
	}

	return nil
}

// ListSocialAuthNonceByIDsRequestMultiError is an error wrapping multiple
// validation errors returned by ListSocialAuthNonceByIDsRequest.ValidateAll()
// if the designated constraints aren't met.
type ListSocialAuthNonceByIDsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSocialAuthNonceByIDsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSocialAuthNonceByIDsRequestMultiError) AllErrors() []error { return m }

// ListSocialAuthNonceByIDsRequestValidationError is the validation error
// returned by ListSocialAuthNonceByIDsRequest.Validate if the designated
// constraints aren't met.
type ListSocialAuthNonceByIDsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSocialAuthNonceByIDsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSocialAuthNonceByIDsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSocialAuthNonceByIDsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSocialAuthNonceByIDsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSocialAuthNonceByIDsRequestValidationError) ErrorName() string {
	return "ListSocialAuthNonceByIDsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListSocialAuthNonceByIDsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSocialAuthNonceByIDsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSocialAuthNonceByIDsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSocialAuthNonceByIDsRequestValidationError{}

// Validate checks the field values on ListSocialAuthNonceByIDsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSocialAuthNonceByIDsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSocialAuthNonceByIDsReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListSocialAuthNonceByIDsReplyMultiError, or nil if none found.
func (m *ListSocialAuthNonceByIDsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSocialAuthNonceByIDsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSocialAuthNonces() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListSocialAuthNonceByIDsReplyValidationError{
						field:  fmt.Sprintf("SocialAuthNonces[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListSocialAuthNonceByIDsReplyValidationError{
						field:  fmt.Sprintf("SocialAuthNonces[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListSocialAuthNonceByIDsReplyValidationError{
					field:  fmt.Sprintf("SocialAuthNonces[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListSocialAuthNonceByIDsReplyMultiError(errors)
	}

	return nil
}

// ListSocialAuthNonceByIDsReplyMultiError is an error wrapping multiple
// validation errors returned by ListSocialAuthNonceByIDsReply.ValidateAll()
// if the designated constraints aren't met.
type ListSocialAuthNonceByIDsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSocialAuthNonceByIDsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSocialAuthNonceByIDsReplyMultiError) AllErrors() []error { return m }

// ListSocialAuthNonceByIDsReplyValidationError is the validation error
// returned by ListSocialAuthNonceByIDsReply.Validate if the designated
// constraints aren't met.
type ListSocialAuthNonceByIDsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSocialAuthNonceByIDsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSocialAuthNonceByIDsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSocialAuthNonceByIDsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSocialAuthNonceByIDsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSocialAuthNonceByIDsReplyValidationError) ErrorName() string {
	return "ListSocialAuthNonceByIDsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListSocialAuthNonceByIDsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSocialAuthNonceByIDsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSocialAuthNonceByIDsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSocialAuthNonceByIDsReplyValidationError{}

// Validate checks the field values on ListSocialAuthNonceByLastIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListSocialAuthNonceByLastIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSocialAuthNonceByLastIDRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ListSocialAuthNonceByLastIDRequestMultiError, or nil if none found.
func (m *ListSocialAuthNonceByLastIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSocialAuthNonceByLastIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LastID

	if m.GetLimit() <= 0 {
		err := ListSocialAuthNonceByLastIDRequestValidationError{
			field:  "Limit",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Sort

	if len(errors) > 0 {
		return ListSocialAuthNonceByLastIDRequestMultiError(errors)
	}

	return nil
}

// ListSocialAuthNonceByLastIDRequestMultiError is an error wrapping multiple
// validation errors returned by
// ListSocialAuthNonceByLastIDRequest.ValidateAll() if the designated
// constraints aren't met.
type ListSocialAuthNonceByLastIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSocialAuthNonceByLastIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSocialAuthNonceByLastIDRequestMultiError) AllErrors() []error { return m }

// ListSocialAuthNonceByLastIDRequestValidationError is the validation error
// returned by ListSocialAuthNonceByLastIDRequest.Validate if the designated
// constraints aren't met.
type ListSocialAuthNonceByLastIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSocialAuthNonceByLastIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSocialAuthNonceByLastIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSocialAuthNonceByLastIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSocialAuthNonceByLastIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSocialAuthNonceByLastIDRequestValidationError) ErrorName() string {
	return "ListSocialAuthNonceByLastIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListSocialAuthNonceByLastIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSocialAuthNonceByLastIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSocialAuthNonceByLastIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSocialAuthNonceByLastIDRequestValidationError{}

// Validate checks the field values on ListSocialAuthNonceByLastIDReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListSocialAuthNonceByLastIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSocialAuthNonceByLastIDReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListSocialAuthNonceByLastIDReplyMultiError, or nil if none found.
func (m *ListSocialAuthNonceByLastIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSocialAuthNonceByLastIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSocialAuthNonces() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListSocialAuthNonceByLastIDReplyValidationError{
						field:  fmt.Sprintf("SocialAuthNonces[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListSocialAuthNonceByLastIDReplyValidationError{
						field:  fmt.Sprintf("SocialAuthNonces[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListSocialAuthNonceByLastIDReplyValidationError{
					field:  fmt.Sprintf("SocialAuthNonces[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListSocialAuthNonceByLastIDReplyMultiError(errors)
	}

	return nil
}

// ListSocialAuthNonceByLastIDReplyMultiError is an error wrapping multiple
// validation errors returned by
// ListSocialAuthNonceByLastIDReply.ValidateAll() if the designated
// constraints aren't met.
type ListSocialAuthNonceByLastIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSocialAuthNonceByLastIDReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSocialAuthNonceByLastIDReplyMultiError) AllErrors() []error { return m }

// ListSocialAuthNonceByLastIDReplyValidationError is the validation error
// returned by ListSocialAuthNonceByLastIDReply.Validate if the designated
// constraints aren't met.
type ListSocialAuthNonceByLastIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSocialAuthNonceByLastIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSocialAuthNonceByLastIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSocialAuthNonceByLastIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSocialAuthNonceByLastIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSocialAuthNonceByLastIDReplyValidationError) ErrorName() string {
	return "ListSocialAuthNonceByLastIDReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListSocialAuthNonceByLastIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSocialAuthNonceByLastIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSocialAuthNonceByLastIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSocialAuthNonceByLastIDReplyValidationError{}
