syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service taggitTag {
  // Create a new taggitTag
  rpc Create(CreateTaggitTagRequest) returns (CreateTaggitTagReply) {
    option (google.api.http) = {
      post: "/api/taggit/tags"
      body: "*"
    };
  }

  // Delete a taggitTag by id
  rpc DeleteByID(DeleteTaggitTagByIDRequest) returns (DeleteTaggitTagByIDReply) {
    option (google.api.http) = {
      delete: "/api/taggit/tags/{id}"
    };
  }

  // Update a taggitTag by id
  rpc UpdateByID(UpdateTaggitTagByIDRequest) returns (UpdateTaggitTagByIDReply) {
    option (google.api.http) = {
      put: "/api/taggit/tags/{id}"
      body: "*"
    };
  }

  // Get a taggitTag by id
  rpc GetByID(GetTaggitTagByIDRequest) returns (GetTaggitTagByIDReply) {
    option (google.api.http) = {
      get: "/api/taggit/tags/{id}"
    };
  }

  // Get a paginated list of taggitTag by custom conditions
  rpc List(ListTaggitTagRequest) returns (ListTaggitTagReply) {
    option (google.api.http) = {
      post: "/api/taggit/tags/list"
      body: "*"
    };
  }

  // Batch delete taggitTag by ids
  rpc DeleteByIDs(DeleteTaggitTagByIDsRequest) returns (DeleteTaggitTagByIDsReply) {
    option (google.api.http) = {
      post: "/api/taggit/tags/delete/ids"
      body: "*"
    };
  }

  // Get a taggitTag by custom condition
  rpc GetByCondition(GetTaggitTagByConditionRequest) returns (GetTaggitTagByConditionReply) {
    option (google.api.http) = {
      post: "/api/taggit/tags/condition"
      body: "*"
    };
  }

  // Batch get taggitTag by ids
  rpc ListByIDs(ListTaggitTagByIDsRequest) returns (ListTaggitTagByIDsReply) {
    option (google.api.http) = {
      post: "/api/taggit/tags/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of taggitTag by last id
  rpc ListByLastID(ListTaggitTagByLastIDRequest) returns (ListTaggitTagByLastIDReply) {
    option (google.api.http) = {
      get: "/api/taggit/tags"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/taggitTag/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getTaggitTag?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateTaggitTagRequest {
	string name = 1; 
	string slug = 2; 
}

message CreateTaggitTagReply {
  uint64 id = 1;
}

message DeleteTaggitTagByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteTaggitTagByIDReply {

}

message UpdateTaggitTagByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string name = 2; 
	string slug = 3; 
}

message UpdateTaggitTagByIDReply {

}

message TaggitTag {
	uint64 id = 1; 
	string name = 2; 
	string slug = 3; 
}

message GetTaggitTagByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetTaggitTagByIDReply {
  TaggitTag taggitTag = 1;
}

message ListTaggitTagRequest {
  api.types.Params params = 1;
}

message ListTaggitTagReply {
  int64 total = 1;
  repeated TaggitTag taggitTags = 2;
}

message DeleteTaggitTagByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteTaggitTagByIDsReply {

}

message GetTaggitTagByConditionRequest {
  types.Conditions conditions = 1;
}

message GetTaggitTagByConditionReply {
  TaggitTag taggitTag = 1;
}

message ListTaggitTagByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListTaggitTagByIDsReply {
  repeated TaggitTag taggitTags = 1;
}

message ListTaggitTagByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListTaggitTagByLastIDReply {
  repeated TaggitTag taggitTags = 1;
}


