syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service tenancyContactassignment {
  // Create a new tenancyContactassignment
  rpc Create(CreateTenancyContactassignmentRequest) returns (CreateTenancyContactassignmentReply) {
    option (google.api.http) = {
      post: "/api/tenancy/contactassignments"
      body: "*"
    };
  }

  // Delete a tenancyContactassignment by id
  rpc DeleteByID(DeleteTenancyContactassignmentByIDRequest) returns (DeleteTenancyContactassignmentByIDReply) {
    option (google.api.http) = {
      delete: "/api/tenancy/contactassignments/{id}"
    };
  }

  // Update a tenancyContactassignment by id
  rpc UpdateByID(UpdateTenancyContactassignmentByIDRequest) returns (UpdateTenancyContactassignmentByIDReply) {
    option (google.api.http) = {
      put: "/api/tenancy/contactassignments/{id}"
      body: "*"
    };
  }

  // Get a tenancyContactassignment by id
  rpc GetByID(GetTenancyContactassignmentByIDRequest) returns (GetTenancyContactassignmentByIDReply) {
    option (google.api.http) = {
      get: "/api/tenancy/contactassignments/{id}"
    };
  }

  // Get a paginated list of tenancyContactassignment by custom conditions
  rpc List(ListTenancyContactassignmentRequest) returns (ListTenancyContactassignmentReply) {
    option (google.api.http) = {
      post: "/api/tenancy/contactassignments/list"
      body: "*"
    };
  }

  // Batch delete tenancyContactassignment by ids
  rpc DeleteByIDs(DeleteTenancyContactassignmentByIDsRequest) returns (DeleteTenancyContactassignmentByIDsReply) {
    option (google.api.http) = {
      post: "/api/tenancy/contactassignments/delete/ids"
      body: "*"
    };
  }

  // Get a tenancyContactassignment by custom condition
  rpc GetByCondition(GetTenancyContactassignmentByConditionRequest) returns (GetTenancyContactassignmentByConditionReply) {
    option (google.api.http) = {
      post: "/api/tenancy/contactassignments/condition"
      body: "*"
    };
  }

  // Batch get tenancyContactassignment by ids
  rpc ListByIDs(ListTenancyContactassignmentByIDsRequest) returns (ListTenancyContactassignmentByIDsReply) {
    option (google.api.http) = {
      post: "/api/tenancy/contactassignments/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of tenancyContactassignment by last id
  rpc ListByLastID(ListTenancyContactassignmentByLastIDRequest) returns (ListTenancyContactassignmentByLastIDReply) {
    option (google.api.http) = {
      get: "/api/tenancy/contactassignments"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/tenancyContactassignment/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getTenancyContactassignment?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateTenancyContactassignmentRequest {
	string created = 1; 
	string lastUpdated = 2; 
	int64 objectID = 3; 
	string priority = 4; 
	int64 contactID = 5; 
	int32 objectTypeID = 6; 
	int64 roleID = 7; 
	string customFieldData = 8; 
}

message CreateTenancyContactassignmentReply {
  uint64 id = 1;
}

message DeleteTenancyContactassignmentByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteTenancyContactassignmentByIDReply {

}

message UpdateTenancyContactassignmentByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string created = 2; 
	string lastUpdated = 3; 
	int64 objectID = 4; 
	string priority = 5; 
	int64 contactID = 6; 
	int32 objectTypeID = 7; 
	int64 roleID = 8; 
	string customFieldData = 9; 
}

message UpdateTenancyContactassignmentByIDReply {

}

message TenancyContactassignment {
	uint64 id = 1; 
	string created = 2; 
	string lastUpdated = 3; 
	int64 objectID = 4; 
	string priority = 5; 
	int64 contactID = 6; 
	int32 objectTypeID = 7; 
	int64 roleID = 8; 
	string customFieldData = 9; 
}

message GetTenancyContactassignmentByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetTenancyContactassignmentByIDReply {
  TenancyContactassignment tenancyContactassignment = 1;
}

message ListTenancyContactassignmentRequest {
  api.types.Params params = 1;
}

message ListTenancyContactassignmentReply {
  int64 total = 1;
  repeated TenancyContactassignment tenancyContactassignments = 2;
}

message DeleteTenancyContactassignmentByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteTenancyContactassignmentByIDsReply {

}

message GetTenancyContactassignmentByConditionRequest {
  types.Conditions conditions = 1;
}

message GetTenancyContactassignmentByConditionReply {
  TenancyContactassignment tenancyContactassignment = 1;
}

message ListTenancyContactassignmentByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListTenancyContactassignmentByIDsReply {
  repeated TenancyContactassignment tenancyContactassignments = 1;
}

message ListTenancyContactassignmentByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListTenancyContactassignmentByLastIDReply {
  repeated TenancyContactassignment tenancyContactassignments = 1;
}


