// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/netbox_go/v1/usersGroupPermissions.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "netbox-go/api/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUsersGroupPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       int64                  `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID"`
	PermissionID  int32                  `protobuf:"varint,2,opt,name=permissionID,proto3" json:"permissionID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUsersGroupPermissionsRequest) Reset() {
	*x = CreateUsersGroupPermissionsRequest{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUsersGroupPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUsersGroupPermissionsRequest) ProtoMessage() {}

func (x *CreateUsersGroupPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUsersGroupPermissionsRequest.ProtoReflect.Descriptor instead.
func (*CreateUsersGroupPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUsersGroupPermissionsRequest) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *CreateUsersGroupPermissionsRequest) GetPermissionID() int32 {
	if x != nil {
		return x.PermissionID
	}
	return 0
}

type CreateUsersGroupPermissionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUsersGroupPermissionsReply) Reset() {
	*x = CreateUsersGroupPermissionsReply{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUsersGroupPermissionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUsersGroupPermissionsReply) ProtoMessage() {}

func (x *CreateUsersGroupPermissionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUsersGroupPermissionsReply.ProtoReflect.Descriptor instead.
func (*CreateUsersGroupPermissionsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUsersGroupPermissionsReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUsersGroupPermissionsByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUsersGroupPermissionsByIDRequest) Reset() {
	*x = DeleteUsersGroupPermissionsByIDRequest{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUsersGroupPermissionsByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUsersGroupPermissionsByIDRequest) ProtoMessage() {}

func (x *DeleteUsersGroupPermissionsByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUsersGroupPermissionsByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteUsersGroupPermissionsByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUsersGroupPermissionsByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUsersGroupPermissionsByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUsersGroupPermissionsByIDReply) Reset() {
	*x = DeleteUsersGroupPermissionsByIDReply{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUsersGroupPermissionsByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUsersGroupPermissionsByIDReply) ProtoMessage() {}

func (x *DeleteUsersGroupPermissionsByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUsersGroupPermissionsByIDReply.ProtoReflect.Descriptor instead.
func (*DeleteUsersGroupPermissionsByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{3}
}

type UpdateUsersGroupPermissionsByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	GroupID       int64                  `protobuf:"varint,2,opt,name=groupID,proto3" json:"groupID"`
	PermissionID  int32                  `protobuf:"varint,3,opt,name=permissionID,proto3" json:"permissionID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsersGroupPermissionsByIDRequest) Reset() {
	*x = UpdateUsersGroupPermissionsByIDRequest{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsersGroupPermissionsByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsersGroupPermissionsByIDRequest) ProtoMessage() {}

func (x *UpdateUsersGroupPermissionsByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsersGroupPermissionsByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsersGroupPermissionsByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUsersGroupPermissionsByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUsersGroupPermissionsByIDRequest) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *UpdateUsersGroupPermissionsByIDRequest) GetPermissionID() int32 {
	if x != nil {
		return x.PermissionID
	}
	return 0
}

type UpdateUsersGroupPermissionsByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsersGroupPermissionsByIDReply) Reset() {
	*x = UpdateUsersGroupPermissionsByIDReply{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsersGroupPermissionsByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsersGroupPermissionsByIDReply) ProtoMessage() {}

func (x *UpdateUsersGroupPermissionsByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsersGroupPermissionsByIDReply.ProtoReflect.Descriptor instead.
func (*UpdateUsersGroupPermissionsByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{5}
}

type UsersGroupPermissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	GroupID       int64                  `protobuf:"varint,2,opt,name=groupID,proto3" json:"groupID"`
	PermissionID  int32                  `protobuf:"varint,3,opt,name=permissionID,proto3" json:"permissionID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersGroupPermissions) Reset() {
	*x = UsersGroupPermissions{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersGroupPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersGroupPermissions) ProtoMessage() {}

func (x *UsersGroupPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersGroupPermissions.ProtoReflect.Descriptor instead.
func (*UsersGroupPermissions) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{6}
}

func (x *UsersGroupPermissions) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UsersGroupPermissions) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *UsersGroupPermissions) GetPermissionID() int32 {
	if x != nil {
		return x.PermissionID
	}
	return 0
}

type GetUsersGroupPermissionsByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersGroupPermissionsByIDRequest) Reset() {
	*x = GetUsersGroupPermissionsByIDRequest{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersGroupPermissionsByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersGroupPermissionsByIDRequest) ProtoMessage() {}

func (x *GetUsersGroupPermissionsByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersGroupPermissionsByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUsersGroupPermissionsByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsersGroupPermissionsByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUsersGroupPermissionsByIDReply struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UsersGroupPermissions *UsersGroupPermissions `protobuf:"bytes,1,opt,name=usersGroupPermissions,proto3" json:"usersGroupPermissions"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetUsersGroupPermissionsByIDReply) Reset() {
	*x = GetUsersGroupPermissionsByIDReply{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersGroupPermissionsByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersGroupPermissionsByIDReply) ProtoMessage() {}

func (x *GetUsersGroupPermissionsByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersGroupPermissionsByIDReply.ProtoReflect.Descriptor instead.
func (*GetUsersGroupPermissionsByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{8}
}

func (x *GetUsersGroupPermissionsByIDReply) GetUsersGroupPermissions() *UsersGroupPermissions {
	if x != nil {
		return x.UsersGroupPermissions
	}
	return nil
}

type ListUsersGroupPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *types.Params          `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersGroupPermissionsRequest) Reset() {
	*x = ListUsersGroupPermissionsRequest{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersGroupPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersGroupPermissionsRequest) ProtoMessage() {}

func (x *ListUsersGroupPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersGroupPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListUsersGroupPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsersGroupPermissionsRequest) GetParams() *types.Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type ListUsersGroupPermissionsReply struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	Total                  int64                    `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	UsersGroupPermissionss []*UsersGroupPermissions `protobuf:"bytes,2,rep,name=usersGroupPermissionss,proto3" json:"usersGroupPermissionss"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListUsersGroupPermissionsReply) Reset() {
	*x = ListUsersGroupPermissionsReply{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersGroupPermissionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersGroupPermissionsReply) ProtoMessage() {}

func (x *ListUsersGroupPermissionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersGroupPermissionsReply.ProtoReflect.Descriptor instead.
func (*ListUsersGroupPermissionsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{10}
}

func (x *ListUsersGroupPermissionsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersGroupPermissionsReply) GetUsersGroupPermissionss() []*UsersGroupPermissions {
	if x != nil {
		return x.UsersGroupPermissionss
	}
	return nil
}

type DeleteUsersGroupPermissionsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUsersGroupPermissionsByIDsRequest) Reset() {
	*x = DeleteUsersGroupPermissionsByIDsRequest{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUsersGroupPermissionsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUsersGroupPermissionsByIDsRequest) ProtoMessage() {}

func (x *DeleteUsersGroupPermissionsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUsersGroupPermissionsByIDsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUsersGroupPermissionsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUsersGroupPermissionsByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteUsersGroupPermissionsByIDsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUsersGroupPermissionsByIDsReply) Reset() {
	*x = DeleteUsersGroupPermissionsByIDsReply{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUsersGroupPermissionsByIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUsersGroupPermissionsByIDsReply) ProtoMessage() {}

func (x *DeleteUsersGroupPermissionsByIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUsersGroupPermissionsByIDsReply.ProtoReflect.Descriptor instead.
func (*DeleteUsersGroupPermissionsByIDsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{12}
}

type GetUsersGroupPermissionsByConditionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    *types.Conditions      `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersGroupPermissionsByConditionRequest) Reset() {
	*x = GetUsersGroupPermissionsByConditionRequest{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersGroupPermissionsByConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersGroupPermissionsByConditionRequest) ProtoMessage() {}

func (x *GetUsersGroupPermissionsByConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersGroupPermissionsByConditionRequest.ProtoReflect.Descriptor instead.
func (*GetUsersGroupPermissionsByConditionRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{13}
}

func (x *GetUsersGroupPermissionsByConditionRequest) GetConditions() *types.Conditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type GetUsersGroupPermissionsByConditionReply struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UsersGroupPermissions *UsersGroupPermissions `protobuf:"bytes,1,opt,name=usersGroupPermissions,proto3" json:"usersGroupPermissions"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetUsersGroupPermissionsByConditionReply) Reset() {
	*x = GetUsersGroupPermissionsByConditionReply{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersGroupPermissionsByConditionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersGroupPermissionsByConditionReply) ProtoMessage() {}

func (x *GetUsersGroupPermissionsByConditionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersGroupPermissionsByConditionReply.ProtoReflect.Descriptor instead.
func (*GetUsersGroupPermissionsByConditionReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{14}
}

func (x *GetUsersGroupPermissionsByConditionReply) GetUsersGroupPermissions() *UsersGroupPermissions {
	if x != nil {
		return x.UsersGroupPermissions
	}
	return nil
}

type ListUsersGroupPermissionsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersGroupPermissionsByIDsRequest) Reset() {
	*x = ListUsersGroupPermissionsByIDsRequest{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersGroupPermissionsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersGroupPermissionsByIDsRequest) ProtoMessage() {}

func (x *ListUsersGroupPermissionsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersGroupPermissionsByIDsRequest.ProtoReflect.Descriptor instead.
func (*ListUsersGroupPermissionsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{15}
}

func (x *ListUsersGroupPermissionsByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListUsersGroupPermissionsByIDsReply struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	UsersGroupPermissionss []*UsersGroupPermissions `protobuf:"bytes,1,rep,name=usersGroupPermissionss,proto3" json:"usersGroupPermissionss"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListUsersGroupPermissionsByIDsReply) Reset() {
	*x = ListUsersGroupPermissionsByIDsReply{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersGroupPermissionsByIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersGroupPermissionsByIDsReply) ProtoMessage() {}

func (x *ListUsersGroupPermissionsByIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersGroupPermissionsByIDsReply.ProtoReflect.Descriptor instead.
func (*ListUsersGroupPermissionsByIDsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{16}
}

func (x *ListUsersGroupPermissionsByIDsReply) GetUsersGroupPermissionss() []*UsersGroupPermissions {
	if x != nil {
		return x.UsersGroupPermissionss
	}
	return nil
}

type ListUsersGroupPermissionsByLastIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastID        uint64                 `protobuf:"varint,1,opt,name=lastID,proto3" json:"lastID" form:"lastID"` // last id
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit" form:"limit"`    // limit size per page
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort" form:"sort"`        // sort by column name of table, default is -id, the - sign indicates descending order.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersGroupPermissionsByLastIDRequest) Reset() {
	*x = ListUsersGroupPermissionsByLastIDRequest{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersGroupPermissionsByLastIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersGroupPermissionsByLastIDRequest) ProtoMessage() {}

func (x *ListUsersGroupPermissionsByLastIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersGroupPermissionsByLastIDRequest.ProtoReflect.Descriptor instead.
func (*ListUsersGroupPermissionsByLastIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{17}
}

func (x *ListUsersGroupPermissionsByLastIDRequest) GetLastID() uint64 {
	if x != nil {
		return x.LastID
	}
	return 0
}

func (x *ListUsersGroupPermissionsByLastIDRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersGroupPermissionsByLastIDRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListUsersGroupPermissionsByLastIDReply struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	UsersGroupPermissionss []*UsersGroupPermissions `protobuf:"bytes,1,rep,name=usersGroupPermissionss,proto3" json:"usersGroupPermissionss"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListUsersGroupPermissionsByLastIDReply) Reset() {
	*x = ListUsersGroupPermissionsByLastIDReply{}
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersGroupPermissionsByLastIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersGroupPermissionsByLastIDReply) ProtoMessage() {}

func (x *ListUsersGroupPermissionsByLastIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersGroupPermissionsByLastIDReply.ProtoReflect.Descriptor instead.
func (*ListUsersGroupPermissionsByLastIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP(), []int{18}
}

func (x *ListUsersGroupPermissionsByLastIDReply) GetUsersGroupPermissionss() []*UsersGroupPermissions {
	if x != nil {
		return x.UsersGroupPermissionss
	}
	return nil
}

var File_api_netbox_go_v1_usersGroupPermissions_proto protoreflect.FileDescriptor

const file_api_netbox_go_v1_usersGroupPermissions_proto_rawDesc = "" +
	"\n" +
	",api/netbox_go/v1/usersGroupPermissions.proto\x12\x10api.netbox_go.v1\x1a\x15api/types/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x13tagger/tagger.proto\x1a\x17validate/validate.proto\"b\n" +
	"\"CreateUsersGroupPermissionsRequest\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\x03R\agroupID\x12\"\n" +
	"\fpermissionID\x18\x02 \x01(\x05R\fpermissionID\"2\n" +
	" CreateUsersGroupPermissionsReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"N\n" +
	"&DeleteUsersGroupPermissionsByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"&\n" +
	"$DeleteUsersGroupPermissionsByIDReply\"\x8c\x01\n" +
	"&UpdateUsersGroupPermissionsByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\x12\x18\n" +
	"\agroupID\x18\x02 \x01(\x03R\agroupID\x12\"\n" +
	"\fpermissionID\x18\x03 \x01(\x05R\fpermissionID\"&\n" +
	"$UpdateUsersGroupPermissionsByIDReply\"e\n" +
	"\x15UsersGroupPermissions\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\agroupID\x18\x02 \x01(\x03R\agroupID\x12\"\n" +
	"\fpermissionID\x18\x03 \x01(\x05R\fpermissionID\"K\n" +
	"#GetUsersGroupPermissionsByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"\x82\x01\n" +
	"!GetUsersGroupPermissionsByIDReply\x12]\n" +
	"\x15usersGroupPermissions\x18\x01 \x01(\v2'.api.netbox_go.v1.UsersGroupPermissionsR\x15usersGroupPermissions\"M\n" +
	" ListUsersGroupPermissionsRequest\x12)\n" +
	"\x06params\x18\x01 \x01(\v2\x11.api.types.ParamsR\x06params\"\x97\x01\n" +
	"\x1eListUsersGroupPermissionsReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12_\n" +
	"\x16usersGroupPermissionss\x18\x02 \x03(\v2'.api.netbox_go.v1.UsersGroupPermissionsR\x16usersGroupPermissionss\"E\n" +
	"'DeleteUsersGroupPermissionsByIDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"'\n" +
	"%DeleteUsersGroupPermissionsByIDsReply\"c\n" +
	"*GetUsersGroupPermissionsByConditionRequest\x125\n" +
	"\n" +
	"conditions\x18\x01 \x01(\v2\x15.api.types.ConditionsR\n" +
	"conditions\"\x89\x01\n" +
	"(GetUsersGroupPermissionsByConditionReply\x12]\n" +
	"\x15usersGroupPermissions\x18\x01 \x01(\v2'.api.netbox_go.v1.UsersGroupPermissionsR\x15usersGroupPermissions\"C\n" +
	"%ListUsersGroupPermissionsByIDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"\x86\x01\n" +
	"#ListUsersGroupPermissionsByIDsReply\x12_\n" +
	"\x16usersGroupPermissionss\x18\x01 \x03(\v2'.api.netbox_go.v1.UsersGroupPermissionsR\x16usersGroupPermissionss\"\xac\x01\n" +
	"(ListUsersGroupPermissionsByLastIDRequest\x12*\n" +
	"\x06lastID\x18\x01 \x01(\x04B\x12\x9a\x84\x9e\x03\rform:\"lastID\"R\x06lastID\x12.\n" +
	"\x05limit\x18\x02 \x01(\rB\x18\xfaB\x04*\x02 \x00\x9a\x84\x9e\x03\fform:\"limit\"R\x05limit\x12$\n" +
	"\x04sort\x18\x03 \x01(\tB\x10\x9a\x84\x9e\x03\vform:\"sort\"R\x04sort\"\x89\x01\n" +
	"&ListUsersGroupPermissionsByLastIDReply\x12_\n" +
	"\x16usersGroupPermissionss\x18\x01 \x03(\v2'.api.netbox_go.v1.UsersGroupPermissionsR\x16usersGroupPermissionss2\xc9\f\n" +
	"\x15usersGroupPermissions\x12\x9f\x01\n" +
	"\x06Create\x124.api.netbox_go.v1.CreateUsersGroupPermissionsRequest\x1a2.api.netbox_go.v1.CreateUsersGroupPermissionsReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/users/usersGroupPermissions\x12\xad\x01\n" +
	"\n" +
	"DeleteByID\x128.api.netbox_go.v1.DeleteUsersGroupPermissionsByIDRequest\x1a6.api.netbox_go.v1.DeleteUsersGroupPermissionsByIDReply\"-\x82\xd3\xe4\x93\x02'*%/api/users/usersGroupPermissions/{id}\x12\xb0\x01\n" +
	"\n" +
	"UpdateByID\x128.api.netbox_go.v1.UpdateUsersGroupPermissionsByIDRequest\x1a6.api.netbox_go.v1.UpdateUsersGroupPermissionsByIDReply\"0\x82\xd3\xe4\x93\x02*:\x01*\x1a%/api/users/usersGroupPermissions/{id}\x12\xa4\x01\n" +
	"\aGetByID\x125.api.netbox_go.v1.GetUsersGroupPermissionsByIDRequest\x1a3.api.netbox_go.v1.GetUsersGroupPermissionsByIDReply\"-\x82\xd3\xe4\x93\x02'\x12%/api/users/usersGroupPermissions/{id}\x12\x9e\x01\n" +
	"\x04List\x122.api.netbox_go.v1.ListUsersGroupPermissionsRequest\x1a0.api.netbox_go.v1.ListUsersGroupPermissionsReply\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/users/usersGroupPermissions/list\x12\xb9\x01\n" +
	"\vDeleteByIDs\x129.api.netbox_go.v1.DeleteUsersGroupPermissionsByIDsRequest\x1a7.api.netbox_go.v1.DeleteUsersGroupPermissionsByIDsReply\"6\x82\xd3\xe4\x93\x020:\x01*\"+/api/users/usersGroupPermissions/delete/ids\x12\xc1\x01\n" +
	"\x0eGetByCondition\x12<.api.netbox_go.v1.GetUsersGroupPermissionsByConditionRequest\x1a:.api.netbox_go.v1.GetUsersGroupPermissionsByConditionReply\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/api/users/usersGroupPermissions/condition\x12\xb1\x01\n" +
	"\tListByIDs\x127.api.netbox_go.v1.ListUsersGroupPermissionsByIDsRequest\x1a5.api.netbox_go.v1.ListUsersGroupPermissionsByIDsReply\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/users/usersGroupPermissions/list/ids\x12\xae\x01\n" +
	"\fListByLastID\x12:.api.netbox_go.v1.ListUsersGroupPermissionsByLastIDRequest\x1a8.api.netbox_go.v1.ListUsersGroupPermissionsByLastIDReply\"(\x82\xd3\xe4\x93\x02\"\x12 /api/users/usersGroupPermissionsB\xc3\x01\x92A\xa0\x01\x12\x1c\n" +
	"\x12netbox_go api docs2\x06v1.0.0\x1a\x0elocalhost:8080*\x02\x01\x022\x10application/json:\x10application/jsonZH\n" +
	"F\n" +
	"\n" +
	"BearerAuth\x128\b\x02\x12#Type Bearer your-jwt-token to Value\x1a\rAuthorization \x02Z\x1dnetbox-go/api/netbox_go/v1;v1b\x06proto3"

var (
	file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescOnce sync.Once
	file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescData []byte
)

func file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescGZIP() []byte {
	file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescOnce.Do(func() {
		file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_netbox_go_v1_usersGroupPermissions_proto_rawDesc), len(file_api_netbox_go_v1_usersGroupPermissions_proto_rawDesc)))
	})
	return file_api_netbox_go_v1_usersGroupPermissions_proto_rawDescData
}

var file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_netbox_go_v1_usersGroupPermissions_proto_goTypes = []any{
	(*CreateUsersGroupPermissionsRequest)(nil),         // 0: api.netbox_go.v1.CreateUsersGroupPermissionsRequest
	(*CreateUsersGroupPermissionsReply)(nil),           // 1: api.netbox_go.v1.CreateUsersGroupPermissionsReply
	(*DeleteUsersGroupPermissionsByIDRequest)(nil),     // 2: api.netbox_go.v1.DeleteUsersGroupPermissionsByIDRequest
	(*DeleteUsersGroupPermissionsByIDReply)(nil),       // 3: api.netbox_go.v1.DeleteUsersGroupPermissionsByIDReply
	(*UpdateUsersGroupPermissionsByIDRequest)(nil),     // 4: api.netbox_go.v1.UpdateUsersGroupPermissionsByIDRequest
	(*UpdateUsersGroupPermissionsByIDReply)(nil),       // 5: api.netbox_go.v1.UpdateUsersGroupPermissionsByIDReply
	(*UsersGroupPermissions)(nil),                      // 6: api.netbox_go.v1.UsersGroupPermissions
	(*GetUsersGroupPermissionsByIDRequest)(nil),        // 7: api.netbox_go.v1.GetUsersGroupPermissionsByIDRequest
	(*GetUsersGroupPermissionsByIDReply)(nil),          // 8: api.netbox_go.v1.GetUsersGroupPermissionsByIDReply
	(*ListUsersGroupPermissionsRequest)(nil),           // 9: api.netbox_go.v1.ListUsersGroupPermissionsRequest
	(*ListUsersGroupPermissionsReply)(nil),             // 10: api.netbox_go.v1.ListUsersGroupPermissionsReply
	(*DeleteUsersGroupPermissionsByIDsRequest)(nil),    // 11: api.netbox_go.v1.DeleteUsersGroupPermissionsByIDsRequest
	(*DeleteUsersGroupPermissionsByIDsReply)(nil),      // 12: api.netbox_go.v1.DeleteUsersGroupPermissionsByIDsReply
	(*GetUsersGroupPermissionsByConditionRequest)(nil), // 13: api.netbox_go.v1.GetUsersGroupPermissionsByConditionRequest
	(*GetUsersGroupPermissionsByConditionReply)(nil),   // 14: api.netbox_go.v1.GetUsersGroupPermissionsByConditionReply
	(*ListUsersGroupPermissionsByIDsRequest)(nil),      // 15: api.netbox_go.v1.ListUsersGroupPermissionsByIDsRequest
	(*ListUsersGroupPermissionsByIDsReply)(nil),        // 16: api.netbox_go.v1.ListUsersGroupPermissionsByIDsReply
	(*ListUsersGroupPermissionsByLastIDRequest)(nil),   // 17: api.netbox_go.v1.ListUsersGroupPermissionsByLastIDRequest
	(*ListUsersGroupPermissionsByLastIDReply)(nil),     // 18: api.netbox_go.v1.ListUsersGroupPermissionsByLastIDReply
	(*types.Params)(nil),                               // 19: api.types.Params
	(*types.Conditions)(nil),                           // 20: api.types.Conditions
}
var file_api_netbox_go_v1_usersGroupPermissions_proto_depIdxs = []int32{
	6,  // 0: api.netbox_go.v1.GetUsersGroupPermissionsByIDReply.usersGroupPermissions:type_name -> api.netbox_go.v1.UsersGroupPermissions
	19, // 1: api.netbox_go.v1.ListUsersGroupPermissionsRequest.params:type_name -> api.types.Params
	6,  // 2: api.netbox_go.v1.ListUsersGroupPermissionsReply.usersGroupPermissionss:type_name -> api.netbox_go.v1.UsersGroupPermissions
	20, // 3: api.netbox_go.v1.GetUsersGroupPermissionsByConditionRequest.conditions:type_name -> api.types.Conditions
	6,  // 4: api.netbox_go.v1.GetUsersGroupPermissionsByConditionReply.usersGroupPermissions:type_name -> api.netbox_go.v1.UsersGroupPermissions
	6,  // 5: api.netbox_go.v1.ListUsersGroupPermissionsByIDsReply.usersGroupPermissionss:type_name -> api.netbox_go.v1.UsersGroupPermissions
	6,  // 6: api.netbox_go.v1.ListUsersGroupPermissionsByLastIDReply.usersGroupPermissionss:type_name -> api.netbox_go.v1.UsersGroupPermissions
	0,  // 7: api.netbox_go.v1.usersGroupPermissions.Create:input_type -> api.netbox_go.v1.CreateUsersGroupPermissionsRequest
	2,  // 8: api.netbox_go.v1.usersGroupPermissions.DeleteByID:input_type -> api.netbox_go.v1.DeleteUsersGroupPermissionsByIDRequest
	4,  // 9: api.netbox_go.v1.usersGroupPermissions.UpdateByID:input_type -> api.netbox_go.v1.UpdateUsersGroupPermissionsByIDRequest
	7,  // 10: api.netbox_go.v1.usersGroupPermissions.GetByID:input_type -> api.netbox_go.v1.GetUsersGroupPermissionsByIDRequest
	9,  // 11: api.netbox_go.v1.usersGroupPermissions.List:input_type -> api.netbox_go.v1.ListUsersGroupPermissionsRequest
	11, // 12: api.netbox_go.v1.usersGroupPermissions.DeleteByIDs:input_type -> api.netbox_go.v1.DeleteUsersGroupPermissionsByIDsRequest
	13, // 13: api.netbox_go.v1.usersGroupPermissions.GetByCondition:input_type -> api.netbox_go.v1.GetUsersGroupPermissionsByConditionRequest
	15, // 14: api.netbox_go.v1.usersGroupPermissions.ListByIDs:input_type -> api.netbox_go.v1.ListUsersGroupPermissionsByIDsRequest
	17, // 15: api.netbox_go.v1.usersGroupPermissions.ListByLastID:input_type -> api.netbox_go.v1.ListUsersGroupPermissionsByLastIDRequest
	1,  // 16: api.netbox_go.v1.usersGroupPermissions.Create:output_type -> api.netbox_go.v1.CreateUsersGroupPermissionsReply
	3,  // 17: api.netbox_go.v1.usersGroupPermissions.DeleteByID:output_type -> api.netbox_go.v1.DeleteUsersGroupPermissionsByIDReply
	5,  // 18: api.netbox_go.v1.usersGroupPermissions.UpdateByID:output_type -> api.netbox_go.v1.UpdateUsersGroupPermissionsByIDReply
	8,  // 19: api.netbox_go.v1.usersGroupPermissions.GetByID:output_type -> api.netbox_go.v1.GetUsersGroupPermissionsByIDReply
	10, // 20: api.netbox_go.v1.usersGroupPermissions.List:output_type -> api.netbox_go.v1.ListUsersGroupPermissionsReply
	12, // 21: api.netbox_go.v1.usersGroupPermissions.DeleteByIDs:output_type -> api.netbox_go.v1.DeleteUsersGroupPermissionsByIDsReply
	14, // 22: api.netbox_go.v1.usersGroupPermissions.GetByCondition:output_type -> api.netbox_go.v1.GetUsersGroupPermissionsByConditionReply
	16, // 23: api.netbox_go.v1.usersGroupPermissions.ListByIDs:output_type -> api.netbox_go.v1.ListUsersGroupPermissionsByIDsReply
	18, // 24: api.netbox_go.v1.usersGroupPermissions.ListByLastID:output_type -> api.netbox_go.v1.ListUsersGroupPermissionsByLastIDReply
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_netbox_go_v1_usersGroupPermissions_proto_init() }
func file_api_netbox_go_v1_usersGroupPermissions_proto_init() {
	if File_api_netbox_go_v1_usersGroupPermissions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_netbox_go_v1_usersGroupPermissions_proto_rawDesc), len(file_api_netbox_go_v1_usersGroupPermissions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_netbox_go_v1_usersGroupPermissions_proto_goTypes,
		DependencyIndexes: file_api_netbox_go_v1_usersGroupPermissions_proto_depIdxs,
		MessageInfos:      file_api_netbox_go_v1_usersGroupPermissions_proto_msgTypes,
	}.Build()
	File_api_netbox_go_v1_usersGroupPermissions_proto = out.File
	file_api_netbox_go_v1_usersGroupPermissions_proto_goTypes = nil
	file_api_netbox_go_v1_usersGroupPermissions_proto_depIdxs = nil
}
