syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service usersObjectpermission {
  // Create a new usersObjectpermission
  rpc Create(CreateUsersObjectpermissionRequest) returns (CreateUsersObjectpermissionReply) {
    option (google.api.http) = {
      post: "/api/users/objectpermissions"
      body: "*"
    };
  }

  // Delete a usersObjectpermission by id
  rpc DeleteByID(DeleteUsersObjectpermissionByIDRequest) returns (DeleteUsersObjectpermissionByIDReply) {
    option (google.api.http) = {
      delete: "/api/users/objectpermissions/{id}"
    };
  }

  // Update a usersObjectpermission by id
  rpc UpdateByID(UpdateUsersObjectpermissionByIDRequest) returns (UpdateUsersObjectpermissionByIDReply) {
    option (google.api.http) = {
      put: "/api/users/objectpermissions/{id}"
      body: "*"
    };
  }

  // Get a usersObjectpermission by id
  rpc GetByID(GetUsersObjectpermissionByIDRequest) returns (GetUsersObjectpermissionByIDReply) {
    option (google.api.http) = {
      get: "/api/users/objectpermissions/{id}"
    };
  }

  // Get a paginated list of usersObjectpermission by custom conditions
  rpc List(ListUsersObjectpermissionRequest) returns (ListUsersObjectpermissionReply) {
    option (google.api.http) = {
      post: "/api/users/objectpermissions/list"
      body: "*"
    };
  }

  // Batch delete usersObjectpermission by ids
  rpc DeleteByIDs(DeleteUsersObjectpermissionByIDsRequest) returns (DeleteUsersObjectpermissionByIDsReply) {
    option (google.api.http) = {
      post: "/api/users/objectpermissions/delete/ids"
      body: "*"
    };
  }

  // Get a usersObjectpermission by custom condition
  rpc GetByCondition(GetUsersObjectpermissionByConditionRequest) returns (GetUsersObjectpermissionByConditionReply) {
    option (google.api.http) = {
      post: "/api/users/objectpermissions/condition"
      body: "*"
    };
  }

  // Batch get usersObjectpermission by ids
  rpc ListByIDs(ListUsersObjectpermissionByIDsRequest) returns (ListUsersObjectpermissionByIDsReply) {
    option (google.api.http) = {
      post: "/api/users/objectpermissions/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of usersObjectpermission by last id
  rpc ListByLastID(ListUsersObjectpermissionByLastIDRequest) returns (ListUsersObjectpermissionByLastIDReply) {
    option (google.api.http) = {
      get: "/api/users/objectpermissions"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/usersObjectpermission/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getUsersObjectpermission?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateUsersObjectpermissionRequest {
	string name = 1; 
	string description = 2; 
	bool enabled = 3; 
	string actions = 4; 
	string constraints = 5; 
}

message CreateUsersObjectpermissionReply {
  uint64 id = 1;
}

message DeleteUsersObjectpermissionByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteUsersObjectpermissionByIDReply {

}

message UpdateUsersObjectpermissionByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string name = 2; 
	string description = 3; 
	bool enabled = 4; 
	string actions = 5; 
	string constraints = 6; 
}

message UpdateUsersObjectpermissionByIDReply {

}

message UsersObjectpermission {
	uint64 id = 1; 
	string name = 2; 
	string description = 3; 
	bool enabled = 4; 
	string actions = 5; 
	string constraints = 6; 
}

message GetUsersObjectpermissionByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetUsersObjectpermissionByIDReply {
  UsersObjectpermission usersObjectpermission = 1;
}

message ListUsersObjectpermissionRequest {
  api.types.Params params = 1;
}

message ListUsersObjectpermissionReply {
  int64 total = 1;
  repeated UsersObjectpermission usersObjectpermissions = 2;
}

message DeleteUsersObjectpermissionByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteUsersObjectpermissionByIDsReply {

}

message GetUsersObjectpermissionByConditionRequest {
  types.Conditions conditions = 1;
}

message GetUsersObjectpermissionByConditionReply {
  UsersObjectpermission usersObjectpermission = 1;
}

message ListUsersObjectpermissionByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListUsersObjectpermissionByIDsReply {
  repeated UsersObjectpermission usersObjectpermissions = 1;
}

message ListUsersObjectpermissionByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListUsersObjectpermissionByLastIDReply {
  repeated UsersObjectpermission usersObjectpermissions = 1;
}


