syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service usersToken {
  // Create a new usersToken
  rpc Create(CreateUsersTokenRequest) returns (CreateUsersTokenReply) {
    option (google.api.http) = {
      post: "/api/users/tokens"
      body: "*"
    };
  }

  // Delete a usersToken by id
  rpc DeleteByID(DeleteUsersTokenByIDRequest) returns (DeleteUsersTokenByIDReply) {
    option (google.api.http) = {
      delete: "/api/users/tokens/{id}"
    };
  }

  // Update a usersToken by id
  rpc UpdateByID(UpdateUsersTokenByIDRequest) returns (UpdateUsersTokenByIDReply) {
    option (google.api.http) = {
      put: "/api/users/tokens/{id}"
      body: "*"
    };
  }

  // Get a usersToken by id
  rpc GetByID(GetUsersTokenByIDRequest) returns (GetUsersTokenByIDReply) {
    option (google.api.http) = {
      get: "/api/users/tokens/{id}"
    };
  }

  // Get a paginated list of usersToken by custom conditions
  rpc List(ListUsersTokenRequest) returns (ListUsersTokenReply) {
    option (google.api.http) = {
      post: "/api/users/tokens/list"
      body: "*"
    };
  }

  // Batch delete usersToken by ids
  rpc DeleteByIDs(DeleteUsersTokenByIDsRequest) returns (DeleteUsersTokenByIDsReply) {
    option (google.api.http) = {
      post: "/api/users/tokens/delete/ids"
      body: "*"
    };
  }

  // Get a usersToken by custom condition
  rpc GetByCondition(GetUsersTokenByConditionRequest) returns (GetUsersTokenByConditionReply) {
    option (google.api.http) = {
      post: "/api/users/tokens/condition"
      body: "*"
    };
  }

  // Batch get usersToken by ids
  rpc ListByIDs(ListUsersTokenByIDsRequest) returns (ListUsersTokenByIDsReply) {
    option (google.api.http) = {
      post: "/api/users/tokens/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of usersToken by last id
  rpc ListByLastID(ListUsersTokenByLastIDRequest) returns (ListUsersTokenByLastIDReply) {
    option (google.api.http) = {
      get: "/api/users/tokens"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/usersToken/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getUsersToken?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateUsersTokenRequest {
	string created = 1; 
	string expires = 2; 
	string key = 3; 
	bool writeEnabled = 4; 
	string description = 5; 
	int64 userID = 6; 
	string allowedIps = 7; 
	string lastUsed = 8; 
}

message CreateUsersTokenReply {
  uint64 id = 1;
}

message DeleteUsersTokenByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteUsersTokenByIDReply {

}

message UpdateUsersTokenByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string created = 2; 
	string expires = 3; 
	string key = 4; 
	bool writeEnabled = 5; 
	string description = 6; 
	int64 userID = 7; 
	string allowedIps = 8; 
	string lastUsed = 9; 
}

message UpdateUsersTokenByIDReply {

}

message UsersToken {
	uint64 id = 1; 
	string created = 2; 
	string expires = 3; 
	string key = 4; 
	bool writeEnabled = 5; 
	string description = 6; 
	int64 userID = 7; 
	string allowedIps = 8; 
	string lastUsed = 9; 
}

message GetUsersTokenByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetUsersTokenByIDReply {
  UsersToken usersToken = 1;
}

message ListUsersTokenRequest {
  api.types.Params params = 1;
}

message ListUsersTokenReply {
  int64 total = 1;
  repeated UsersToken usersTokens = 2;
}

message DeleteUsersTokenByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteUsersTokenByIDsReply {

}

message GetUsersTokenByConditionRequest {
  types.Conditions conditions = 1;
}

message GetUsersTokenByConditionReply {
  UsersToken usersToken = 1;
}

message ListUsersTokenByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListUsersTokenByIDsReply {
  repeated UsersToken usersTokens = 1;
}

message ListUsersTokenByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListUsersTokenByLastIDReply {
  repeated UsersToken usersTokens = 1;
}


