syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service virtualizationVminterface {
  // Create a new virtualizationVminterface
  rpc Create(CreateVirtualizationVminterfaceRequest) returns (CreateVirtualizationVminterfaceReply) {
    option (google.api.http) = {
      post: "/api/virtualization/vminterfaces"
      body: "*"
    };
  }

  // Delete a virtualizationVminterface by id
  rpc DeleteByID(DeleteVirtualizationVminterfaceByIDRequest) returns (DeleteVirtualizationVminterfaceByIDReply) {
    option (google.api.http) = {
      delete: "/api/virtualization/vminterfaces/{id}"
    };
  }

  // Update a virtualizationVminterface by id
  rpc UpdateByID(UpdateVirtualizationVminterfaceByIDRequest) returns (UpdateVirtualizationVminterfaceByIDReply) {
    option (google.api.http) = {
      put: "/api/virtualization/vminterfaces/{id}"
      body: "*"
    };
  }

  // Get a virtualizationVminterface by id
  rpc GetByID(GetVirtualizationVminterfaceByIDRequest) returns (GetVirtualizationVminterfaceByIDReply) {
    option (google.api.http) = {
      get: "/api/virtualization/vminterfaces/{id}"
    };
  }

  // Get a paginated list of virtualizationVminterface by custom conditions
  rpc List(ListVirtualizationVminterfaceRequest) returns (ListVirtualizationVminterfaceReply) {
    option (google.api.http) = {
      post: "/api/virtualization/vminterfaces/list"
      body: "*"
    };
  }

  // Batch delete virtualizationVminterface by ids
  rpc DeleteByIDs(DeleteVirtualizationVminterfaceByIDsRequest) returns (DeleteVirtualizationVminterfaceByIDsReply) {
    option (google.api.http) = {
      post: "/api/virtualization/vminterfaces/delete/ids"
      body: "*"
    };
  }

  // Get a virtualizationVminterface by custom condition
  rpc GetByCondition(GetVirtualizationVminterfaceByConditionRequest) returns (GetVirtualizationVminterfaceByConditionReply) {
    option (google.api.http) = {
      post: "/api/virtualization/vminterfaces/condition"
      body: "*"
    };
  }

  // Batch get virtualizationVminterface by ids
  rpc ListByIDs(ListVirtualizationVminterfaceByIDsRequest) returns (ListVirtualizationVminterfaceByIDsReply) {
    option (google.api.http) = {
      post: "/api/virtualization/vminterfaces/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of virtualizationVminterface by last id
  rpc ListByLastID(ListVirtualizationVminterfaceByLastIDRequest) returns (ListVirtualizationVminterfaceByLastIDReply) {
    option (google.api.http) = {
      get: "/api/virtualization/vminterfaces"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/virtualizationVminterface/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getVirtualizationVminterface?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateVirtualizationVminterfaceRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	bool enabled = 4; 
	int32 mtu = 5; 
	string mode = 6; 
	string name = 7; 
	string xName = 8 [json_name = "xName"]; 
	string description = 9; 
	int64 parentID = 10; 
	int64 untaggedVlanID = 11; 
	int64 virtualMachineID = 12; 
	int64 bridgeID = 13; 
	int64 vrfID = 14; 
	int64 vlanTranslationPolicyID = 15; 
	int64 qinqSvlanID = 16; 
	int64 primaryMacAddressID = 17; 
}

message CreateVirtualizationVminterfaceReply {
  uint64 id = 1;
}

message DeleteVirtualizationVminterfaceByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteVirtualizationVminterfaceByIDReply {

}

message UpdateVirtualizationVminterfaceByIDRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	bool enabled = 5; 
	int32 mtu = 6; 
	string mode = 7; 
	string name = 8; 
	string xName = 9 [json_name = "xName"]; 
	string description = 10; 
	int64 parentID = 11; 
	int64 untaggedVlanID = 12; 
	int64 virtualMachineID = 13; 
	int64 bridgeID = 14; 
	int64 vrfID = 15; 
	int64 vlanTranslationPolicyID = 16; 
	int64 qinqSvlanID = 17; 
	int64 primaryMacAddressID = 18; 
}

message UpdateVirtualizationVminterfaceByIDReply {

}

message VirtualizationVminterface {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4; 
	bool enabled = 5; 
	int32 mtu = 6; 
	string mode = 7; 
	string name = 8; 
	string xName = 9 [json_name = "xName"]; 
	string description = 10; 
	int64 parentID = 11; 
	int64 untaggedVlanID = 12; 
	int64 virtualMachineID = 13; 
	int64 bridgeID = 14; 
	int64 vrfID = 15; 
	int64 vlanTranslationPolicyID = 16; 
	int64 qinqSvlanID = 17; 
	int64 primaryMacAddressID = 18; 
}

message GetVirtualizationVminterfaceByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetVirtualizationVminterfaceByIDReply {
  VirtualizationVminterface virtualizationVminterface = 1;
}

message ListVirtualizationVminterfaceRequest {
  api.types.Params params = 1;
}

message ListVirtualizationVminterfaceReply {
  int64 total = 1;
  repeated VirtualizationVminterface virtualizationVminterfaces = 2;
}

message DeleteVirtualizationVminterfaceByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteVirtualizationVminterfaceByIDsReply {

}

message GetVirtualizationVminterfaceByConditionRequest {
  types.Conditions conditions = 1;
}

message GetVirtualizationVminterfaceByConditionReply {
  VirtualizationVminterface virtualizationVminterface = 1;
}

message ListVirtualizationVminterfaceByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListVirtualizationVminterfaceByIDsReply {
  repeated VirtualizationVminterface virtualizationVminterfaces = 1;
}

message ListVirtualizationVminterfaceByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListVirtualizationVminterfaceByLastIDReply {
  repeated VirtualizationVminterface virtualizationVminterfaces = 1;
}


