syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service virtualizationVirtualmachine {
  // Create a new virtualizationVirtualmachine
  rpc Create(CreateVirtualizationVirtualmachineRequest) returns (CreateVirtualizationVirtualmachineReply) {
    option (google.api.http) = {
      post: "/api/virtualization/virtualmachines"
      body: "*"
    };
  }

  // Delete a virtualizationVirtualmachine by id
  rpc DeleteByID(DeleteVirtualizationVirtualmachineByIDRequest) returns (DeleteVirtualizationVirtualmachineByIDReply) {
    option (google.api.http) = {
      delete: "/api/virtualization/virtualmachines/{id}"
    };
  }

  // Update a virtualizationVirtualmachine by id
  rpc UpdateByID(UpdateVirtualizationVirtualmachineByIDRequest) returns (UpdateVirtualizationVirtualmachineByIDReply) {
    option (google.api.http) = {
      put: "/api/virtualization/virtualmachines/{id}"
      body: "*"
    };
  }

  // Get a virtualizationVirtualmachine by id
  rpc GetByID(GetVirtualizationVirtualmachineByIDRequest) returns (GetVirtualizationVirtualmachineByIDReply) {
    option (google.api.http) = {
      get: "/api/virtualization/virtualmachines/{id}"
    };
  }

  // Get a paginated list of virtualizationVirtualmachine by custom conditions
  rpc List(ListVirtualizationVirtualmachineRequest) returns (ListVirtualizationVirtualmachineReply) {
    option (google.api.http) = {
      post: "/api/virtualization/virtualmachines/list"
      body: "*"
    };
  }

  // Batch delete virtualizationVirtualmachine by ids
  rpc DeleteByIDs(DeleteVirtualizationVirtualmachineByIDsRequest) returns (DeleteVirtualizationVirtualmachineByIDsReply) {
    option (google.api.http) = {
      post: "/api/virtualization/virtualmachines/delete/ids"
      body: "*"
    };
  }

  // Get a virtualizationVirtualmachine by custom condition
  rpc GetByCondition(GetVirtualizationVirtualmachineByConditionRequest) returns (GetVirtualizationVirtualmachineByConditionReply) {
    option (google.api.http) = {
      post: "/api/virtualization/virtualmachines/condition"
      body: "*"
    };
  }

  // Batch get virtualizationVirtualmachine by ids
  rpc ListByIDs(ListVirtualizationVirtualmachineByIDsRequest) returns (ListVirtualizationVirtualmachineByIDsReply) {
    option (google.api.http) = {
      post: "/api/virtualization/virtualmachines/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of virtualizationVirtualmachine by last id
  rpc ListByLastID(ListVirtualizationVirtualmachineByLastIDRequest) returns (ListVirtualizationVirtualmachineByLastIDReply) {
    option (google.api.http) = {
      get: "/api/virtualization/virtualmachines"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/virtualizationVirtualmachine/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getVirtualizationVirtualmachine?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateVirtualizationVirtualmachineRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	string localContextData = 4; 
	string name = 5; 
	string status = 6; 
	string vcpus = 7; 
	int32 memory = 8; 
	int32 disk = 9; 
	string comments = 10; 
	int64 clusterID = 11; 
	int64 platformID = 12; 
	int64 primaryIp4ID = 13; 
	int64 primaryIp6ID = 14; 
	int64 roleID = 15; 
	int64 tenantID = 16; 
	int64 siteID = 17; 
	int64 deviceID = 18; 
	string description = 19; 
	int64 interfaceCount = 20; 
	int64 configTemplateID = 21; 
	int64 virtualDiskCount = 22; 
	string serial = 23; 
}

message CreateVirtualizationVirtualmachineReply {
  uint64 id = 1;
}

message DeleteVirtualizationVirtualmachineByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteVirtualizationVirtualmachineByIDReply {

}

message UpdateVirtualizationVirtualmachineByIDRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string localContextData = 5; 
	string name = 6; 
	string status = 7; 
	string vcpus = 8; 
	int32 memory = 9; 
	int32 disk = 10; 
	string comments = 11; 
	int64 clusterID = 12; 
	int64 platformID = 13; 
	int64 primaryIp4ID = 14; 
	int64 primaryIp6ID = 15; 
	int64 roleID = 16; 
	int64 tenantID = 17; 
	int64 siteID = 18; 
	int64 deviceID = 19; 
	string description = 20; 
	int64 interfaceCount = 21; 
	int64 configTemplateID = 22; 
	int64 virtualDiskCount = 23; 
	string serial = 24; 
}

message UpdateVirtualizationVirtualmachineByIDReply {

}

message VirtualizationVirtualmachine {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	uint64 id = 4; 
	string localContextData = 5; 
	string name = 6; 
	string status = 7; 
	string vcpus = 8; 
	int32 memory = 9; 
	int32 disk = 10; 
	string comments = 11; 
	int64 clusterID = 12; 
	int64 platformID = 13; 
	int64 primaryIp4ID = 14; 
	int64 primaryIp6ID = 15; 
	int64 roleID = 16; 
	int64 tenantID = 17; 
	int64 siteID = 18; 
	int64 deviceID = 19; 
	string description = 20; 
	int64 interfaceCount = 21; 
	int64 configTemplateID = 22; 
	int64 virtualDiskCount = 23; 
	string serial = 24; 
}

message GetVirtualizationVirtualmachineByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetVirtualizationVirtualmachineByIDReply {
  VirtualizationVirtualmachine virtualizationVirtualmachine = 1;
}

message ListVirtualizationVirtualmachineRequest {
  api.types.Params params = 1;
}

message ListVirtualizationVirtualmachineReply {
  int64 total = 1;
  repeated VirtualizationVirtualmachine virtualizationVirtualmachines = 2;
}

message DeleteVirtualizationVirtualmachineByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteVirtualizationVirtualmachineByIDsReply {

}

message GetVirtualizationVirtualmachineByConditionRequest {
  types.Conditions conditions = 1;
}

message GetVirtualizationVirtualmachineByConditionReply {
  VirtualizationVirtualmachine virtualizationVirtualmachine = 1;
}

message ListVirtualizationVirtualmachineByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListVirtualizationVirtualmachineByIDsReply {
  repeated VirtualizationVirtualmachine virtualizationVirtualmachines = 1;
}

message ListVirtualizationVirtualmachineByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListVirtualizationVirtualmachineByLastIDReply {
  repeated VirtualizationVirtualmachine virtualizationVirtualmachines = 1;
}


