syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service vpnIkepolicy {
  // Create a new vpnIkepolicy
  rpc Create(CreateVpnIkepolicyRequest) returns (CreateVpnIkepolicyReply) {
    option (google.api.http) = {
      post: "/api/vpn/ikepolicys"
      body: "*"
    };
  }

  // Delete a vpnIkepolicy by id
  rpc DeleteByID(DeleteVpnIkepolicyByIDRequest) returns (DeleteVpnIkepolicyByIDReply) {
    option (google.api.http) = {
      delete: "/api/vpn/ikepolicys/{id}"
    };
  }

  // Update a vpnIkepolicy by id
  rpc UpdateByID(UpdateVpnIkepolicyByIDRequest) returns (UpdateVpnIkepolicyByIDReply) {
    option (google.api.http) = {
      put: "/api/vpn/ikepolicys/{id}"
      body: "*"
    };
  }

  // Get a vpnIkepolicy by id
  rpc GetByID(GetVpnIkepolicyByIDRequest) returns (GetVpnIkepolicyByIDReply) {
    option (google.api.http) = {
      get: "/api/vpn/ikepolicys/{id}"
    };
  }

  // Get a paginated list of vpnIkepolicy by custom conditions
  rpc List(ListVpnIkepolicyRequest) returns (ListVpnIkepolicyReply) {
    option (google.api.http) = {
      post: "/api/vpn/ikepolicys/list"
      body: "*"
    };
  }

  // Batch delete vpnIkepolicy by ids
  rpc DeleteByIDs(DeleteVpnIkepolicyByIDsRequest) returns (DeleteVpnIkepolicyByIDsReply) {
    option (google.api.http) = {
      post: "/api/vpn/ikepolicys/delete/ids"
      body: "*"
    };
  }

  // Get a vpnIkepolicy by custom condition
  rpc GetByCondition(GetVpnIkepolicyByConditionRequest) returns (GetVpnIkepolicyByConditionReply) {
    option (google.api.http) = {
      post: "/api/vpn/ikepolicys/condition"
      body: "*"
    };
  }

  // Batch get vpnIkepolicy by ids
  rpc ListByIDs(ListVpnIkepolicyByIDsRequest) returns (ListVpnIkepolicyByIDsReply) {
    option (google.api.http) = {
      post: "/api/vpn/ikepolicys/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of vpnIkepolicy by last id
  rpc ListByLastID(ListVpnIkepolicyByLastIDRequest) returns (ListVpnIkepolicyByLastIDReply) {
    option (google.api.http) = {
      get: "/api/vpn/ikepolicys"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/vpnIkepolicy/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getVpnIkepolicy?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateVpnIkepolicyRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	string description = 4; 
	string comments = 5; 
	string name = 6; 
	int32 version = 7; 
	string mode = 8; 
	string presharedKey = 9; 
}

message CreateVpnIkepolicyReply {
  uint64 id = 1;
}

message DeleteVpnIkepolicyByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteVpnIkepolicyByIDReply {

}

message UpdateVpnIkepolicyByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string created = 2; 
	string lastUpdated = 3; 
	string customFieldData = 4; 
	string description = 5; 
	string comments = 6; 
	string name = 7; 
	int32 version = 8; 
	string mode = 9; 
	string presharedKey = 10; 
}

message UpdateVpnIkepolicyByIDReply {

}

message VpnIkepolicy {
	uint64 id = 1; 
	string created = 2; 
	string lastUpdated = 3; 
	string customFieldData = 4; 
	string description = 5; 
	string comments = 6; 
	string name = 7; 
	int32 version = 8; 
	string mode = 9; 
	string presharedKey = 10; 
}

message GetVpnIkepolicyByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetVpnIkepolicyByIDReply {
  VpnIkepolicy vpnIkepolicy = 1;
}

message ListVpnIkepolicyRequest {
  api.types.Params params = 1;
}

message ListVpnIkepolicyReply {
  int64 total = 1;
  repeated VpnIkepolicy vpnIkepolicys = 2;
}

message DeleteVpnIkepolicyByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteVpnIkepolicyByIDsReply {

}

message GetVpnIkepolicyByConditionRequest {
  types.Conditions conditions = 1;
}

message GetVpnIkepolicyByConditionReply {
  VpnIkepolicy vpnIkepolicy = 1;
}

message ListVpnIkepolicyByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListVpnIkepolicyByIDsReply {
  repeated VpnIkepolicy vpnIkepolicys = 1;
}

message ListVpnIkepolicyByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListVpnIkepolicyByLastIDReply {
  repeated VpnIkepolicy vpnIkepolicys = 1;
}


