syntax = "proto3";

package api.netbox_go.v1;

import "api/types/types.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "tagger/tagger.proto";
import "validate/validate.proto";

option go_package = "netbox-go/api/netbox_go/v1;v1";

/*
Default settings for generating *.swagger.json documents. For reference, see: https://bit.ly/4dE5jj7
Tip: To enhance the generated Swagger documentation, you can add the openapiv2_operation option to your RPC method. For example:
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "get user by id",
      description: "get user by id",
      security: {
        security_requirement: {
          key: "BearerAuth";
          value: {}
        }
      }
    };
*/
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  host: "localhost:8080"
  base_path: ""
  info: {
    title: "netbox_go api docs";
    version: "v1.0.0";
  }
  schemes: HTTP;
  schemes: HTTPS;
  consumes: "application/json";
  produces: "application/json";
  security_definitions: {
    security: {
      key: "BearerAuth";
      value: {
        type: TYPE_API_KEY;
        in: IN_HEADER;
        name: "Authorization";
        description: "Type Bearer your-jwt-token to Value";
      }
    }
  }
};

service vpnTunnel {
  // Create a new vpnTunnel
  rpc Create(CreateVpnTunnelRequest) returns (CreateVpnTunnelReply) {
    option (google.api.http) = {
      post: "/api/vpn/tunnels"
      body: "*"
    };
  }

  // Delete a vpnTunnel by id
  rpc DeleteByID(DeleteVpnTunnelByIDRequest) returns (DeleteVpnTunnelByIDReply) {
    option (google.api.http) = {
      delete: "/api/vpn/tunnels/{id}"
    };
  }

  // Update a vpnTunnel by id
  rpc UpdateByID(UpdateVpnTunnelByIDRequest) returns (UpdateVpnTunnelByIDReply) {
    option (google.api.http) = {
      put: "/api/vpn/tunnels/{id}"
      body: "*"
    };
  }

  // Get a vpnTunnel by id
  rpc GetByID(GetVpnTunnelByIDRequest) returns (GetVpnTunnelByIDReply) {
    option (google.api.http) = {
      get: "/api/vpn/tunnels/{id}"
    };
  }

  // Get a paginated list of vpnTunnel by custom conditions
  rpc List(ListVpnTunnelRequest) returns (ListVpnTunnelReply) {
    option (google.api.http) = {
      post: "/api/vpn/tunnels/list"
      body: "*"
    };
  }

  // Batch delete vpnTunnel by ids
  rpc DeleteByIDs(DeleteVpnTunnelByIDsRequest) returns (DeleteVpnTunnelByIDsReply) {
    option (google.api.http) = {
      post: "/api/vpn/tunnels/delete/ids"
      body: "*"
    };
  }

  // Get a vpnTunnel by custom condition
  rpc GetByCondition(GetVpnTunnelByConditionRequest) returns (GetVpnTunnelByConditionReply) {
    option (google.api.http) = {
      post: "/api/vpn/tunnels/condition"
      body: "*"
    };
  }

  // Batch get vpnTunnel by ids
  rpc ListByIDs(ListVpnTunnelByIDsRequest) returns (ListVpnTunnelByIDsReply) {
    option (google.api.http) = {
      post: "/api/vpn/tunnels/list/ids"
      body: "*"
    };
  }

  // Get a paginated list of vpnTunnel by last id
  rpc ListByLastID(ListVpnTunnelByLastIDRequest) returns (ListVpnTunnelByLastIDReply) {
    option (google.api.http) = {
      get: "/api/vpn/tunnels"
    };
  }
}


/*
Notes for defining message fields:
    1. Suggest using camel case style naming for message field names, such as firstName, lastName, etc.
    2. If the message field name ending in 'id', it is recommended to use xxxID naming format, such as userID, orderID, etc.
    3. Add validate rules https://github.com/envoyproxy/protoc-gen-validate#constraint-rules, such as:
        uint64 id = 1 [(validate.rules).uint64.gte  = 1];

If used to generate code that supports the HTTP protocol, notes for defining message fields:
    1. If the route contains the path parameter, such as /api/v1/vpnTunnel/{id}, the defined
        message must contain the name of the path parameter and the name should be added
        with a new tag, such as int64 id = 1 [(tagger.tags) = "uri:\"id\""];
    2. If the request url is followed by a query parameter, such as /api/v1/getVpnTunnel?name=Tom,
        a form tag must be added when defining the query parameter in the message, such as:
        string name = 1 [(tagger.tags) = "form:\"name\""].
    3. When the message fields use snake_case naming (e.g., order_id), the generated swagger.json file
        will use camelCase (e.g., orderId) instead of the expected snake_case. This behavior aligns with
        the JSON tag names used by gRPC, but it can cause the Gin framework to fail to correctly bind and
        retrieve parameter values. There are two ways to resolve this issue:
            (1) Explicitly specify the JSON tag name using the json_name option, such as:
                 string order_id = 1 [json_name = "order_id"];
            (2) If you want to switch to camelCase naming and update the JSON tag name accordingly, such as:
                 string order_id = 1 [json_name = "orderID", (tagger.tags) = "json:\"orderID\""];
*/


message CreateVpnTunnelRequest {
	string created = 1; 
	string lastUpdated = 2; 
	string customFieldData = 3; 
	string description = 4; 
	string comments = 5; 
	string name = 6; 
	string status = 7; 
	int64 groupID = 8; 
	string encapsulation = 9; 
	int64 tunnelID = 10; 
	int64 ipsecProfileID = 11; 
	int64 tenantID = 12; 
}

message CreateVpnTunnelReply {
  uint64 id = 1;
}

message DeleteVpnTunnelByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""];
}

message DeleteVpnTunnelByIDReply {

}

message UpdateVpnTunnelByIDRequest {
	uint64 id = 1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\""]; 
	string created = 2; 
	string lastUpdated = 3; 
	string customFieldData = 4; 
	string description = 5; 
	string comments = 6; 
	string name = 7; 
	string status = 8; 
	int64 groupID = 9; 
	string encapsulation = 10; 
	int64 tunnelID = 11; 
	int64 ipsecProfileID = 12; 
	int64 tenantID = 13; 
}

message UpdateVpnTunnelByIDReply {

}

message VpnTunnel {
	uint64 id = 1; 
	string created = 2; 
	string lastUpdated = 3; 
	string customFieldData = 4; 
	string description = 5; 
	string comments = 6; 
	string name = 7; 
	string status = 8; 
	int64 groupID = 9; 
	string encapsulation = 10; 
	int64 tunnelID = 11; 
	int64 ipsecProfileID = 12; 
	int64 tenantID = 13; 
}

message GetVpnTunnelByIDRequest {
  uint64 id =1 [(validate.rules).uint64.gt = 0, (tagger.tags) = "uri:\"id\"" ];
}

message GetVpnTunnelByIDReply {
  VpnTunnel vpnTunnel = 1;
}

message ListVpnTunnelRequest {
  api.types.Params params = 1;
}

message ListVpnTunnelReply {
  int64 total = 1;
  repeated VpnTunnel vpnTunnels = 2;
}

message DeleteVpnTunnelByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message DeleteVpnTunnelByIDsReply {

}

message GetVpnTunnelByConditionRequest {
  types.Conditions conditions = 1;
}

message GetVpnTunnelByConditionReply {
  VpnTunnel vpnTunnel = 1;
}

message ListVpnTunnelByIDsRequest {
  repeated uint64 ids = 1 [(validate.rules).repeated.min_items = 1];
}

message ListVpnTunnelByIDsReply {
  repeated VpnTunnel vpnTunnels = 1;
}

message ListVpnTunnelByLastIDRequest {
  uint64 lastID = 1 [(tagger.tags) = "form:\"lastID\""]; // last id
  uint32 limit = 2 [(validate.rules).uint32.gt = 0, (tagger.tags) = "form:\"limit\""]; // limit size per page
  string sort = 3 [(tagger.tags) = "form:\"sort\""]; // sort by column name of table, default is -id, the - sign indicates descending order.
}

message ListVpnTunnelByLastIDReply {
  repeated VpnTunnel vpnTunnels = 1;
}


