// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/netbox_go/v1/wirelessWirelesslangroup.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "netbox-go/api/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWirelessWirelesslangroupRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Created         string                 `protobuf:"bytes,1,opt,name=created,proto3" json:"created"`
	LastUpdated     string                 `protobuf:"bytes,2,opt,name=lastUpdated,proto3" json:"lastUpdated"`
	CustomFieldData string                 `protobuf:"bytes,3,opt,name=customFieldData,proto3" json:"customFieldData"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	Slug            string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	Lft             int32                  `protobuf:"varint,7,opt,name=lft,proto3" json:"lft"`
	Rght            int32                  `protobuf:"varint,8,opt,name=rght,proto3" json:"rght"`
	TreeID          int32                  `protobuf:"varint,9,opt,name=treeID,proto3" json:"treeID"`
	Level           int32                  `protobuf:"varint,10,opt,name=level,proto3" json:"level"`
	ParentID        int64                  `protobuf:"varint,11,opt,name=parentID,proto3" json:"parentID"`
	Comments        string                 `protobuf:"bytes,12,opt,name=comments,proto3" json:"comments"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateWirelessWirelesslangroupRequest) Reset() {
	*x = CreateWirelessWirelesslangroupRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWirelessWirelesslangroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWirelessWirelesslangroupRequest) ProtoMessage() {}

func (x *CreateWirelessWirelesslangroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWirelessWirelesslangroupRequest.ProtoReflect.Descriptor instead.
func (*CreateWirelessWirelesslangroupRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWirelessWirelesslangroupRequest) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *CreateWirelessWirelesslangroupRequest) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *CreateWirelessWirelesslangroupRequest) GetCustomFieldData() string {
	if x != nil {
		return x.CustomFieldData
	}
	return ""
}

func (x *CreateWirelessWirelesslangroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWirelessWirelesslangroupRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateWirelessWirelesslangroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWirelessWirelesslangroupRequest) GetLft() int32 {
	if x != nil {
		return x.Lft
	}
	return 0
}

func (x *CreateWirelessWirelesslangroupRequest) GetRght() int32 {
	if x != nil {
		return x.Rght
	}
	return 0
}

func (x *CreateWirelessWirelesslangroupRequest) GetTreeID() int32 {
	if x != nil {
		return x.TreeID
	}
	return 0
}

func (x *CreateWirelessWirelesslangroupRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateWirelessWirelesslangroupRequest) GetParentID() int64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

func (x *CreateWirelessWirelesslangroupRequest) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

type CreateWirelessWirelesslangroupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWirelessWirelesslangroupReply) Reset() {
	*x = CreateWirelessWirelesslangroupReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWirelessWirelesslangroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWirelessWirelesslangroupReply) ProtoMessage() {}

func (x *CreateWirelessWirelesslangroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWirelessWirelesslangroupReply.ProtoReflect.Descriptor instead.
func (*CreateWirelessWirelesslangroupReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWirelessWirelesslangroupReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWirelessWirelesslangroupByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWirelessWirelesslangroupByIDRequest) Reset() {
	*x = DeleteWirelessWirelesslangroupByIDRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWirelessWirelesslangroupByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWirelessWirelesslangroupByIDRequest) ProtoMessage() {}

func (x *DeleteWirelessWirelesslangroupByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWirelessWirelesslangroupByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteWirelessWirelesslangroupByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteWirelessWirelesslangroupByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWirelessWirelesslangroupByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWirelessWirelesslangroupByIDReply) Reset() {
	*x = DeleteWirelessWirelesslangroupByIDReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWirelessWirelesslangroupByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWirelessWirelesslangroupByIDReply) ProtoMessage() {}

func (x *DeleteWirelessWirelesslangroupByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWirelessWirelesslangroupByIDReply.ProtoReflect.Descriptor instead.
func (*DeleteWirelessWirelesslangroupByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{3}
}

type UpdateWirelessWirelesslangroupByIDRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	Created         string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created"`
	LastUpdated     string                 `protobuf:"bytes,3,opt,name=lastUpdated,proto3" json:"lastUpdated"`
	CustomFieldData string                 `protobuf:"bytes,4,opt,name=customFieldData,proto3" json:"customFieldData"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Slug            string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description"`
	Lft             int32                  `protobuf:"varint,8,opt,name=lft,proto3" json:"lft"`
	Rght            int32                  `protobuf:"varint,9,opt,name=rght,proto3" json:"rght"`
	TreeID          int32                  `protobuf:"varint,10,opt,name=treeID,proto3" json:"treeID"`
	Level           int32                  `protobuf:"varint,11,opt,name=level,proto3" json:"level"`
	ParentID        int64                  `protobuf:"varint,12,opt,name=parentID,proto3" json:"parentID"`
	Comments        string                 `protobuf:"bytes,13,opt,name=comments,proto3" json:"comments"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) Reset() {
	*x = UpdateWirelessWirelesslangroupByIDRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWirelessWirelesslangroupByIDRequest) ProtoMessage() {}

func (x *UpdateWirelessWirelesslangroupByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWirelessWirelesslangroupByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateWirelessWirelesslangroupByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetCustomFieldData() string {
	if x != nil {
		return x.CustomFieldData
	}
	return ""
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetLft() int32 {
	if x != nil {
		return x.Lft
	}
	return 0
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetRght() int32 {
	if x != nil {
		return x.Rght
	}
	return 0
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetTreeID() int32 {
	if x != nil {
		return x.TreeID
	}
	return 0
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetParentID() int64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

func (x *UpdateWirelessWirelesslangroupByIDRequest) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

type UpdateWirelessWirelesslangroupByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWirelessWirelesslangroupByIDReply) Reset() {
	*x = UpdateWirelessWirelesslangroupByIDReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWirelessWirelesslangroupByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWirelessWirelesslangroupByIDReply) ProtoMessage() {}

func (x *UpdateWirelessWirelesslangroupByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWirelessWirelesslangroupByIDReply.ProtoReflect.Descriptor instead.
func (*UpdateWirelessWirelesslangroupByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{5}
}

type WirelessWirelesslangroup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Created         string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created"`
	LastUpdated     string                 `protobuf:"bytes,3,opt,name=lastUpdated,proto3" json:"lastUpdated"`
	CustomFieldData string                 `protobuf:"bytes,4,opt,name=customFieldData,proto3" json:"customFieldData"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Slug            string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description"`
	Lft             int32                  `protobuf:"varint,8,opt,name=lft,proto3" json:"lft"`
	Rght            int32                  `protobuf:"varint,9,opt,name=rght,proto3" json:"rght"`
	TreeID          int32                  `protobuf:"varint,10,opt,name=treeID,proto3" json:"treeID"`
	Level           int32                  `protobuf:"varint,11,opt,name=level,proto3" json:"level"`
	ParentID        int64                  `protobuf:"varint,12,opt,name=parentID,proto3" json:"parentID"`
	Comments        string                 `protobuf:"bytes,13,opt,name=comments,proto3" json:"comments"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WirelessWirelesslangroup) Reset() {
	*x = WirelessWirelesslangroup{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WirelessWirelesslangroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WirelessWirelesslangroup) ProtoMessage() {}

func (x *WirelessWirelesslangroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WirelessWirelesslangroup.ProtoReflect.Descriptor instead.
func (*WirelessWirelesslangroup) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{6}
}

func (x *WirelessWirelesslangroup) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WirelessWirelesslangroup) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *WirelessWirelesslangroup) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *WirelessWirelesslangroup) GetCustomFieldData() string {
	if x != nil {
		return x.CustomFieldData
	}
	return ""
}

func (x *WirelessWirelesslangroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WirelessWirelesslangroup) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *WirelessWirelesslangroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WirelessWirelesslangroup) GetLft() int32 {
	if x != nil {
		return x.Lft
	}
	return 0
}

func (x *WirelessWirelesslangroup) GetRght() int32 {
	if x != nil {
		return x.Rght
	}
	return 0
}

func (x *WirelessWirelesslangroup) GetTreeID() int32 {
	if x != nil {
		return x.TreeID
	}
	return 0
}

func (x *WirelessWirelesslangroup) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *WirelessWirelesslangroup) GetParentID() int64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

func (x *WirelessWirelesslangroup) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

type GetWirelessWirelesslangroupByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWirelessWirelesslangroupByIDRequest) Reset() {
	*x = GetWirelessWirelesslangroupByIDRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWirelessWirelesslangroupByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWirelessWirelesslangroupByIDRequest) ProtoMessage() {}

func (x *GetWirelessWirelesslangroupByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWirelessWirelesslangroupByIDRequest.ProtoReflect.Descriptor instead.
func (*GetWirelessWirelesslangroupByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{7}
}

func (x *GetWirelessWirelesslangroupByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWirelessWirelesslangroupByIDReply struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	WirelessWirelesslangroup *WirelessWirelesslangroup `protobuf:"bytes,1,opt,name=wirelessWirelesslangroup,proto3" json:"wirelessWirelesslangroup"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetWirelessWirelesslangroupByIDReply) Reset() {
	*x = GetWirelessWirelesslangroupByIDReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWirelessWirelesslangroupByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWirelessWirelesslangroupByIDReply) ProtoMessage() {}

func (x *GetWirelessWirelesslangroupByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWirelessWirelesslangroupByIDReply.ProtoReflect.Descriptor instead.
func (*GetWirelessWirelesslangroupByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{8}
}

func (x *GetWirelessWirelesslangroupByIDReply) GetWirelessWirelesslangroup() *WirelessWirelesslangroup {
	if x != nil {
		return x.WirelessWirelesslangroup
	}
	return nil
}

type ListWirelessWirelesslangroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *types.Params          `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWirelessWirelesslangroupRequest) Reset() {
	*x = ListWirelessWirelesslangroupRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslangroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslangroupRequest) ProtoMessage() {}

func (x *ListWirelessWirelesslangroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslangroupRequest.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslangroupRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{9}
}

func (x *ListWirelessWirelesslangroupRequest) GetParams() *types.Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type ListWirelessWirelesslangroupReply struct {
	state                     protoimpl.MessageState      `protogen:"open.v1"`
	Total                     int64                       `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	WirelessWirelesslangroups []*WirelessWirelesslangroup `protobuf:"bytes,2,rep,name=wirelessWirelesslangroups,proto3" json:"wirelessWirelesslangroups"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListWirelessWirelesslangroupReply) Reset() {
	*x = ListWirelessWirelesslangroupReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslangroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslangroupReply) ProtoMessage() {}

func (x *ListWirelessWirelesslangroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslangroupReply.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslangroupReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{10}
}

func (x *ListWirelessWirelesslangroupReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWirelessWirelesslangroupReply) GetWirelessWirelesslangroups() []*WirelessWirelesslangroup {
	if x != nil {
		return x.WirelessWirelesslangroups
	}
	return nil
}

type DeleteWirelessWirelesslangroupByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWirelessWirelesslangroupByIDsRequest) Reset() {
	*x = DeleteWirelessWirelesslangroupByIDsRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWirelessWirelesslangroupByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWirelessWirelesslangroupByIDsRequest) ProtoMessage() {}

func (x *DeleteWirelessWirelesslangroupByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWirelessWirelesslangroupByIDsRequest.ProtoReflect.Descriptor instead.
func (*DeleteWirelessWirelesslangroupByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteWirelessWirelesslangroupByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteWirelessWirelesslangroupByIDsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWirelessWirelesslangroupByIDsReply) Reset() {
	*x = DeleteWirelessWirelesslangroupByIDsReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWirelessWirelesslangroupByIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWirelessWirelesslangroupByIDsReply) ProtoMessage() {}

func (x *DeleteWirelessWirelesslangroupByIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWirelessWirelesslangroupByIDsReply.ProtoReflect.Descriptor instead.
func (*DeleteWirelessWirelesslangroupByIDsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{12}
}

type GetWirelessWirelesslangroupByConditionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    *types.Conditions      `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWirelessWirelesslangroupByConditionRequest) Reset() {
	*x = GetWirelessWirelesslangroupByConditionRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWirelessWirelesslangroupByConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWirelessWirelesslangroupByConditionRequest) ProtoMessage() {}

func (x *GetWirelessWirelesslangroupByConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWirelessWirelesslangroupByConditionRequest.ProtoReflect.Descriptor instead.
func (*GetWirelessWirelesslangroupByConditionRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{13}
}

func (x *GetWirelessWirelesslangroupByConditionRequest) GetConditions() *types.Conditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type GetWirelessWirelesslangroupByConditionReply struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	WirelessWirelesslangroup *WirelessWirelesslangroup `protobuf:"bytes,1,opt,name=wirelessWirelesslangroup,proto3" json:"wirelessWirelesslangroup"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetWirelessWirelesslangroupByConditionReply) Reset() {
	*x = GetWirelessWirelesslangroupByConditionReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWirelessWirelesslangroupByConditionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWirelessWirelesslangroupByConditionReply) ProtoMessage() {}

func (x *GetWirelessWirelesslangroupByConditionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWirelessWirelesslangroupByConditionReply.ProtoReflect.Descriptor instead.
func (*GetWirelessWirelesslangroupByConditionReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{14}
}

func (x *GetWirelessWirelesslangroupByConditionReply) GetWirelessWirelesslangroup() *WirelessWirelesslangroup {
	if x != nil {
		return x.WirelessWirelesslangroup
	}
	return nil
}

type ListWirelessWirelesslangroupByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWirelessWirelesslangroupByIDsRequest) Reset() {
	*x = ListWirelessWirelesslangroupByIDsRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslangroupByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslangroupByIDsRequest) ProtoMessage() {}

func (x *ListWirelessWirelesslangroupByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslangroupByIDsRequest.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslangroupByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{15}
}

func (x *ListWirelessWirelesslangroupByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListWirelessWirelesslangroupByIDsReply struct {
	state                     protoimpl.MessageState      `protogen:"open.v1"`
	WirelessWirelesslangroups []*WirelessWirelesslangroup `protobuf:"bytes,1,rep,name=wirelessWirelesslangroups,proto3" json:"wirelessWirelesslangroups"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListWirelessWirelesslangroupByIDsReply) Reset() {
	*x = ListWirelessWirelesslangroupByIDsReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslangroupByIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslangroupByIDsReply) ProtoMessage() {}

func (x *ListWirelessWirelesslangroupByIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslangroupByIDsReply.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslangroupByIDsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{16}
}

func (x *ListWirelessWirelesslangroupByIDsReply) GetWirelessWirelesslangroups() []*WirelessWirelesslangroup {
	if x != nil {
		return x.WirelessWirelesslangroups
	}
	return nil
}

type ListWirelessWirelesslangroupByLastIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastID        uint64                 `protobuf:"varint,1,opt,name=lastID,proto3" json:"lastID" form:"lastID"` // last id
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit" form:"limit"`    // limit size per page
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort" form:"sort"`        // sort by column name of table, default is -id, the - sign indicates descending order.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWirelessWirelesslangroupByLastIDRequest) Reset() {
	*x = ListWirelessWirelesslangroupByLastIDRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslangroupByLastIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslangroupByLastIDRequest) ProtoMessage() {}

func (x *ListWirelessWirelesslangroupByLastIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslangroupByLastIDRequest.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslangroupByLastIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{17}
}

func (x *ListWirelessWirelesslangroupByLastIDRequest) GetLastID() uint64 {
	if x != nil {
		return x.LastID
	}
	return 0
}

func (x *ListWirelessWirelesslangroupByLastIDRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWirelessWirelesslangroupByLastIDRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListWirelessWirelesslangroupByLastIDReply struct {
	state                     protoimpl.MessageState      `protogen:"open.v1"`
	WirelessWirelesslangroups []*WirelessWirelesslangroup `protobuf:"bytes,1,rep,name=wirelessWirelesslangroups,proto3" json:"wirelessWirelesslangroups"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListWirelessWirelesslangroupByLastIDReply) Reset() {
	*x = ListWirelessWirelesslangroupByLastIDReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslangroupByLastIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslangroupByLastIDReply) ProtoMessage() {}

func (x *ListWirelessWirelesslangroupByLastIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslangroupByLastIDReply.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslangroupByLastIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP(), []int{18}
}

func (x *ListWirelessWirelesslangroupByLastIDReply) GetWirelessWirelesslangroups() []*WirelessWirelesslangroup {
	if x != nil {
		return x.WirelessWirelesslangroups
	}
	return nil
}

var File_api_netbox_go_v1_wirelessWirelesslangroup_proto protoreflect.FileDescriptor

const file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDesc = "" +
	"\n" +
	"/api/netbox_go/v1/wirelessWirelesslangroup.proto\x12\x10api.netbox_go.v1\x1a\x15api/types/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x13tagger/tagger.proto\x1a\x17validate/validate.proto\"\xe3\x02\n" +
	"%CreateWirelessWirelesslangroupRequest\x12\x18\n" +
	"\acreated\x18\x01 \x01(\tR\acreated\x12 \n" +
	"\vlastUpdated\x18\x02 \x01(\tR\vlastUpdated\x12(\n" +
	"\x0fcustomFieldData\x18\x03 \x01(\tR\x0fcustomFieldData\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x10\n" +
	"\x03lft\x18\a \x01(\x05R\x03lft\x12\x12\n" +
	"\x04rght\x18\b \x01(\x05R\x04rght\x12\x16\n" +
	"\x06treeID\x18\t \x01(\x05R\x06treeID\x12\x14\n" +
	"\x05level\x18\n" +
	" \x01(\x05R\x05level\x12\x1a\n" +
	"\bparentID\x18\v \x01(\x03R\bparentID\x12\x1a\n" +
	"\bcomments\x18\f \x01(\tR\bcomments\"5\n" +
	"#CreateWirelessWirelesslangroupReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"Q\n" +
	")DeleteWirelessWirelesslangroupByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\")\n" +
	"'DeleteWirelessWirelesslangroupByIDReply\"\x8d\x03\n" +
	")UpdateWirelessWirelesslangroupByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12 \n" +
	"\vlastUpdated\x18\x03 \x01(\tR\vlastUpdated\x12(\n" +
	"\x0fcustomFieldData\x18\x04 \x01(\tR\x0fcustomFieldData\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x10\n" +
	"\x03lft\x18\b \x01(\x05R\x03lft\x12\x12\n" +
	"\x04rght\x18\t \x01(\x05R\x04rght\x12\x16\n" +
	"\x06treeID\x18\n" +
	" \x01(\x05R\x06treeID\x12\x14\n" +
	"\x05level\x18\v \x01(\x05R\x05level\x12\x1a\n" +
	"\bparentID\x18\f \x01(\x03R\bparentID\x12\x1a\n" +
	"\bcomments\x18\r \x01(\tR\bcomments\")\n" +
	"'UpdateWirelessWirelesslangroupByIDReply\"\xe6\x02\n" +
	"\x18WirelessWirelesslangroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12 \n" +
	"\vlastUpdated\x18\x03 \x01(\tR\vlastUpdated\x12(\n" +
	"\x0fcustomFieldData\x18\x04 \x01(\tR\x0fcustomFieldData\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x10\n" +
	"\x03lft\x18\b \x01(\x05R\x03lft\x12\x12\n" +
	"\x04rght\x18\t \x01(\x05R\x04rght\x12\x16\n" +
	"\x06treeID\x18\n" +
	" \x01(\x05R\x06treeID\x12\x14\n" +
	"\x05level\x18\v \x01(\x05R\x05level\x12\x1a\n" +
	"\bparentID\x18\f \x01(\x03R\bparentID\x12\x1a\n" +
	"\bcomments\x18\r \x01(\tR\bcomments\"N\n" +
	"&GetWirelessWirelesslangroupByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"\x8e\x01\n" +
	"$GetWirelessWirelesslangroupByIDReply\x12f\n" +
	"\x18wirelessWirelesslangroup\x18\x01 \x01(\v2*.api.netbox_go.v1.WirelessWirelesslangroupR\x18wirelessWirelesslangroup\"P\n" +
	"#ListWirelessWirelesslangroupRequest\x12)\n" +
	"\x06params\x18\x01 \x01(\v2\x11.api.types.ParamsR\x06params\"\xa3\x01\n" +
	"!ListWirelessWirelesslangroupReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12h\n" +
	"\x19wirelessWirelesslangroups\x18\x02 \x03(\v2*.api.netbox_go.v1.WirelessWirelesslangroupR\x19wirelessWirelesslangroups\"H\n" +
	"*DeleteWirelessWirelesslangroupByIDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"*\n" +
	"(DeleteWirelessWirelesslangroupByIDsReply\"f\n" +
	"-GetWirelessWirelesslangroupByConditionRequest\x125\n" +
	"\n" +
	"conditions\x18\x01 \x01(\v2\x15.api.types.ConditionsR\n" +
	"conditions\"\x95\x01\n" +
	"+GetWirelessWirelesslangroupByConditionReply\x12f\n" +
	"\x18wirelessWirelesslangroup\x18\x01 \x01(\v2*.api.netbox_go.v1.WirelessWirelesslangroupR\x18wirelessWirelesslangroup\"F\n" +
	"(ListWirelessWirelesslangroupByIDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"\x92\x01\n" +
	"&ListWirelessWirelesslangroupByIDsReply\x12h\n" +
	"\x19wirelessWirelesslangroups\x18\x01 \x03(\v2*.api.netbox_go.v1.WirelessWirelesslangroupR\x19wirelessWirelesslangroups\"\xaf\x01\n" +
	"+ListWirelessWirelesslangroupByLastIDRequest\x12*\n" +
	"\x06lastID\x18\x01 \x01(\x04B\x12\x9a\x84\x9e\x03\rform:\"lastID\"R\x06lastID\x12.\n" +
	"\x05limit\x18\x02 \x01(\rB\x18\xfaB\x04*\x02 \x00\x9a\x84\x9e\x03\fform:\"limit\"R\x05limit\x12$\n" +
	"\x04sort\x18\x03 \x01(\tB\x10\x9a\x84\x9e\x03\vform:\"sort\"R\x04sort\"\x95\x01\n" +
	")ListWirelessWirelesslangroupByLastIDReply\x12h\n" +
	"\x19wirelessWirelesslangroups\x18\x01 \x03(\v2*.api.netbox_go.v1.WirelessWirelesslangroupR\x19wirelessWirelesslangroups2\xf9\f\n" +
	"\x18wirelessWirelesslangroup\x12\xa4\x01\n" +
	"\x06Create\x127.api.netbox_go.v1.CreateWirelessWirelesslangroupRequest\x1a5.api.netbox_go.v1.CreateWirelessWirelesslangroupReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/wireless/wirelesslangroups\x12\xb2\x01\n" +
	"\n" +
	"DeleteByID\x12;.api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDRequest\x1a9.api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDReply\",\x82\xd3\xe4\x93\x02&*$/api/wireless/wirelesslangroups/{id}\x12\xb5\x01\n" +
	"\n" +
	"UpdateByID\x12;.api.netbox_go.v1.UpdateWirelessWirelesslangroupByIDRequest\x1a9.api.netbox_go.v1.UpdateWirelessWirelesslangroupByIDReply\"/\x82\xd3\xe4\x93\x02):\x01*\x1a$/api/wireless/wirelesslangroups/{id}\x12\xa9\x01\n" +
	"\aGetByID\x128.api.netbox_go.v1.GetWirelessWirelesslangroupByIDRequest\x1a6.api.netbox_go.v1.GetWirelessWirelesslangroupByIDReply\",\x82\xd3\xe4\x93\x02&\x12$/api/wireless/wirelesslangroups/{id}\x12\xa3\x01\n" +
	"\x04List\x125.api.netbox_go.v1.ListWirelessWirelesslangroupRequest\x1a3.api.netbox_go.v1.ListWirelessWirelesslangroupReply\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/wireless/wirelesslangroups/list\x12\xbe\x01\n" +
	"\vDeleteByIDs\x12<.api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDsRequest\x1a:.api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDsReply\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/api/wireless/wirelesslangroups/delete/ids\x12\xc6\x01\n" +
	"\x0eGetByCondition\x12?.api.netbox_go.v1.GetWirelessWirelesslangroupByConditionRequest\x1a=.api.netbox_go.v1.GetWirelessWirelesslangroupByConditionReply\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/wireless/wirelesslangroups/condition\x12\xb6\x01\n" +
	"\tListByIDs\x12:.api.netbox_go.v1.ListWirelessWirelesslangroupByIDsRequest\x1a8.api.netbox_go.v1.ListWirelessWirelesslangroupByIDsReply\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/api/wireless/wirelesslangroups/list/ids\x12\xb3\x01\n" +
	"\fListByLastID\x12=.api.netbox_go.v1.ListWirelessWirelesslangroupByLastIDRequest\x1a;.api.netbox_go.v1.ListWirelessWirelesslangroupByLastIDReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/wireless/wirelesslangroupsB\xc3\x01\x92A\xa0\x01\x12\x1c\n" +
	"\x12netbox_go api docs2\x06v1.0.0\x1a\x0elocalhost:8080*\x02\x01\x022\x10application/json:\x10application/jsonZH\n" +
	"F\n" +
	"\n" +
	"BearerAuth\x128\b\x02\x12#Type Bearer your-jwt-token to Value\x1a\rAuthorization \x02Z\x1dnetbox-go/api/netbox_go/v1;v1b\x06proto3"

var (
	file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescOnce sync.Once
	file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescData []byte
)

func file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescGZIP() []byte {
	file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescOnce.Do(func() {
		file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDesc), len(file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDesc)))
	})
	return file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDescData
}

var file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_netbox_go_v1_wirelessWirelesslangroup_proto_goTypes = []any{
	(*CreateWirelessWirelesslangroupRequest)(nil),         // 0: api.netbox_go.v1.CreateWirelessWirelesslangroupRequest
	(*CreateWirelessWirelesslangroupReply)(nil),           // 1: api.netbox_go.v1.CreateWirelessWirelesslangroupReply
	(*DeleteWirelessWirelesslangroupByIDRequest)(nil),     // 2: api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDRequest
	(*DeleteWirelessWirelesslangroupByIDReply)(nil),       // 3: api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDReply
	(*UpdateWirelessWirelesslangroupByIDRequest)(nil),     // 4: api.netbox_go.v1.UpdateWirelessWirelesslangroupByIDRequest
	(*UpdateWirelessWirelesslangroupByIDReply)(nil),       // 5: api.netbox_go.v1.UpdateWirelessWirelesslangroupByIDReply
	(*WirelessWirelesslangroup)(nil),                      // 6: api.netbox_go.v1.WirelessWirelesslangroup
	(*GetWirelessWirelesslangroupByIDRequest)(nil),        // 7: api.netbox_go.v1.GetWirelessWirelesslangroupByIDRequest
	(*GetWirelessWirelesslangroupByIDReply)(nil),          // 8: api.netbox_go.v1.GetWirelessWirelesslangroupByIDReply
	(*ListWirelessWirelesslangroupRequest)(nil),           // 9: api.netbox_go.v1.ListWirelessWirelesslangroupRequest
	(*ListWirelessWirelesslangroupReply)(nil),             // 10: api.netbox_go.v1.ListWirelessWirelesslangroupReply
	(*DeleteWirelessWirelesslangroupByIDsRequest)(nil),    // 11: api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDsRequest
	(*DeleteWirelessWirelesslangroupByIDsReply)(nil),      // 12: api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDsReply
	(*GetWirelessWirelesslangroupByConditionRequest)(nil), // 13: api.netbox_go.v1.GetWirelessWirelesslangroupByConditionRequest
	(*GetWirelessWirelesslangroupByConditionReply)(nil),   // 14: api.netbox_go.v1.GetWirelessWirelesslangroupByConditionReply
	(*ListWirelessWirelesslangroupByIDsRequest)(nil),      // 15: api.netbox_go.v1.ListWirelessWirelesslangroupByIDsRequest
	(*ListWirelessWirelesslangroupByIDsReply)(nil),        // 16: api.netbox_go.v1.ListWirelessWirelesslangroupByIDsReply
	(*ListWirelessWirelesslangroupByLastIDRequest)(nil),   // 17: api.netbox_go.v1.ListWirelessWirelesslangroupByLastIDRequest
	(*ListWirelessWirelesslangroupByLastIDReply)(nil),     // 18: api.netbox_go.v1.ListWirelessWirelesslangroupByLastIDReply
	(*types.Params)(nil),                                  // 19: api.types.Params
	(*types.Conditions)(nil),                              // 20: api.types.Conditions
}
var file_api_netbox_go_v1_wirelessWirelesslangroup_proto_depIdxs = []int32{
	6,  // 0: api.netbox_go.v1.GetWirelessWirelesslangroupByIDReply.wirelessWirelesslangroup:type_name -> api.netbox_go.v1.WirelessWirelesslangroup
	19, // 1: api.netbox_go.v1.ListWirelessWirelesslangroupRequest.params:type_name -> api.types.Params
	6,  // 2: api.netbox_go.v1.ListWirelessWirelesslangroupReply.wirelessWirelesslangroups:type_name -> api.netbox_go.v1.WirelessWirelesslangroup
	20, // 3: api.netbox_go.v1.GetWirelessWirelesslangroupByConditionRequest.conditions:type_name -> api.types.Conditions
	6,  // 4: api.netbox_go.v1.GetWirelessWirelesslangroupByConditionReply.wirelessWirelesslangroup:type_name -> api.netbox_go.v1.WirelessWirelesslangroup
	6,  // 5: api.netbox_go.v1.ListWirelessWirelesslangroupByIDsReply.wirelessWirelesslangroups:type_name -> api.netbox_go.v1.WirelessWirelesslangroup
	6,  // 6: api.netbox_go.v1.ListWirelessWirelesslangroupByLastIDReply.wirelessWirelesslangroups:type_name -> api.netbox_go.v1.WirelessWirelesslangroup
	0,  // 7: api.netbox_go.v1.wirelessWirelesslangroup.Create:input_type -> api.netbox_go.v1.CreateWirelessWirelesslangroupRequest
	2,  // 8: api.netbox_go.v1.wirelessWirelesslangroup.DeleteByID:input_type -> api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDRequest
	4,  // 9: api.netbox_go.v1.wirelessWirelesslangroup.UpdateByID:input_type -> api.netbox_go.v1.UpdateWirelessWirelesslangroupByIDRequest
	7,  // 10: api.netbox_go.v1.wirelessWirelesslangroup.GetByID:input_type -> api.netbox_go.v1.GetWirelessWirelesslangroupByIDRequest
	9,  // 11: api.netbox_go.v1.wirelessWirelesslangroup.List:input_type -> api.netbox_go.v1.ListWirelessWirelesslangroupRequest
	11, // 12: api.netbox_go.v1.wirelessWirelesslangroup.DeleteByIDs:input_type -> api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDsRequest
	13, // 13: api.netbox_go.v1.wirelessWirelesslangroup.GetByCondition:input_type -> api.netbox_go.v1.GetWirelessWirelesslangroupByConditionRequest
	15, // 14: api.netbox_go.v1.wirelessWirelesslangroup.ListByIDs:input_type -> api.netbox_go.v1.ListWirelessWirelesslangroupByIDsRequest
	17, // 15: api.netbox_go.v1.wirelessWirelesslangroup.ListByLastID:input_type -> api.netbox_go.v1.ListWirelessWirelesslangroupByLastIDRequest
	1,  // 16: api.netbox_go.v1.wirelessWirelesslangroup.Create:output_type -> api.netbox_go.v1.CreateWirelessWirelesslangroupReply
	3,  // 17: api.netbox_go.v1.wirelessWirelesslangroup.DeleteByID:output_type -> api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDReply
	5,  // 18: api.netbox_go.v1.wirelessWirelesslangroup.UpdateByID:output_type -> api.netbox_go.v1.UpdateWirelessWirelesslangroupByIDReply
	8,  // 19: api.netbox_go.v1.wirelessWirelesslangroup.GetByID:output_type -> api.netbox_go.v1.GetWirelessWirelesslangroupByIDReply
	10, // 20: api.netbox_go.v1.wirelessWirelesslangroup.List:output_type -> api.netbox_go.v1.ListWirelessWirelesslangroupReply
	12, // 21: api.netbox_go.v1.wirelessWirelesslangroup.DeleteByIDs:output_type -> api.netbox_go.v1.DeleteWirelessWirelesslangroupByIDsReply
	14, // 22: api.netbox_go.v1.wirelessWirelesslangroup.GetByCondition:output_type -> api.netbox_go.v1.GetWirelessWirelesslangroupByConditionReply
	16, // 23: api.netbox_go.v1.wirelessWirelesslangroup.ListByIDs:output_type -> api.netbox_go.v1.ListWirelessWirelesslangroupByIDsReply
	18, // 24: api.netbox_go.v1.wirelessWirelesslangroup.ListByLastID:output_type -> api.netbox_go.v1.ListWirelessWirelesslangroupByLastIDReply
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_netbox_go_v1_wirelessWirelesslangroup_proto_init() }
func file_api_netbox_go_v1_wirelessWirelesslangroup_proto_init() {
	if File_api_netbox_go_v1_wirelessWirelesslangroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDesc), len(file_api_netbox_go_v1_wirelessWirelesslangroup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_netbox_go_v1_wirelessWirelesslangroup_proto_goTypes,
		DependencyIndexes: file_api_netbox_go_v1_wirelessWirelesslangroup_proto_depIdxs,
		MessageInfos:      file_api_netbox_go_v1_wirelessWirelesslangroup_proto_msgTypes,
	}.Build()
	File_api_netbox_go_v1_wirelessWirelesslangroup_proto = out.File
	file_api_netbox_go_v1_wirelessWirelesslangroup_proto_goTypes = nil
	file_api_netbox_go_v1_wirelessWirelesslangroup_proto_depIdxs = nil
}
