// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/netbox_go/v1/wirelessWirelesslink.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "netbox-go/api/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWirelessWirelesslinkRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Created             string                 `protobuf:"bytes,1,opt,name=created,proto3" json:"created"`
	LastUpdated         string                 `protobuf:"bytes,2,opt,name=lastUpdated,proto3" json:"lastUpdated"`
	CustomFieldData     string                 `protobuf:"bytes,3,opt,name=customFieldData,proto3" json:"customFieldData"`
	Ssid                string                 `protobuf:"bytes,4,opt,name=ssid,proto3" json:"ssid"`
	Status              string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status"`
	Description         string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	AuthCipher          string                 `protobuf:"bytes,7,opt,name=authCipher,proto3" json:"authCipher"`
	AuthPsk             string                 `protobuf:"bytes,8,opt,name=authPsk,proto3" json:"authPsk"`
	AuthType            string                 `protobuf:"bytes,9,opt,name=authType,proto3" json:"authType"`
	XInterfaceADeviceID int64                  `protobuf:"varint,10,opt,name=xInterfaceADeviceID,proto3" json:"xInterfaceADeviceID"`
	XInterfaceBDeviceID int64                  `protobuf:"varint,11,opt,name=xInterfaceBDeviceID,proto3" json:"xInterfaceBDeviceID"`
	InterfaceAID        int64                  `protobuf:"varint,12,opt,name=interfaceAID,proto3" json:"interfaceAID"`
	InterfaceBID        int64                  `protobuf:"varint,13,opt,name=interfaceBID,proto3" json:"interfaceBID"`
	TenantID            int64                  `protobuf:"varint,14,opt,name=tenantID,proto3" json:"tenantID"`
	Comments            string                 `protobuf:"bytes,15,opt,name=comments,proto3" json:"comments"`
	XAbsDistance        string                 `protobuf:"bytes,16,opt,name=xAbsDistance,proto3" json:"xAbsDistance"`
	Distance            string                 `protobuf:"bytes,17,opt,name=distance,proto3" json:"distance"`
	DistanceUnit        string                 `protobuf:"bytes,18,opt,name=distanceUnit,proto3" json:"distanceUnit"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateWirelessWirelesslinkRequest) Reset() {
	*x = CreateWirelessWirelesslinkRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWirelessWirelesslinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWirelessWirelesslinkRequest) ProtoMessage() {}

func (x *CreateWirelessWirelesslinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWirelessWirelesslinkRequest.ProtoReflect.Descriptor instead.
func (*CreateWirelessWirelesslinkRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWirelessWirelesslinkRequest) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetCustomFieldData() string {
	if x != nil {
		return x.CustomFieldData
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetAuthCipher() string {
	if x != nil {
		return x.AuthCipher
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetAuthPsk() string {
	if x != nil {
		return x.AuthPsk
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetXInterfaceADeviceID() int64 {
	if x != nil {
		return x.XInterfaceADeviceID
	}
	return 0
}

func (x *CreateWirelessWirelesslinkRequest) GetXInterfaceBDeviceID() int64 {
	if x != nil {
		return x.XInterfaceBDeviceID
	}
	return 0
}

func (x *CreateWirelessWirelesslinkRequest) GetInterfaceAID() int64 {
	if x != nil {
		return x.InterfaceAID
	}
	return 0
}

func (x *CreateWirelessWirelesslinkRequest) GetInterfaceBID() int64 {
	if x != nil {
		return x.InterfaceBID
	}
	return 0
}

func (x *CreateWirelessWirelesslinkRequest) GetTenantID() int64 {
	if x != nil {
		return x.TenantID
	}
	return 0
}

func (x *CreateWirelessWirelesslinkRequest) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetXAbsDistance() string {
	if x != nil {
		return x.XAbsDistance
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *CreateWirelessWirelesslinkRequest) GetDistanceUnit() string {
	if x != nil {
		return x.DistanceUnit
	}
	return ""
}

type CreateWirelessWirelesslinkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWirelessWirelesslinkReply) Reset() {
	*x = CreateWirelessWirelesslinkReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWirelessWirelesslinkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWirelessWirelesslinkReply) ProtoMessage() {}

func (x *CreateWirelessWirelesslinkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWirelessWirelesslinkReply.ProtoReflect.Descriptor instead.
func (*CreateWirelessWirelesslinkReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWirelessWirelesslinkReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWirelessWirelesslinkByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWirelessWirelesslinkByIDRequest) Reset() {
	*x = DeleteWirelessWirelesslinkByIDRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWirelessWirelesslinkByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWirelessWirelesslinkByIDRequest) ProtoMessage() {}

func (x *DeleteWirelessWirelesslinkByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWirelessWirelesslinkByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteWirelessWirelesslinkByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteWirelessWirelesslinkByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWirelessWirelesslinkByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWirelessWirelesslinkByIDReply) Reset() {
	*x = DeleteWirelessWirelesslinkByIDReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWirelessWirelesslinkByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWirelessWirelesslinkByIDReply) ProtoMessage() {}

func (x *DeleteWirelessWirelesslinkByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWirelessWirelesslinkByIDReply.ProtoReflect.Descriptor instead.
func (*DeleteWirelessWirelesslinkByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{3}
}

type UpdateWirelessWirelesslinkByIDRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	Created             string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created"`
	LastUpdated         string                 `protobuf:"bytes,3,opt,name=lastUpdated,proto3" json:"lastUpdated"`
	CustomFieldData     string                 `protobuf:"bytes,4,opt,name=customFieldData,proto3" json:"customFieldData"`
	Ssid                string                 `protobuf:"bytes,5,opt,name=ssid,proto3" json:"ssid"`
	Status              string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status"`
	Description         string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description"`
	AuthCipher          string                 `protobuf:"bytes,8,opt,name=authCipher,proto3" json:"authCipher"`
	AuthPsk             string                 `protobuf:"bytes,9,opt,name=authPsk,proto3" json:"authPsk"`
	AuthType            string                 `protobuf:"bytes,10,opt,name=authType,proto3" json:"authType"`
	XInterfaceADeviceID int64                  `protobuf:"varint,11,opt,name=xInterfaceADeviceID,proto3" json:"xInterfaceADeviceID"`
	XInterfaceBDeviceID int64                  `protobuf:"varint,12,opt,name=xInterfaceBDeviceID,proto3" json:"xInterfaceBDeviceID"`
	InterfaceAID        int64                  `protobuf:"varint,13,opt,name=interfaceAID,proto3" json:"interfaceAID"`
	InterfaceBID        int64                  `protobuf:"varint,14,opt,name=interfaceBID,proto3" json:"interfaceBID"`
	TenantID            int64                  `protobuf:"varint,15,opt,name=tenantID,proto3" json:"tenantID"`
	Comments            string                 `protobuf:"bytes,16,opt,name=comments,proto3" json:"comments"`
	XAbsDistance        string                 `protobuf:"bytes,17,opt,name=xAbsDistance,proto3" json:"xAbsDistance"`
	Distance            string                 `protobuf:"bytes,18,opt,name=distance,proto3" json:"distance"`
	DistanceUnit        string                 `protobuf:"bytes,19,opt,name=distanceUnit,proto3" json:"distanceUnit"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateWirelessWirelesslinkByIDRequest) Reset() {
	*x = UpdateWirelessWirelesslinkByIDRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWirelessWirelesslinkByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWirelessWirelesslinkByIDRequest) ProtoMessage() {}

func (x *UpdateWirelessWirelesslinkByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWirelessWirelesslinkByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateWirelessWirelesslinkByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetCustomFieldData() string {
	if x != nil {
		return x.CustomFieldData
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetAuthCipher() string {
	if x != nil {
		return x.AuthCipher
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetAuthPsk() string {
	if x != nil {
		return x.AuthPsk
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetXInterfaceADeviceID() int64 {
	if x != nil {
		return x.XInterfaceADeviceID
	}
	return 0
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetXInterfaceBDeviceID() int64 {
	if x != nil {
		return x.XInterfaceBDeviceID
	}
	return 0
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetInterfaceAID() int64 {
	if x != nil {
		return x.InterfaceAID
	}
	return 0
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetInterfaceBID() int64 {
	if x != nil {
		return x.InterfaceBID
	}
	return 0
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetTenantID() int64 {
	if x != nil {
		return x.TenantID
	}
	return 0
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetXAbsDistance() string {
	if x != nil {
		return x.XAbsDistance
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *UpdateWirelessWirelesslinkByIDRequest) GetDistanceUnit() string {
	if x != nil {
		return x.DistanceUnit
	}
	return ""
}

type UpdateWirelessWirelesslinkByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWirelessWirelesslinkByIDReply) Reset() {
	*x = UpdateWirelessWirelesslinkByIDReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWirelessWirelesslinkByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWirelessWirelesslinkByIDReply) ProtoMessage() {}

func (x *UpdateWirelessWirelesslinkByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWirelessWirelesslinkByIDReply.ProtoReflect.Descriptor instead.
func (*UpdateWirelessWirelesslinkByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{5}
}

type WirelessWirelesslink struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Created             string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created"`
	LastUpdated         string                 `protobuf:"bytes,3,opt,name=lastUpdated,proto3" json:"lastUpdated"`
	CustomFieldData     string                 `protobuf:"bytes,4,opt,name=customFieldData,proto3" json:"customFieldData"`
	Ssid                string                 `protobuf:"bytes,5,opt,name=ssid,proto3" json:"ssid"`
	Status              string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status"`
	Description         string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description"`
	AuthCipher          string                 `protobuf:"bytes,8,opt,name=authCipher,proto3" json:"authCipher"`
	AuthPsk             string                 `protobuf:"bytes,9,opt,name=authPsk,proto3" json:"authPsk"`
	AuthType            string                 `protobuf:"bytes,10,opt,name=authType,proto3" json:"authType"`
	XInterfaceADeviceID int64                  `protobuf:"varint,11,opt,name=xInterfaceADeviceID,proto3" json:"xInterfaceADeviceID"`
	XInterfaceBDeviceID int64                  `protobuf:"varint,12,opt,name=xInterfaceBDeviceID,proto3" json:"xInterfaceBDeviceID"`
	InterfaceAID        int64                  `protobuf:"varint,13,opt,name=interfaceAID,proto3" json:"interfaceAID"`
	InterfaceBID        int64                  `protobuf:"varint,14,opt,name=interfaceBID,proto3" json:"interfaceBID"`
	TenantID            int64                  `protobuf:"varint,15,opt,name=tenantID,proto3" json:"tenantID"`
	Comments            string                 `protobuf:"bytes,16,opt,name=comments,proto3" json:"comments"`
	XAbsDistance        string                 `protobuf:"bytes,17,opt,name=xAbsDistance,proto3" json:"xAbsDistance"`
	Distance            string                 `protobuf:"bytes,18,opt,name=distance,proto3" json:"distance"`
	DistanceUnit        string                 `protobuf:"bytes,19,opt,name=distanceUnit,proto3" json:"distanceUnit"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WirelessWirelesslink) Reset() {
	*x = WirelessWirelesslink{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WirelessWirelesslink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WirelessWirelesslink) ProtoMessage() {}

func (x *WirelessWirelesslink) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WirelessWirelesslink.ProtoReflect.Descriptor instead.
func (*WirelessWirelesslink) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{6}
}

func (x *WirelessWirelesslink) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WirelessWirelesslink) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *WirelessWirelesslink) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *WirelessWirelesslink) GetCustomFieldData() string {
	if x != nil {
		return x.CustomFieldData
	}
	return ""
}

func (x *WirelessWirelesslink) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *WirelessWirelesslink) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WirelessWirelesslink) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WirelessWirelesslink) GetAuthCipher() string {
	if x != nil {
		return x.AuthCipher
	}
	return ""
}

func (x *WirelessWirelesslink) GetAuthPsk() string {
	if x != nil {
		return x.AuthPsk
	}
	return ""
}

func (x *WirelessWirelesslink) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *WirelessWirelesslink) GetXInterfaceADeviceID() int64 {
	if x != nil {
		return x.XInterfaceADeviceID
	}
	return 0
}

func (x *WirelessWirelesslink) GetXInterfaceBDeviceID() int64 {
	if x != nil {
		return x.XInterfaceBDeviceID
	}
	return 0
}

func (x *WirelessWirelesslink) GetInterfaceAID() int64 {
	if x != nil {
		return x.InterfaceAID
	}
	return 0
}

func (x *WirelessWirelesslink) GetInterfaceBID() int64 {
	if x != nil {
		return x.InterfaceBID
	}
	return 0
}

func (x *WirelessWirelesslink) GetTenantID() int64 {
	if x != nil {
		return x.TenantID
	}
	return 0
}

func (x *WirelessWirelesslink) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *WirelessWirelesslink) GetXAbsDistance() string {
	if x != nil {
		return x.XAbsDistance
	}
	return ""
}

func (x *WirelessWirelesslink) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *WirelessWirelesslink) GetDistanceUnit() string {
	if x != nil {
		return x.DistanceUnit
	}
	return ""
}

type GetWirelessWirelesslinkByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWirelessWirelesslinkByIDRequest) Reset() {
	*x = GetWirelessWirelesslinkByIDRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWirelessWirelesslinkByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWirelessWirelesslinkByIDRequest) ProtoMessage() {}

func (x *GetWirelessWirelesslinkByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWirelessWirelesslinkByIDRequest.ProtoReflect.Descriptor instead.
func (*GetWirelessWirelesslinkByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{7}
}

func (x *GetWirelessWirelesslinkByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWirelessWirelesslinkByIDReply struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WirelessWirelesslink *WirelessWirelesslink  `protobuf:"bytes,1,opt,name=wirelessWirelesslink,proto3" json:"wirelessWirelesslink"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetWirelessWirelesslinkByIDReply) Reset() {
	*x = GetWirelessWirelesslinkByIDReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWirelessWirelesslinkByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWirelessWirelesslinkByIDReply) ProtoMessage() {}

func (x *GetWirelessWirelesslinkByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWirelessWirelesslinkByIDReply.ProtoReflect.Descriptor instead.
func (*GetWirelessWirelesslinkByIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{8}
}

func (x *GetWirelessWirelesslinkByIDReply) GetWirelessWirelesslink() *WirelessWirelesslink {
	if x != nil {
		return x.WirelessWirelesslink
	}
	return nil
}

type ListWirelessWirelesslinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *types.Params          `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWirelessWirelesslinkRequest) Reset() {
	*x = ListWirelessWirelesslinkRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslinkRequest) ProtoMessage() {}

func (x *ListWirelessWirelesslinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslinkRequest.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslinkRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{9}
}

func (x *ListWirelessWirelesslinkRequest) GetParams() *types.Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type ListWirelessWirelesslinkReply struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	Total                 int64                   `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	WirelessWirelesslinks []*WirelessWirelesslink `protobuf:"bytes,2,rep,name=wirelessWirelesslinks,proto3" json:"wirelessWirelesslinks"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListWirelessWirelesslinkReply) Reset() {
	*x = ListWirelessWirelesslinkReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslinkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslinkReply) ProtoMessage() {}

func (x *ListWirelessWirelesslinkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslinkReply.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslinkReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{10}
}

func (x *ListWirelessWirelesslinkReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWirelessWirelesslinkReply) GetWirelessWirelesslinks() []*WirelessWirelesslink {
	if x != nil {
		return x.WirelessWirelesslinks
	}
	return nil
}

type DeleteWirelessWirelesslinkByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWirelessWirelesslinkByIDsRequest) Reset() {
	*x = DeleteWirelessWirelesslinkByIDsRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWirelessWirelesslinkByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWirelessWirelesslinkByIDsRequest) ProtoMessage() {}

func (x *DeleteWirelessWirelesslinkByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWirelessWirelesslinkByIDsRequest.ProtoReflect.Descriptor instead.
func (*DeleteWirelessWirelesslinkByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteWirelessWirelesslinkByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteWirelessWirelesslinkByIDsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWirelessWirelesslinkByIDsReply) Reset() {
	*x = DeleteWirelessWirelesslinkByIDsReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWirelessWirelesslinkByIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWirelessWirelesslinkByIDsReply) ProtoMessage() {}

func (x *DeleteWirelessWirelesslinkByIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWirelessWirelesslinkByIDsReply.ProtoReflect.Descriptor instead.
func (*DeleteWirelessWirelesslinkByIDsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{12}
}

type GetWirelessWirelesslinkByConditionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    *types.Conditions      `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWirelessWirelesslinkByConditionRequest) Reset() {
	*x = GetWirelessWirelesslinkByConditionRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWirelessWirelesslinkByConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWirelessWirelesslinkByConditionRequest) ProtoMessage() {}

func (x *GetWirelessWirelesslinkByConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWirelessWirelesslinkByConditionRequest.ProtoReflect.Descriptor instead.
func (*GetWirelessWirelesslinkByConditionRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{13}
}

func (x *GetWirelessWirelesslinkByConditionRequest) GetConditions() *types.Conditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type GetWirelessWirelesslinkByConditionReply struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WirelessWirelesslink *WirelessWirelesslink  `protobuf:"bytes,1,opt,name=wirelessWirelesslink,proto3" json:"wirelessWirelesslink"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetWirelessWirelesslinkByConditionReply) Reset() {
	*x = GetWirelessWirelesslinkByConditionReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWirelessWirelesslinkByConditionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWirelessWirelesslinkByConditionReply) ProtoMessage() {}

func (x *GetWirelessWirelesslinkByConditionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWirelessWirelesslinkByConditionReply.ProtoReflect.Descriptor instead.
func (*GetWirelessWirelesslinkByConditionReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{14}
}

func (x *GetWirelessWirelesslinkByConditionReply) GetWirelessWirelesslink() *WirelessWirelesslink {
	if x != nil {
		return x.WirelessWirelesslink
	}
	return nil
}

type ListWirelessWirelesslinkByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWirelessWirelesslinkByIDsRequest) Reset() {
	*x = ListWirelessWirelesslinkByIDsRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslinkByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslinkByIDsRequest) ProtoMessage() {}

func (x *ListWirelessWirelesslinkByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslinkByIDsRequest.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslinkByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{15}
}

func (x *ListWirelessWirelesslinkByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListWirelessWirelesslinkByIDsReply struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	WirelessWirelesslinks []*WirelessWirelesslink `protobuf:"bytes,1,rep,name=wirelessWirelesslinks,proto3" json:"wirelessWirelesslinks"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListWirelessWirelesslinkByIDsReply) Reset() {
	*x = ListWirelessWirelesslinkByIDsReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslinkByIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslinkByIDsReply) ProtoMessage() {}

func (x *ListWirelessWirelesslinkByIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslinkByIDsReply.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslinkByIDsReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{16}
}

func (x *ListWirelessWirelesslinkByIDsReply) GetWirelessWirelesslinks() []*WirelessWirelesslink {
	if x != nil {
		return x.WirelessWirelesslinks
	}
	return nil
}

type ListWirelessWirelesslinkByLastIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastID        uint64                 `protobuf:"varint,1,opt,name=lastID,proto3" json:"lastID" form:"lastID"` // last id
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit" form:"limit"`    // limit size per page
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort" form:"sort"`        // sort by column name of table, default is -id, the - sign indicates descending order.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWirelessWirelesslinkByLastIDRequest) Reset() {
	*x = ListWirelessWirelesslinkByLastIDRequest{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslinkByLastIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslinkByLastIDRequest) ProtoMessage() {}

func (x *ListWirelessWirelesslinkByLastIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslinkByLastIDRequest.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslinkByLastIDRequest) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{17}
}

func (x *ListWirelessWirelesslinkByLastIDRequest) GetLastID() uint64 {
	if x != nil {
		return x.LastID
	}
	return 0
}

func (x *ListWirelessWirelesslinkByLastIDRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWirelessWirelesslinkByLastIDRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListWirelessWirelesslinkByLastIDReply struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	WirelessWirelesslinks []*WirelessWirelesslink `protobuf:"bytes,1,rep,name=wirelessWirelesslinks,proto3" json:"wirelessWirelesslinks"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListWirelessWirelesslinkByLastIDReply) Reset() {
	*x = ListWirelessWirelesslinkByLastIDReply{}
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWirelessWirelesslinkByLastIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWirelessWirelesslinkByLastIDReply) ProtoMessage() {}

func (x *ListWirelessWirelesslinkByLastIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWirelessWirelesslinkByLastIDReply.ProtoReflect.Descriptor instead.
func (*ListWirelessWirelesslinkByLastIDReply) Descriptor() ([]byte, []int) {
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP(), []int{18}
}

func (x *ListWirelessWirelesslinkByLastIDReply) GetWirelessWirelesslinks() []*WirelessWirelesslink {
	if x != nil {
		return x.WirelessWirelesslinks
	}
	return nil
}

var File_api_netbox_go_v1_wirelessWirelesslink_proto protoreflect.FileDescriptor

const file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDesc = "" +
	"\n" +
	"+api/netbox_go/v1/wirelessWirelesslink.proto\x12\x10api.netbox_go.v1\x1a\x15api/types/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x13tagger/tagger.proto\x1a\x17validate/validate.proto\"\xf5\x04\n" +
	"!CreateWirelessWirelesslinkRequest\x12\x18\n" +
	"\acreated\x18\x01 \x01(\tR\acreated\x12 \n" +
	"\vlastUpdated\x18\x02 \x01(\tR\vlastUpdated\x12(\n" +
	"\x0fcustomFieldData\x18\x03 \x01(\tR\x0fcustomFieldData\x12\x12\n" +
	"\x04ssid\x18\x04 \x01(\tR\x04ssid\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"authCipher\x18\a \x01(\tR\n" +
	"authCipher\x12\x18\n" +
	"\aauthPsk\x18\b \x01(\tR\aauthPsk\x12\x1a\n" +
	"\bauthType\x18\t \x01(\tR\bauthType\x120\n" +
	"\x13xInterfaceADeviceID\x18\n" +
	" \x01(\x03R\x13xInterfaceADeviceID\x120\n" +
	"\x13xInterfaceBDeviceID\x18\v \x01(\x03R\x13xInterfaceBDeviceID\x12\"\n" +
	"\finterfaceAID\x18\f \x01(\x03R\finterfaceAID\x12\"\n" +
	"\finterfaceBID\x18\r \x01(\x03R\finterfaceBID\x12\x1a\n" +
	"\btenantID\x18\x0e \x01(\x03R\btenantID\x12\x1a\n" +
	"\bcomments\x18\x0f \x01(\tR\bcomments\x12\"\n" +
	"\fxAbsDistance\x18\x10 \x01(\tR\fxAbsDistance\x12\x1a\n" +
	"\bdistance\x18\x11 \x01(\tR\bdistance\x12\"\n" +
	"\fdistanceUnit\x18\x12 \x01(\tR\fdistanceUnit\"1\n" +
	"\x1fCreateWirelessWirelesslinkReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"M\n" +
	"%DeleteWirelessWirelesslinkByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"%\n" +
	"#DeleteWirelessWirelesslinkByIDReply\"\x9f\x05\n" +
	"%UpdateWirelessWirelesslinkByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12 \n" +
	"\vlastUpdated\x18\x03 \x01(\tR\vlastUpdated\x12(\n" +
	"\x0fcustomFieldData\x18\x04 \x01(\tR\x0fcustomFieldData\x12\x12\n" +
	"\x04ssid\x18\x05 \x01(\tR\x04ssid\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"authCipher\x18\b \x01(\tR\n" +
	"authCipher\x12\x18\n" +
	"\aauthPsk\x18\t \x01(\tR\aauthPsk\x12\x1a\n" +
	"\bauthType\x18\n" +
	" \x01(\tR\bauthType\x120\n" +
	"\x13xInterfaceADeviceID\x18\v \x01(\x03R\x13xInterfaceADeviceID\x120\n" +
	"\x13xInterfaceBDeviceID\x18\f \x01(\x03R\x13xInterfaceBDeviceID\x12\"\n" +
	"\finterfaceAID\x18\r \x01(\x03R\finterfaceAID\x12\"\n" +
	"\finterfaceBID\x18\x0e \x01(\x03R\finterfaceBID\x12\x1a\n" +
	"\btenantID\x18\x0f \x01(\x03R\btenantID\x12\x1a\n" +
	"\bcomments\x18\x10 \x01(\tR\bcomments\x12\"\n" +
	"\fxAbsDistance\x18\x11 \x01(\tR\fxAbsDistance\x12\x1a\n" +
	"\bdistance\x18\x12 \x01(\tR\bdistance\x12\"\n" +
	"\fdistanceUnit\x18\x13 \x01(\tR\fdistanceUnit\"%\n" +
	"#UpdateWirelessWirelesslinkByIDReply\"\xf8\x04\n" +
	"\x14WirelessWirelesslink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12 \n" +
	"\vlastUpdated\x18\x03 \x01(\tR\vlastUpdated\x12(\n" +
	"\x0fcustomFieldData\x18\x04 \x01(\tR\x0fcustomFieldData\x12\x12\n" +
	"\x04ssid\x18\x05 \x01(\tR\x04ssid\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"authCipher\x18\b \x01(\tR\n" +
	"authCipher\x12\x18\n" +
	"\aauthPsk\x18\t \x01(\tR\aauthPsk\x12\x1a\n" +
	"\bauthType\x18\n" +
	" \x01(\tR\bauthType\x120\n" +
	"\x13xInterfaceADeviceID\x18\v \x01(\x03R\x13xInterfaceADeviceID\x120\n" +
	"\x13xInterfaceBDeviceID\x18\f \x01(\x03R\x13xInterfaceBDeviceID\x12\"\n" +
	"\finterfaceAID\x18\r \x01(\x03R\finterfaceAID\x12\"\n" +
	"\finterfaceBID\x18\x0e \x01(\x03R\finterfaceBID\x12\x1a\n" +
	"\btenantID\x18\x0f \x01(\x03R\btenantID\x12\x1a\n" +
	"\bcomments\x18\x10 \x01(\tR\bcomments\x12\"\n" +
	"\fxAbsDistance\x18\x11 \x01(\tR\fxAbsDistance\x12\x1a\n" +
	"\bdistance\x18\x12 \x01(\tR\bdistance\x12\"\n" +
	"\fdistanceUnit\x18\x13 \x01(\tR\fdistanceUnit\"J\n" +
	"\"GetWirelessWirelesslinkByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02 \x00\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"~\n" +
	" GetWirelessWirelesslinkByIDReply\x12Z\n" +
	"\x14wirelessWirelesslink\x18\x01 \x01(\v2&.api.netbox_go.v1.WirelessWirelesslinkR\x14wirelessWirelesslink\"L\n" +
	"\x1fListWirelessWirelesslinkRequest\x12)\n" +
	"\x06params\x18\x01 \x01(\v2\x11.api.types.ParamsR\x06params\"\x93\x01\n" +
	"\x1dListWirelessWirelesslinkReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\\\n" +
	"\x15wirelessWirelesslinks\x18\x02 \x03(\v2&.api.netbox_go.v1.WirelessWirelesslinkR\x15wirelessWirelesslinks\"D\n" +
	"&DeleteWirelessWirelesslinkByIDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"&\n" +
	"$DeleteWirelessWirelesslinkByIDsReply\"b\n" +
	")GetWirelessWirelesslinkByConditionRequest\x125\n" +
	"\n" +
	"conditions\x18\x01 \x01(\v2\x15.api.types.ConditionsR\n" +
	"conditions\"\x85\x01\n" +
	"'GetWirelessWirelesslinkByConditionReply\x12Z\n" +
	"\x14wirelessWirelesslink\x18\x01 \x01(\v2&.api.netbox_go.v1.WirelessWirelesslinkR\x14wirelessWirelesslink\"B\n" +
	"$ListWirelessWirelesslinkByIDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"\x82\x01\n" +
	"\"ListWirelessWirelesslinkByIDsReply\x12\\\n" +
	"\x15wirelessWirelesslinks\x18\x01 \x03(\v2&.api.netbox_go.v1.WirelessWirelesslinkR\x15wirelessWirelesslinks\"\xab\x01\n" +
	"'ListWirelessWirelesslinkByLastIDRequest\x12*\n" +
	"\x06lastID\x18\x01 \x01(\x04B\x12\x9a\x84\x9e\x03\rform:\"lastID\"R\x06lastID\x12.\n" +
	"\x05limit\x18\x02 \x01(\rB\x18\xfaB\x04*\x02 \x00\x9a\x84\x9e\x03\fform:\"limit\"R\x05limit\x12$\n" +
	"\x04sort\x18\x03 \x01(\tB\x10\x9a\x84\x9e\x03\vform:\"sort\"R\x04sort\"\x85\x01\n" +
	"%ListWirelessWirelesslinkByLastIDReply\x12\\\n" +
	"\x15wirelessWirelesslinks\x18\x01 \x03(\v2&.api.netbox_go.v1.WirelessWirelesslinkR\x15wirelessWirelesslinks2\x89\f\n" +
	"\x14wirelessWirelesslink\x12\x98\x01\n" +
	"\x06Create\x123.api.netbox_go.v1.CreateWirelessWirelesslinkRequest\x1a1.api.netbox_go.v1.CreateWirelessWirelesslinkReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/wireless/wirelesslinks\x12\xa6\x01\n" +
	"\n" +
	"DeleteByID\x127.api.netbox_go.v1.DeleteWirelessWirelesslinkByIDRequest\x1a5.api.netbox_go.v1.DeleteWirelessWirelesslinkByIDReply\"(\x82\xd3\xe4\x93\x02\"* /api/wireless/wirelesslinks/{id}\x12\xa9\x01\n" +
	"\n" +
	"UpdateByID\x127.api.netbox_go.v1.UpdateWirelessWirelesslinkByIDRequest\x1a5.api.netbox_go.v1.UpdateWirelessWirelesslinkByIDReply\"+\x82\xd3\xe4\x93\x02%:\x01*\x1a /api/wireless/wirelesslinks/{id}\x12\x9d\x01\n" +
	"\aGetByID\x124.api.netbox_go.v1.GetWirelessWirelesslinkByIDRequest\x1a2.api.netbox_go.v1.GetWirelessWirelesslinkByIDReply\"(\x82\xd3\xe4\x93\x02\"\x12 /api/wireless/wirelesslinks/{id}\x12\x97\x01\n" +
	"\x04List\x121.api.netbox_go.v1.ListWirelessWirelesslinkRequest\x1a/.api.netbox_go.v1.ListWirelessWirelesslinkReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/wireless/wirelesslinks/list\x12\xb2\x01\n" +
	"\vDeleteByIDs\x128.api.netbox_go.v1.DeleteWirelessWirelesslinkByIDsRequest\x1a6.api.netbox_go.v1.DeleteWirelessWirelesslinkByIDsReply\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/wireless/wirelesslinks/delete/ids\x12\xba\x01\n" +
	"\x0eGetByCondition\x12;.api.netbox_go.v1.GetWirelessWirelesslinkByConditionRequest\x1a9.api.netbox_go.v1.GetWirelessWirelesslinkByConditionReply\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/wireless/wirelesslinks/condition\x12\xaa\x01\n" +
	"\tListByIDs\x126.api.netbox_go.v1.ListWirelessWirelesslinkByIDsRequest\x1a4.api.netbox_go.v1.ListWirelessWirelesslinkByIDsReply\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/wireless/wirelesslinks/list/ids\x12\xa7\x01\n" +
	"\fListByLastID\x129.api.netbox_go.v1.ListWirelessWirelesslinkByLastIDRequest\x1a7.api.netbox_go.v1.ListWirelessWirelesslinkByLastIDReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/wireless/wirelesslinksB\xc3\x01\x92A\xa0\x01\x12\x1c\n" +
	"\x12netbox_go api docs2\x06v1.0.0\x1a\x0elocalhost:8080*\x02\x01\x022\x10application/json:\x10application/jsonZH\n" +
	"F\n" +
	"\n" +
	"BearerAuth\x128\b\x02\x12#Type Bearer your-jwt-token to Value\x1a\rAuthorization \x02Z\x1dnetbox-go/api/netbox_go/v1;v1b\x06proto3"

var (
	file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescOnce sync.Once
	file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescData []byte
)

func file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescGZIP() []byte {
	file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescOnce.Do(func() {
		file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDesc), len(file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDesc)))
	})
	return file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDescData
}

var file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_netbox_go_v1_wirelessWirelesslink_proto_goTypes = []any{
	(*CreateWirelessWirelesslinkRequest)(nil),         // 0: api.netbox_go.v1.CreateWirelessWirelesslinkRequest
	(*CreateWirelessWirelesslinkReply)(nil),           // 1: api.netbox_go.v1.CreateWirelessWirelesslinkReply
	(*DeleteWirelessWirelesslinkByIDRequest)(nil),     // 2: api.netbox_go.v1.DeleteWirelessWirelesslinkByIDRequest
	(*DeleteWirelessWirelesslinkByIDReply)(nil),       // 3: api.netbox_go.v1.DeleteWirelessWirelesslinkByIDReply
	(*UpdateWirelessWirelesslinkByIDRequest)(nil),     // 4: api.netbox_go.v1.UpdateWirelessWirelesslinkByIDRequest
	(*UpdateWirelessWirelesslinkByIDReply)(nil),       // 5: api.netbox_go.v1.UpdateWirelessWirelesslinkByIDReply
	(*WirelessWirelesslink)(nil),                      // 6: api.netbox_go.v1.WirelessWirelesslink
	(*GetWirelessWirelesslinkByIDRequest)(nil),        // 7: api.netbox_go.v1.GetWirelessWirelesslinkByIDRequest
	(*GetWirelessWirelesslinkByIDReply)(nil),          // 8: api.netbox_go.v1.GetWirelessWirelesslinkByIDReply
	(*ListWirelessWirelesslinkRequest)(nil),           // 9: api.netbox_go.v1.ListWirelessWirelesslinkRequest
	(*ListWirelessWirelesslinkReply)(nil),             // 10: api.netbox_go.v1.ListWirelessWirelesslinkReply
	(*DeleteWirelessWirelesslinkByIDsRequest)(nil),    // 11: api.netbox_go.v1.DeleteWirelessWirelesslinkByIDsRequest
	(*DeleteWirelessWirelesslinkByIDsReply)(nil),      // 12: api.netbox_go.v1.DeleteWirelessWirelesslinkByIDsReply
	(*GetWirelessWirelesslinkByConditionRequest)(nil), // 13: api.netbox_go.v1.GetWirelessWirelesslinkByConditionRequest
	(*GetWirelessWirelesslinkByConditionReply)(nil),   // 14: api.netbox_go.v1.GetWirelessWirelesslinkByConditionReply
	(*ListWirelessWirelesslinkByIDsRequest)(nil),      // 15: api.netbox_go.v1.ListWirelessWirelesslinkByIDsRequest
	(*ListWirelessWirelesslinkByIDsReply)(nil),        // 16: api.netbox_go.v1.ListWirelessWirelesslinkByIDsReply
	(*ListWirelessWirelesslinkByLastIDRequest)(nil),   // 17: api.netbox_go.v1.ListWirelessWirelesslinkByLastIDRequest
	(*ListWirelessWirelesslinkByLastIDReply)(nil),     // 18: api.netbox_go.v1.ListWirelessWirelesslinkByLastIDReply
	(*types.Params)(nil),                              // 19: api.types.Params
	(*types.Conditions)(nil),                          // 20: api.types.Conditions
}
var file_api_netbox_go_v1_wirelessWirelesslink_proto_depIdxs = []int32{
	6,  // 0: api.netbox_go.v1.GetWirelessWirelesslinkByIDReply.wirelessWirelesslink:type_name -> api.netbox_go.v1.WirelessWirelesslink
	19, // 1: api.netbox_go.v1.ListWirelessWirelesslinkRequest.params:type_name -> api.types.Params
	6,  // 2: api.netbox_go.v1.ListWirelessWirelesslinkReply.wirelessWirelesslinks:type_name -> api.netbox_go.v1.WirelessWirelesslink
	20, // 3: api.netbox_go.v1.GetWirelessWirelesslinkByConditionRequest.conditions:type_name -> api.types.Conditions
	6,  // 4: api.netbox_go.v1.GetWirelessWirelesslinkByConditionReply.wirelessWirelesslink:type_name -> api.netbox_go.v1.WirelessWirelesslink
	6,  // 5: api.netbox_go.v1.ListWirelessWirelesslinkByIDsReply.wirelessWirelesslinks:type_name -> api.netbox_go.v1.WirelessWirelesslink
	6,  // 6: api.netbox_go.v1.ListWirelessWirelesslinkByLastIDReply.wirelessWirelesslinks:type_name -> api.netbox_go.v1.WirelessWirelesslink
	0,  // 7: api.netbox_go.v1.wirelessWirelesslink.Create:input_type -> api.netbox_go.v1.CreateWirelessWirelesslinkRequest
	2,  // 8: api.netbox_go.v1.wirelessWirelesslink.DeleteByID:input_type -> api.netbox_go.v1.DeleteWirelessWirelesslinkByIDRequest
	4,  // 9: api.netbox_go.v1.wirelessWirelesslink.UpdateByID:input_type -> api.netbox_go.v1.UpdateWirelessWirelesslinkByIDRequest
	7,  // 10: api.netbox_go.v1.wirelessWirelesslink.GetByID:input_type -> api.netbox_go.v1.GetWirelessWirelesslinkByIDRequest
	9,  // 11: api.netbox_go.v1.wirelessWirelesslink.List:input_type -> api.netbox_go.v1.ListWirelessWirelesslinkRequest
	11, // 12: api.netbox_go.v1.wirelessWirelesslink.DeleteByIDs:input_type -> api.netbox_go.v1.DeleteWirelessWirelesslinkByIDsRequest
	13, // 13: api.netbox_go.v1.wirelessWirelesslink.GetByCondition:input_type -> api.netbox_go.v1.GetWirelessWirelesslinkByConditionRequest
	15, // 14: api.netbox_go.v1.wirelessWirelesslink.ListByIDs:input_type -> api.netbox_go.v1.ListWirelessWirelesslinkByIDsRequest
	17, // 15: api.netbox_go.v1.wirelessWirelesslink.ListByLastID:input_type -> api.netbox_go.v1.ListWirelessWirelesslinkByLastIDRequest
	1,  // 16: api.netbox_go.v1.wirelessWirelesslink.Create:output_type -> api.netbox_go.v1.CreateWirelessWirelesslinkReply
	3,  // 17: api.netbox_go.v1.wirelessWirelesslink.DeleteByID:output_type -> api.netbox_go.v1.DeleteWirelessWirelesslinkByIDReply
	5,  // 18: api.netbox_go.v1.wirelessWirelesslink.UpdateByID:output_type -> api.netbox_go.v1.UpdateWirelessWirelesslinkByIDReply
	8,  // 19: api.netbox_go.v1.wirelessWirelesslink.GetByID:output_type -> api.netbox_go.v1.GetWirelessWirelesslinkByIDReply
	10, // 20: api.netbox_go.v1.wirelessWirelesslink.List:output_type -> api.netbox_go.v1.ListWirelessWirelesslinkReply
	12, // 21: api.netbox_go.v1.wirelessWirelesslink.DeleteByIDs:output_type -> api.netbox_go.v1.DeleteWirelessWirelesslinkByIDsReply
	14, // 22: api.netbox_go.v1.wirelessWirelesslink.GetByCondition:output_type -> api.netbox_go.v1.GetWirelessWirelesslinkByConditionReply
	16, // 23: api.netbox_go.v1.wirelessWirelesslink.ListByIDs:output_type -> api.netbox_go.v1.ListWirelessWirelesslinkByIDsReply
	18, // 24: api.netbox_go.v1.wirelessWirelesslink.ListByLastID:output_type -> api.netbox_go.v1.ListWirelessWirelesslinkByLastIDReply
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_netbox_go_v1_wirelessWirelesslink_proto_init() }
func file_api_netbox_go_v1_wirelessWirelesslink_proto_init() {
	if File_api_netbox_go_v1_wirelessWirelesslink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDesc), len(file_api_netbox_go_v1_wirelessWirelesslink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_netbox_go_v1_wirelessWirelesslink_proto_goTypes,
		DependencyIndexes: file_api_netbox_go_v1_wirelessWirelesslink_proto_depIdxs,
		MessageInfos:      file_api_netbox_go_v1_wirelessWirelesslink_proto_msgTypes,
	}.Build()
	File_api_netbox_go_v1_wirelessWirelesslink_proto = out.File
	file_api_netbox_go_v1_wirelessWirelesslink_proto_goTypes = nil
	file_api_netbox_go_v1_wirelessWirelesslink_proto_depIdxs = nil
}
